apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: clustertemplatequotas.clustertemplate.openshift.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: cluster-aas-operator-webhook-service
          namespace: cluster-aas-operator-system
          path: /convert
      conversionReviewVersions:
      - v1
  group: clustertemplate.openshift.io
  names:
    kind: ClusterTemplateQuota
    listKind: ClusterTemplateQuotaList
    plural: clustertemplatequotas
    shortNames:
    - ctq
    - ctqs
    singular: clustertemplatequota
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Defines which ClusterTemplates can be used in a given namespace
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              allowedTemplates:
                description: Represents all ClusterTemplates which can be used in
                  given namespace
                items:
                  properties:
                    count:
                      description: Defines how many instances of the ClusterTemplate
                        can exist
                      minimum: 1
                      type: integer
                    deleteAfter:
                      description: 'Template instance will be removed after specified
                        time This is a Duration value; see https://pkg.go.dev/time#ParseDuration
                        for accepted formats. Note: due to discrepancies in validation
                        vs parsing, we use a Pattern instead of `Format=duration`.
                        See https://bugzilla.redhat.com/show_bug.cgi?id=2050332 https://github.com/kubernetes/apimachinery/issues/131
                        https://github.com/kubernetes/apiextensions-apiserver/issues/56'
                      pattern: ^([0-9]+(\.[0-9]+)?(ns|us|Âµs|ms|s|m|h))+$
                      type: string
                    name:
                      description: Name of the ClusterTemplate
                      type: string
                  required:
                  - name
                  type: object
                type: array
              budget:
                description: Total budget for all clusters within given namespace
                minimum: 1
                type: integer
            required:
            - allowedTemplates
            type: object
          status:
            description: ClusterTemplateQuotaStatus defines the observed state of
              ClusterTemplateQuota
            properties:
              budgetSpent:
                description: How much budget is currenly spent
                type: integer
              templateInstances:
                description: Which instances are in use
                items:
                  properties:
                    count:
                      description: Defines how many instances of the ClusterTemplate
                        exist
                      type: integer
                    name:
                      description: Name of the ClusterTemplate
                      type: string
                  required:
                  - count
                  - name
                  type: object
                type: array
            required:
            - budgetSpent
            - templateInstances
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
