apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: clustertemplatesetup.clustertemplate.openshift.io
spec:
  group: clustertemplate.openshift.io
  names:
    kind: ClusterTemplateSetup
    listKind: ClusterTemplateSetupList
    plural: clustertemplatesetup
    shortNames:
    - ctsetup
    - ctsetup
    singular: clustertemplatesetup
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Template of a cluster - post-install setup are defined as ArgoCD
          application set refs.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterSetup:
                description: Array of ArgoCD applicationset names which are used for
                  post installation setup of the cluster
                items:
                  type: string
                type: array
              skipClusterRegistration:
                description: Skip the registeration of the cluster to the hub cluster
                type: boolean
            type: object
          status:
            description: ClusterTemplateStatus defines the observed state of ClusterTemplateSetup
            properties:
              clusterSetup:
                description: Describes helm chart properties and schema for every
                  cluster setup step
                items:
                  properties:
                    error:
                      description: Contain information about failure during fetching
                        helm chart
                      type: string
                    name:
                      description: Name of the cluster setup step
                      type: string
                    params:
                      description: Helm chart param overrides from the ArgoCD ApplicationSet
                      items:
                        properties:
                          name:
                            description: Name of a helm chart param
                            type: string
                          value:
                            description: Value of a helm chart param
                            type: string
                        required:
                        - name
                        - value
                        type: object
                      type: array
                    schema:
                      description: Content of helm chart values.schema.json
                      type: string
                    values:
                      description: Content of helm chart values.yaml
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
