apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: clustertemplates.clustertemplate.openshift.io
spec:
  group: clustertemplate.openshift.io
  names:
    kind: ClusterTemplate
    listKind: ClusterTemplateList
    plural: clustertemplates
    shortNames:
    - ct
    - cts
    singular: clustertemplate
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Cluster cost
      jsonPath: .spec.cost
      name: Cost
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Template of a cluster - both installation and post-install setup
          are defined as ArgoCD application spec. Any application source is supported
          - typically a Helm chart
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterDefinition:
                description: ArgoCD applicationset name which is used for installation
                  of the cluster
                type: string
              clusterSetup:
                description: Array of ArgoCD applicationset names which are used for
                  post installation setup of the cluster
                items:
                  type: string
                type: array
              cost:
                description: Cost of the cluster, used for quotas
                minimum: 0
                type: integer
              skipClusterRegistration:
                description: Skip the registration of the cluster to the hub cluster
                type: boolean
            required:
            - clusterDefinition
            type: object
          status:
            description: ClusterTemplateStatus defines the observed state of ClusterTemplate
            properties:
              clusterDefinition:
                description: Describes helm chart properties and their schema
                properties:
                  error:
                    description: Contain information about failure during fetching
                      helm chart
                    type: string
                  schema:
                    description: Content of helm chart values.schema.json
                    type: string
                  values:
                    description: Content of helm chart values.yaml
                    type: string
                type: object
              clusterSetup:
                description: Describes helm chart properties and schema for every
                  cluster setup step
                items:
                  properties:
                    error:
                      description: Contain information about failure during fetching
                        helm chart
                      type: string
                    name:
                      description: Name of the cluster setup step
                      type: string
                    schema:
                      description: Content of helm chart values.schema.json
                      type: string
                    values:
                      description: Content of helm chart values.yaml
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
