# Source: dynatrace-operator/templates/Common/activegate/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-kubernetes-monitoring
  labels:
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/component: activegate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-kubernetes-monitoring
subjects:
  - kind: ServiceAccount
    name: dynatrace-activegate
    namespace: dynatrace
