apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "pulsar.streamnative.io/v1alpha1",
          "kind": "PulsarBroker",
          "metadata": {
            "name": "pulsarbroker-sample"
          },
          "spec": {
            "foo": "bar"
          }
        },
        {
          "apiVersion": "pulsar.streamnative.io/v1alpha1",
          "kind": "PulsarProxy",
          "metadata": {
            "name": "pulsar"
          },
          "spec": {
            "configMapName": "proxy-configmap",
            "image": "apachepulsar/pulsar:2.5.0",
            "imagePullPolicy": "Always",
            "replicas": 3
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Streaming & Messaging
    containerImage: quay.io/streamnativeio/pulsar-operator:v0.12.2
    createdAt: "2019-04-25T16:34:00Z"
    description: The Pulsar Operator manages the Pulsar service instances deployed
      on a Kubernetes cluster.
    operators.operatorframework.io/builder: operator-sdk-v1.23.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    support: StreamNative
  name: pulsar-operator.v0.12.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PulsarBroker is the Schema for the pulsarbrokers API
      displayName: Pulsar Broker
      kind: PulsarBroker
      name: pulsarbrokers.pulsar.streamnative.io
      version: v1alpha1
    - description: PulsarConnection is the Schema for the pulsarconnections API
      displayName: Pulsar Connection
      kind: PulsarConnection
      name: pulsarconnections.pulsar.streamnative.io
      version: v1alpha1
    - description: PulsarNamespace is the Schema for the pulsarnamespaces API
      displayName: Pulsar Namespace
      kind: PulsarNamespace
      name: pulsarnamespaces.pulsar.streamnative.io
      version: v1alpha1
    - description: PulsarPermission is the Schema for the pulsarpermissions API
      displayName: Pulsar Permission
      kind: PulsarPermission
      name: pulsarpermissions.pulsar.streamnative.io
      version: v1alpha1
    - description: PulsarProxy is the Schema for the pulsarproxies API
      displayName: Pulsar Proxy
      kind: PulsarProxy
      name: pulsarproxies.pulsar.streamnative.io
      version: v1alpha1
    - description: PulsarTenant is the Schema for the pulsartenants API
      displayName: Pulsar Tenant
      kind: PulsarTenant
      name: pulsartenants.pulsar.streamnative.io
      version: v1alpha1
    - description: PulsarTopic is the Schema for the pulsartopics API
      displayName: Pulsar Topic
      kind: PulsarTopic
      name: pulsartopics.pulsar.streamnative.io
      version: v1alpha1
  description: |
    The Pulsar Operator is a controller that manages Pulsar clusters in Kubernetes. It provides a full management life-cycle for Pulsar, including deployment, upgrades, scaling, and configuration changes. With the Pulsar Operator, Pulsar can run seamlessly in the Kubernetes clusters deployed on a public or private cloud. You can then manage Pulsar clusters using the Kubernetes Application Programming Interface (API) and the kubectl tool.

    Prerequisites:
    - Install cert-manager operator first.
  displayName: Pulsar Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAABaFBMVEUAAAAAkf8AACsAkf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8Akf8AACsAACsAACsAkf8AACsAACsAACsAACsAkf8Akf8AACsAkf8Akf8Akf8Akf8AACv////kwuOUAAAAdXRSTlMAAAAHJ1B1j5yfoEgcZrTl+20ScNT+/Vc6vfIBXOTZGmfxpgPw/F0z39IZDLJzX/rFFhHE7EZP+PNommICFfSuODTv59PH5vfozJNECVLbUSgUDSZCPCnheiC2MZ5hEEfKHk4LwKt/CDNX6zCr7v0EodR5gB08MC/9AAAAAWJLR0R3RmT51wAAAAlwSFlzAAArDwAAKw8BZQl82QAAAAd0SU1FB+YJBQsHNrqpLMMAAAKxSURBVFjDtZdnW+pAEIUzgOViQUEkGiuKGhURRAELYkPFir0XLIAU6/r7b2IIPbub+DhfyXueCdkzc5Zh/rKgev0KphUQn9Mbamrr6v+VlbGBQkDEG5uaTS2oSrWSBQTcbGmzoqrVbiMKCDzboYAj1MmSBAC4rm6kWD29QOT7+pV5ZB8AAg+2QQzvGAKSwPAIhkf8KF4AYGwcxyMnsYEJF46fdJMa8EzheO80sYEZH4b3B0hOAG4Ww5vm5klOggVeEQ8uhshOhKXlYsa1srq2thr2rwc3NiNb2xROhh1HAd+N7O1HDw6ih+zR8YmHbhJAII+fnp1rGCTglPmLSxXTq0jAIuHWq6gGWhS4zlnuRhvPwO3PObq718gzYAiLXzymlWfg4VEQeNJLvC5f9ALwjJAvlufjiWQyEVehIIyTF8RLlhWwVDqTzWbSKTUKr2/IyOUaSL1//9R7Sk0LIe9H7g3i6e9cpeMqBOAzNzZ1iYwskEno5F8ptor5S3pIl8zKAtlkQYC8VuRnqgl8mWlakAUqXgFg6FPFEav8EwE+vCEVAhWfETgjentVIVB2kADcPHoZVtNC6VEGiAlefVbhs1IzCZnnSXDa44NWowoNBAWBsEHjpAC4vxOHje9W26gCuLFL4+5a06wEiF5ZJQGL+lEt1uVFISHQMkV1fnaa3zgBqpwoBIWT4yP2UFxt+3uR3cLCc+zQ2Gl7K7K5EVz3h8XlulKSWZaXKAwdWgwqbnl+gZgT5+dMmJQxyxFzYsCP4X0zxJQ07cXwaMpDimnuSRzvmiA24MTxaHyM1MAoj+NHSONEGJsODD9oI+bEATuG7+/jiDmxt0eZ7+4i8gywnUq4tYOlWWy2dgW8zWKmyomt1egWU3NTI13ogwZj+UWzvq62xqBXc2H9iwszHayx/gN+0eRQa7eHywAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOS0wNVQxMTowNzo0NyswMDowMGV+/EcAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDktMDVUMTE6MDc6NDcrMDA6MDAUI0T7AAAAAElFTkSuQmCC
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.istio.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarbrokers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarbrokers/finalizers
          verbs:
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarbrokers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarconnections
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarconnections/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarnamespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarnamespaces/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarpermissions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarpermissions/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarproxies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarproxies/finalizers
          verbs:
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsarproxies/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsartenants
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsartenants/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsartopics
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pulsar.streamnative.io
          resources:
          - pulsartopics/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - security.istio.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: pulsar-operator-controller-manager
      deployments:
      - label:
          app: pulsar-operator
          control-plane: controller-manager
        name: pulsar-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: pulsar-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                app: pulsar-operator
                control-plane: controller-manager
                service.istio.io/canonical-name: pulsar-operator
                service.istio.io/canonical-revision: 0.12.2
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: quay.io/streamnativeio/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/streamnativeio/pulsar-operator:v0.12.2
                name: manager
                resources:
                  limits:
                    cpu: "1"
                    memory: 1Gi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              serviceAccountName: pulsar-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: pulsar-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - pulsar
  - streamnative
  links:
  - name: Home Page
    url: https://streamnative.io
  - name: Documentation
    url: https://docs.streamnative.io/operators/pulsar-operator/tutorial/deploy-pulsar
  maintainers:
  - email: cloud@streamnative.io
    name: StreamNative Cloud
  maturity: alpha
  provider:
    name: StreamNative
    url: https://streamnative.io
  version: 0.12.2
