apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  creationTimestamp: null
  labels:
    self-node-remediation-operator: ""
  name: selfnoderemediationtemplates.self-node-remediation.medik8s.io
spec:
  group: self-node-remediation.medik8s.io
  names:
    kind: SelfNodeRemediationTemplate
    listKind: SelfNodeRemediationTemplateList
    plural: selfnoderemediationtemplates
    shortNames:
    - snrt
    - snremediationtemplate
    - snrtemplate
    singular: selfnoderemediationtemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SelfNodeRemediationTemplate is the Schema for the selfnoderemediationtemplates
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SelfNodeRemediationTemplateSpec defines the desired state
              of SelfNodeRemediationTemplate
            properties:
              template:
                description: Template defines the desired state of SelfNodeRemediationTemplate
                properties:
                  spec:
                    description: SelfNodeRemediationSpec defines the desired state
                      of SelfNodeRemediation
                    properties:
                      remediationStrategy:
                        default: Automatic
                        description: |-
                          RemediationStrategy is the remediation method for unhealthy nodes.
                          Currently, it could be either "Automatic", "OutOfServiceTaint" or "ResourceDeletion".
                          ResourceDeletion will iterate over all pods and VolumeAttachment related to the unhealthy node and delete them.
                          OutOfServiceTaint will add the out-of-service taint which is a new well-known taint "node.kubernetes.io/out-of-service"
                          that enables automatic deletion of pv-attached pods on failed nodes, "out-of-service" taint is only supported on clusters with k8s version 1.26+ or OCP/OKD version 4.13+.
                          Automatic will choose the most appropriate strategy during runtime.
                        enum:
                        - Automatic
                        - ResourceDeletion
                        - OutOfServiceTaint
                        type: string
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
          status:
            description: SelfNodeRemediationTemplateStatus defines the observed state
              of SelfNodeRemediationTemplate
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
