apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: dynatrace-extensions-controller
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 1.4.0
  name: dynatrace-extensions-controller
