apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  creationTimestamp: null
  name: queues.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: Queue
    listKind: QueueList
    plural: queues
    shortNames:
    - q
    singular: queue
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the Queue Config
      jsonPath: .status.state
      name: Status
      type: string
    - description: Name of the Hazelcast resource that this resource is created for
      jsonPath: .spec.hazelcastResourceName
      name: Hazelcast-Resource
      priority: 1
      type: string
    - description: Message for the current Queue Config
      jsonPath: .status.message
      name: Message
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Queue is the Schema for the queues API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: QueueSpec defines the desired state of Queue It cannot be
              updated after the Queue is created
            properties:
              asyncBackupCount:
                default: 0
                description: Number of asynchronous backups.
                format: int32
                maximum: 6
                minimum: 0
                type: integer
              backupCount:
                default: 1
                description: Number of synchronous backups.
                format: int32
                maximum: 6
                minimum: 0
                type: integer
              emptyQueueTTLSeconds:
                default: -1
                description: Time in seconds after which the Queue will be destroyed
                  if it stays empty or unused. If the values is not provided the Queue
                  will never be destroyed.
                format: int32
                type: integer
              hazelcastResourceName:
                description: HazelcastResourceName defines the name of the Hazelcast
                  resource that this resource is created for.
                minLength: 1
                type: string
              maxSize:
                default: 0
                description: Max size of the queue.
                format: int32
                minimum: 0
                type: integer
              name:
                description: Name of the data structure config to be created. If empty,
                  CR name will be used. It cannot be updated after the config is created
                  successfully.
                type: string
              priorityComparatorClassName:
                description: The name of the comparator class. If the class name is
                  provided, the Queue becomes Priority Queue. You can learn more at
                  https://docs.hazelcast.com/hazelcast/latest/data-structures/priority-queue.
                type: string
            required:
            - hazelcastResourceName
            type: object
          status:
            description: QueueStatus defines the observed state of Queue
            properties:
              memberStatuses:
                additionalProperties:
                  enum:
                  - Success
                  - Failed
                  - Pending
                  - Persisting
                  - Terminating
                  type: string
                description: Holds status of data structure for each Hazelcast member
                type: object
              message:
                description: Message explaining the current state
                type: string
              state:
                description: State of the data structure
                enum:
                - Success
                - Failed
                - Pending
                - Persisting
                - Terminating
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
