apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: mondooauditconfigs.k8s.mondoo.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: webhook-service
          namespace: mondoo-operator
          path: /convert
      conversionReviewVersions:
      - v1
  group: k8s.mondoo.com
  names:
    kind: MondooAuditConfig
    listKind: MondooAuditConfigList
    plural: mondooauditconfigs
    singular: mondooauditconfig
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: MondooAuditConfig is the Schema for the mondooauditconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MondooAuditConfigSpec defines the desired state of MondooAuditConfig
            properties:
              admission:
                properties:
                  certificateProvisioning:
                    description: CertificateProvisioning defines the certificate provisioning
                      configuration within the cluster.
                    properties:
                      mode:
                        default: manual
                        description: CertificateProvisioningMode is the specified
                          method the cluster uses for provisioning TLS certificates
                        enum:
                        - cert-manager
                        - openshift
                        - manual
                        type: string
                    type: object
                  enable:
                    type: boolean
                  image:
                    properties:
                      name:
                        type: string
                      tag:
                        type: string
                    type: object
                  mode:
                    default: permissive
                    description: Mode represents whether the webhook will behave in
                      a "permissive" mode (the default) which will only scan and report
                      on k8s resources or "enforcing" mode where depending on the
                      scan results may reject the k8s resource creation/modification.
                    enum:
                    - permissive
                    - enforcing
                    type: string
                  replicas:
                    default: 1
                    description: Number of replicas for the admission webhook. For
                      enforcing mode, the minimum should be two to prevent problems
                      during Pod failures, e.g. node failure, node scaling, etc.
                    format: int32
                    minimum: 1
                    type: integer
                type: object
              consoleIntegration:
                properties:
                  enable:
                    type: boolean
                type: object
              kubernetesResources:
                properties:
                  containerImageScanning:
                    description: ContainerImageScanning determines whether container
                      images are being scanned. The current implementation runs a
                      separate job once every 24h that scans the container images
                      running in the cluster.
                    type: boolean
                  enable:
                    type: boolean
                type: object
              mondooCredsSecretRef:
                description: Config is an example field of MondooAuditConfig. Edit
                  mondooauditconfig_types.go to remove/update
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              mondooTokenSecretRef:
                description: MondooTokenSecretRef can optionally hold a time-limited
                  token that the mondoo-operator will use to create a Mondoo service
                  account saved to the Secret specified in .spec.mondooCredsSecretRef
                  if that Secret does not exist.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              nodes:
                properties:
                  enable:
                    type: boolean
                  resources:
                    description: ResourceRequirements describes the compute resource
                      requirements.
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                type: object
              scanner:
                description: Scanner defines the settings for the Mondoo scanner that
                  will be running in the cluster. The same scanner is used for scanning
                  the Kubernetes API, the nodes and for serving the admission controller.
                properties:
                  image:
                    properties:
                      name:
                        type: string
                      tag:
                        type: string
                    type: object
                  replicas:
                    default: 1
                    description: Number of replicas for the scanner. For enforcing
                      mode, the minimum should be two to prevent problems during Pod
                      failures, e.g. node failure, node scaling, etc.
                    format: int32
                    minimum: 1
                    type: integer
                  resources:
                    description: ResourceRequirements describes the compute resource
                      requirements.
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                  serviceAccountName:
                    default: mondoo-operator-k8s-resources-scanning
                    type: string
                type: object
            required:
            - mondooCredsSecretRef
            type: object
          status:
            description: MondooAuditConfigStatus defines the observed state of MondooAuditConfig
            properties:
              conditions:
                description: Conditions includes detailed status for the MondooAuditConfig
                items:
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition
                        transitioned from one status to another.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: LastUpdateTime is the last time we probed the condition
                      format: date-time
                      type: string
                    message:
                      description: Message is a human-readable message indicating
                        details about the last transition
                      type: string
                    reason:
                      description: Reason is a unique, one-word, CamelCase reason
                        for the condition's last transition
                      type: string
                    status:
                      description: Status is the status of the condition
                      type: string
                    type:
                      description: Type is the specific type of the condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              pods:
                description: Pods store the name of the pods which are running mondoo
                  instances
                items:
                  type: string
                type: array
              reconciledByOperatorVersion:
                description: ReconciledByOperatorVersion contains the version of the
                  operator which reconciled this MondooAuditConfig
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
