apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.2
  creationTimestamp: null
  name: healthchecks.route53.services.k8s.aws
spec:
  group: route53.services.k8s.aws
  names:
    kind: HealthCheck
    listKind: HealthCheckList
    plural: healthchecks
    singular: healthcheck
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HealthCheck is the Schema for the HealthChecks API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              HealthCheckSpec defines the desired state of HealthCheck.

              A complex type that contains information about one health check that is associated
              with the current Amazon Web Services account.
            properties:
              healthCheckConfig:
                description: A complex type that contains settings for a new health
                  check.
                properties:
                  alarmIdentifier:
                    description: |-
                      A complex type that identifies the CloudWatch alarm that you want Amazon
                      Route 53 health checkers to use to determine whether the specified health
                      check is healthy.
                    properties:
                      name:
                        type: string
                      region:
                        type: string
                    type: object
                  childHealthChecks:
                    items:
                      type: string
                    type: array
                  disabled:
                    type: boolean
                  enableSNI:
                    type: boolean
                  failureThreshold:
                    format: int64
                    type: integer
                  fullyQualifiedDomainName:
                    type: string
                  healthThreshold:
                    format: int64
                    type: integer
                  insufficientDataHealthStatus:
                    type: string
                  inverted:
                    type: boolean
                  ipAddress:
                    type: string
                  measureLatency:
                    type: boolean
                  port:
                    format: int64
                    type: integer
                  regions:
                    items:
                      type: string
                    type: array
                  requestInterval:
                    format: int64
                    type: integer
                  resourcePath:
                    type: string
                  routingControlARN:
                    type: string
                  searchString:
                    type: string
                  type:
                    type: string
                type: object
              tags:
                description: |-
                  A complex type that contains a list of the tags that you want to add to the
                  specified health check or hosted zone and/or the tags that you want to edit
                  Value for.

                  You can add a maximum of 10 tags to a health check or a hosted zone.
                items:
                  description: |-
                    A complex type that contains information about a tag that you want to add
                    or edit for the specified health check or hosted zone.
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            required:
            - healthCheckConfig
            type: object
          status:
            description: HealthCheckStatus defines the observed state of HealthCheck
            properties:
              ackResourceMetadata:
                description: |-
                  All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
                  that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: |-
                      ARN is the Amazon Resource Name for the resource. This is a
                      globally-unique identifier and is set only by the ACK service controller
                      once the controller has orchestrated the creation of the resource OR
                      when it has verified that an "adopted" resource (a resource where the
                      ARN annotation was set by the Kubernetes user on the CR) exists and
                      matches the supplied CR's Spec field values.
                      https://github.com/aws/aws-controllers-k8s/issues/270
                    type: string
                  ownerAccountID:
                    description: |-
                      OwnerAccountID is the AWS Account ID of the account that owns the
                      backend AWS service API resource.
                    type: string
                  region:
                    description: Region is the AWS region in which the resource exists
                      or will exist.
                    type: string
                required:
                - ownerAccountID
                - region
                type: object
              callerReference:
                description: A unique string that you specified when you created the
                  health check.
                type: string
              cloudWatchAlarmConfiguration:
                description: |-
                  A complex type that contains information about the CloudWatch alarm that
                  Amazon Route 53 is monitoring for this health check.
                properties:
                  comparisonOperator:
                    type: string
                  dimensions:
                    items:
                      description: |-
                        For the metric that the CloudWatch alarm is associated with, a complex type
                        that contains information about one dimension.
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  evaluationPeriods:
                    format: int64
                    type: integer
                  metricName:
                    type: string
                  namespace:
                    type: string
                  period:
                    format: int64
                    type: integer
                  statistic:
                    type: string
                  threshold:
                    type: number
                type: object
              conditions:
                description: |-
                  All CRS managed by ACK have a common `Status.Conditions` member that
                  contains a collection of `ackv1alpha1.Condition` objects that describe
                  the various terminal states of the CR and its backend AWS service API
                  resource
                items:
                  description: |-
                    Condition is the common struct used by all CRDs managed by ACK service
                    controllers to indicate terminal states  of the CR and its backend AWS
                    service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              healthCheckVersion:
                description: |-
                  The version of the health check. You can optionally pass this value in a
                  call to UpdateHealthCheck to prevent overwriting another change to the health
                  check.
                format: int64
                type: integer
              id:
                description: |-
                  The identifier that Amazon Route 53 assigned to the health check when you
                  created it. When you add or update a resource record set, you use this value
                  to specify which health check to use. The value can be up to 64 characters
                  long.
                type: string
              linkedService:
                description: |-
                  If the health check was created by another service, the service that created
                  the health check. When a health check is created by another service, you
                  can't edit or delete it using Amazon Route 53.
                properties:
                  description:
                    type: string
                  servicePrincipal:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
