apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: dynatrace-extensions-controller
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 1.5.1
  name: dynatrace-extensions-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-extensions-controller
subjects:
- kind: ServiceAccount
  name: dynatrace-extensions-controller
