apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  creationTimestamp: null
  name: mounttargets.efs.services.k8s.aws
spec:
  group: efs.services.k8s.aws
  names:
    kind: MountTarget
    listKind: MountTargetList
    plural: mounttargets
    singular: mounttarget
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.fileSystemID
      name: FILESYSTEMID
      type: string
    - jsonPath: .spec.ipAddress
      name: IPADDRESS
      type: string
    - jsonPath: .status.mountTargetID
      name: MOUNTTARGETID
      type: string
    - jsonPath: .spec.subnetID
      name: SUBNETID
      type: string
    - jsonPath: .status.vpcID
      name: VPCID
      priority: 1
      type: string
    - jsonPath: .status.availabilityZoneID
      name: AVAILABILITYZONEID
      priority: 1
      type: string
    - jsonPath: .status.availabilityZoneName
      name: AVAILABILITYZONENAME
      priority: 1
      type: string
    - jsonPath: .status.lifeCycleState
      name: STATE
      type: string
    - jsonPath: .status.conditions[?(@.type=="ACK.ResourceSynced")].status
      name: Synced
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MountTarget is the Schema for the MountTargets API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MountTargetSpec defines the desired state of MountTarget.
            properties:
              fileSystemID:
                description: The ID of the file system for which to create the mount
                  target.
                type: string
              fileSystemRef:
                description: "AWSResourceReferenceWrapper provides a wrapper around
                  *AWSResourceReference\ntype to provide more user friendly syntax
                  for references using 'from' field\nEx:\nAPIIDRef:\n\n\n\tfrom:\n\t
                  \ name: my-api"
                properties:
                  from:
                    description: |-
                      AWSResourceReference provides all the values necessary to reference another
                      k8s resource for finding the identifier(Id/ARN/Name)
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                type: object
              ipAddress:
                description: Valid IPv4 address within the address range of the specified
                  subnet.
                type: string
              securityGroupRefs:
                items:
                  description: "AWSResourceReferenceWrapper provides a wrapper around
                    *AWSResourceReference\ntype to provide more user friendly syntax
                    for references using 'from' field\nEx:\nAPIIDRef:\n\n\n\tfrom:\n\t
                    \ name: my-api"
                  properties:
                    from:
                      description: |-
                        AWSResourceReference provides all the values necessary to reference another
                        k8s resource for finding the identifier(Id/ARN/Name)
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                      type: object
                  type: object
                type: array
              securityGroups:
                description: |-
                  Up to five VPC security group IDs, of the form sg-xxxxxxxx. These must be
                  for the same VPC as subnet specified.
                items:
                  type: string
                type: array
              subnetID:
                description: |-
                  The ID of the subnet to add the mount target in. For One Zone file systems,
                  use the subnet that is associated with the file system's Availability Zone.
                type: string
              subnetRef:
                description: "AWSResourceReferenceWrapper provides a wrapper around
                  *AWSResourceReference\ntype to provide more user friendly syntax
                  for references using 'from' field\nEx:\nAPIIDRef:\n\n\n\tfrom:\n\t
                  \ name: my-api"
                properties:
                  from:
                    description: |-
                      AWSResourceReference provides all the values necessary to reference another
                      k8s resource for finding the identifier(Id/ARN/Name)
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: MountTargetStatus defines the observed state of MountTarget
            properties:
              ackResourceMetadata:
                description: |-
                  All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
                  that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: |-
                      ARN is the Amazon Resource Name for the resource. This is a
                      globally-unique identifier and is set only by the ACK service controller
                      once the controller has orchestrated the creation of the resource OR
                      when it has verified that an "adopted" resource (a resource where the
                      ARN annotation was set by the Kubernetes user on the CR) exists and
                      matches the supplied CR's Spec field values.
                      TODO(vijat@): Find a better strategy for resources that do not have ARN in CreateOutputResponse
                      https://github.com/aws/aws-controllers-k8s/issues/270
                    type: string
                  ownerAccountID:
                    description: |-
                      OwnerAccountID is the AWS Account ID of the account that owns the
                      backend AWS service API resource.
                    type: string
                  region:
                    description: Region is the AWS region in which the resource exists
                      or will exist.
                    type: string
                required:
                - ownerAccountID
                - region
                type: object
              availabilityZoneID:
                description: |-
                  The unique and consistent identifier of the Availability Zone that the mount
                  target resides in. For example, use1-az1 is an AZ ID for the us-east-1 Region
                  and it has the same location in every Amazon Web Services account.
                type: string
              availabilityZoneName:
                description: |-
                  The name of the Availability Zone in which the mount target is located. Availability
                  Zones are independently mapped to names for each Amazon Web Services account.
                  For example, the Availability Zone us-east-1a for your Amazon Web Services
                  account might not be the same location as us-east-1a for another Amazon Web
                  Services account.
                type: string
              conditions:
                description: |-
                  All CRS managed by ACK have a common `Status.Conditions` member that
                  contains a collection of `ackv1alpha1.Condition` objects that describe
                  the various terminal states of the CR and its backend AWS service API
                  resource
                items:
                  description: |-
                    Condition is the common struct used by all CRDs managed by ACK service
                    controllers to indicate terminal states  of the CR and its backend AWS
                    service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              lifeCycleState:
                description: Lifecycle state of the mount target.
                type: string
              mountTargetID:
                description: System-assigned mount target ID.
                type: string
              networkInterfaceID:
                description: |-
                  The ID of the network interface that Amazon EFS created when it created the
                  mount target.
                type: string
              ownerID:
                description: Amazon Web Services account ID that owns the resource.
                type: string
              vpcID:
                description: The virtual private cloud (VPC) ID that the mount target
                  is configured in.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
