apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  creationTimestamp: null
  name: sonarqualityprofiles.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: SonarQualityProfile
    listKind: SonarQualityProfileList
    plural: sonarqualityprofiles
    singular: sonarqualityprofile
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SonarQualityProfile is the Schema for the sonarqualityprofiles
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SonarQualityProfileSpec defines the desired state of SonarQualityProfile
            properties:
              default:
                description: |-
                  Default is a flag to set quality profile as default.
                  Only one quality profile can be default.
                  If several quality profiles have default flag, the random one will be chosen.
                  Default quality profile can't be deleted. You need to set another quality profile as default before.
                example: "true"
                type: boolean
              language:
                description: Language is a language of quality profile.
                example: go
                type: string
              name:
                description: |-
                  Name is a name of quality profile.
                  Name should be unique across all quality profiles.
                  Don't change this field after creation otherwise quality profile will be recreated.
                example: My Quality Profile
                maxLength: 100
                type: string
              rules:
                additionalProperties:
                  description: Rule defines a rule of quality profile.
                  properties:
                    params:
                      description: Params is as semicolon list of key=value.
                      example: key1=v1;key2=v2
                      type: string
                    severity:
                      description: Severity is a severity of rule.
                      enum:
                      - INFO
                      - MINOR
                      - MAJOR
                      - CRITICAL
                      - BLOCKER
                      example: MAJOR
                      type: string
                  type: object
                description: |-
                  Rules is a list of rules for quality profile.
                  Key is a rule key, value is a rule.
                example:
                  S5547:
                    params: key1=v1;key2=v2
                    severity: MAJOR
                nullable: true
                type: object
              sonarRef:
                description: SonarRef is a reference to Sonar custom resource.
                properties:
                  kind:
                    default: Sonar
                    description: Kind specifies the kind of the Sonar resource.
                    type: string
                  name:
                    description: Name specifies the name of the Sonar resource.
                    type: string
                required:
                - name
                type: object
            required:
            - language
            - name
            - sonarRef
            type: object
          status:
            description: SonarQualityProfileStatus defines the observed state of SonarQualityProfile
            properties:
              error:
                description: Error is an error message if something went wrong.
                type: string
              value:
                description: Value is a status of the quality profile.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
