apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  creationTimestamp: null
  name: sonargroups.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: SonarGroup
    listKind: SonarGroupList
    plural: sonargroups
    singular: sonargroup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SonarGroup is the Schema for the sonar group API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SonarGroupSpec defines the desired state of SonarGroup.
            properties:
              description:
                description: Description of sonar group.
                example: Default group for new users
                maxLength: 200
                type: string
              name:
                description: |-
                  Name is a group name.
                  Name should be unique across all groups.
                  Do not edit this field after creation. Otherwise, the group will be recreated.
                example: sonar-users
                maxLength: 255
                type: string
              permissions:
                description: Permissions is a list of permissions assigned to group.
                example:
                - admin
                - provisioning
                items:
                  type: string
                nullable: true
                type: array
              sonarRef:
                description: SonarRef is a reference to Sonar custom resource.
                properties:
                  kind:
                    default: Sonar
                    description: Kind specifies the kind of the Sonar resource.
                    type: string
                  name:
                    description: Name specifies the name of the Sonar resource.
                    type: string
                required:
                - name
                type: object
            required:
            - name
            - sonarRef
            type: object
          status:
            description: SonarGroupStatus defines the observed state of SonarGroup.
            properties:
              error:
                description: Error is an error message if something went wrong.
                type: string
              value:
                description: Value is a status of the group.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
