apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: oracle-database-operator-system/oracle-database-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.18.0
  creationTimestamp: null
  name: lrpdbs.database.oracle.com
spec:
  group: database.oracle.com
  names:
    kind: LRPDB
    listKind: LRPDBList
    plural: lrpdbs
    singular: lrpdb
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the CDB
      jsonPath: .spec.cdbName
      name: CDB Name
      type: string
    - description: Name of the PDB
      jsonPath: .spec.pdbName
      name: PDB Name
      type: string
    - description: PDB Open Mode
      jsonPath: .status.openMode
      name: PDB State
      type: string
    - description: Total Size of the PDB
      jsonPath: .status.totalSize
      name: PDB Size
      type: string
    - description: Error message, if any
      jsonPath: .status.msg
      name: Message
      type: string
    - description: open restricted
      jsonPath: .status.restricted
      name: Restricted
      type: string
    - description: last sqlcode
      jsonPath: .status.sqlCode
      name: last sqlcode
      type: integer
    - description: last plsql applied
      jsonPath: .status.lastplsql
      name: last PLSQL
      type: string
    - description: Bitmask status
      jsonPath: .status.pdbBitMaskStr
      name: BITMASK STATUS
      type: string
    - description: The connect string to be used
      jsonPath: .status.connString
      name: Connect_String
      type: string
    name: v4
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              action:
                type: string
              adminName:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              adminPwd:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              adminpdbPass:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              adminpdbUser:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              alterSystem:
                type: string
              alterSystemParameter:
                type: string
              alterSystemValue:
                type: string
              asClone:
                type: boolean
              cdbName:
                type: string
              cdbNamespace:
                type: string
              cdbPrvKey:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbResName:
                type: string
              codeconfigmap:
                type: string
              copyAction:
                enum:
                - COPY
                - NOCOPY
                - MOVE
                type: string
              dropAction:
                enum:
                - INCLUDING
                - KEEP
                type: string
              fileNameConversions:
                type: string
              getScript:
                default: false
                type: boolean
              imperativeLrpdbDeletion:
                type: boolean
              lrpdbTlsCat:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              lrpdbTlsCrt:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              lrpdbTlsKey:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              modifyOption:
                enum:
                - IMMEDIATE
                - NORMAL
                - READ ONLY
                - READ WRITE
                - RESTRICTED
                type: string
              modifyOption2:
                default: NONE
                type: string
              parameterScope:
                type: string
              passwordProtection:
                default: NATIVE
                enum:
                - NATIVE
                - OPENSSL3
                type: string
              pdbName:
                type: string
              pdbState:
                enum:
                - OPEN
                - CLOSE
                - ALTER
                - DELETE
                - UNPLUG
                - PLUG
                - CLONE
                - RESET
                - NONE
                type: string
              pdbconfigmap:
                type: string
              plsqlexemode:
                type: integer
              reststate:
                type: integer
              reuseTempFile:
                default: true
                type: boolean
              sourceFileNameConversions:
                type: string
              sparseClonePath:
                type: string
              srcPdbName:
                type: string
              tdeExport:
                type: boolean
              tdeImport:
                type: boolean
              tdeKeystorePath:
                type: string
              tdePassword:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              tdeSecret:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              tempSize:
                type: string
              totalSize:
                type: string
              tracelevel:
                type: integer
              unlimitedStorage:
                default: true
                type: boolean
              webServerPwd:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              webServerUser:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              xmlFileName:
                type: string
            required:
            - imperativeLrpdbDeletion
            - passwordProtection
            type: object
          status:
            properties:
              action:
                type: string
              alterSystem:
                type: string
              bitstat:
                type: integer
              bitstatstr:
                type: string
              connString:
                type: string
              lastplsql:
                type: string
              modifyOption:
                type: string
              msg:
                type: string
              openMode:
                type: string
              pdbBitMask:
                type: integer
              pdbBitMaskStr:
                type: string
              phase:
                type: string
              restricted:
                type: string
              sqlCode:
                type: integer
              status:
                type: boolean
              totalSize:
                type: string
            required:
            - phase
            - sqlCode
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
