apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: oracle-database-operator-system/oracle-database-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.18.0
  creationTimestamp: null
  name: lrests.database.oracle.com
spec:
  group: database.oracle.com
  names:
    kind: LREST
    listKind: LRESTList
    plural: lrests
    singular: lrest
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the LREST
      jsonPath: .spec.cdbName
      name: CDB NAME
      type: string
    - description: Status of the LREST Resource
      jsonPath: .status.phase
      name: STATUS
      type: string
    - description: Error message if any
      jsonPath: .status.msg
      name: MESSAGE
      type: string
    - description: Autodiscover
      jsonPath: .spec.autodiscover
      name: AUTODISCOVER
      type: boolean
    - description: Number of PDBS
      jsonPath: .status.npdbscrd
      name: PDB:CRD
      type: string
    - description: string of the tnsalias
      jsonPath: .spec.dbTnsurl
      name: TNS STRING
      type: string
    name: v4
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              autodiscover:
                type: boolean
              cdbAdminPwd:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbAdminUser:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbName:
                type: string
              cdbPrvKey:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbPubKey:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbTlsCat:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbTlsCrt:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              cdbTlsKey:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              clusterIp:
                default: false
                type: boolean
              dbPort:
                type: integer
              dbServer:
                type: string
              dbTnsurl:
                type: string
              deletePdbCascade:
                type: boolean
              loadBalancer:
                default: false
                type: boolean
              lrestImage:
                type: string
              lrestImagePullPolicy:
                enum:
                - Always
                - Never
                type: string
              lrestImagePullSecret:
                type: string
              lrestPort:
                default: 8888
                type: integer
              lrestPwd:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              namespaceAutoDiscover:
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                type: object
              orapki:
                properties:
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              orapkitag:
                default: orapkitag
                type: string
              passwordProtection:
                default: NATIVE
                enum:
                - NATIVE
                - OPENSSL3
                - ORAPKI
                type: string
              replicas:
                type: integer
              resetDbpassword:
                type: boolean
              serviceAccountName:
                type: string
              serviceName:
                type: string
              sysAdminPwd:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              trace_level_client:
                default: 0
                type: integer
              tracelevel:
                type: integer
              webServerPwd:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
              webServerUser:
                properties:
                  secret:
                    properties:
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - key
                    - secretName
                    type: object
                required:
                - secret
                type: object
            required:
            - passwordProtection
            type: object
          status:
            properties:
              msg:
                type: string
              ncrds:
                type: integer
              npdbs:
                type: integer
              npdbscrd:
                type: string
              phase:
                type: string
              status:
                type: boolean
            required:
            - phase
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
