apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: oracle-database-operator-system/oracle-database-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.18.0
  creationTimestamp: null
  name: oraclerestdataservices.database.oracle.com
spec:
  group: database.oracle.com
  names:
    kind: OracleRestDataService
    listKind: OracleRestDataServiceList
    plural: oraclerestdataservices
    shortNames:
    - ords
    singular: oraclerestdataservice
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .spec.databaseRef
      name: Database
      type: string
    - jsonPath: .status.databaseApiUrl
      name: Database API URL
      type: string
    - jsonPath: .status.databaseActionsUrl
      name: Database Actions URL
      type: string
    - jsonPath: .status.apexUrl
      name: Apex URL
      type: string
    - jsonPath: .status.mongoDbApiAccessUrl
      name: MongoDbApi Access URL
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminPassword:
                properties:
                  keepSecret:
                    type: boolean
                  secretKey:
                    default: oracle_pwd
                    type: string
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              databaseRef:
                type: string
              image:
                properties:
                  pullFrom:
                    type: string
                  pullSecrets:
                    type: string
                  version:
                    type: string
                required:
                - pullFrom
                type: object
              loadBalancer:
                type: boolean
              mongoDbApi:
                type: boolean
              nodeSelector:
                additionalProperties:
                  type: string
                type: object
              oracleService:
                type: string
              ordsPassword:
                properties:
                  keepSecret:
                    type: boolean
                  secretKey:
                    default: oracle_pwd
                    type: string
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              ordsUser:
                type: string
              persistence:
                properties:
                  accessMode:
                    enum:
                    - ReadWriteOnce
                    - ReadWriteMany
                    type: string
                  setWritePermissions:
                    type: boolean
                  size:
                    type: string
                  storageClass:
                    type: string
                  volumeName:
                    type: string
                type: object
              readinessCheckPeriod:
                type: integer
              replicas:
                minimum: 1
                type: integer
              restEnableSchemas:
                items:
                  properties:
                    enable:
                      type: boolean
                    pdbName:
                      type: string
                    schemaName:
                      type: string
                    urlMapping:
                      type: string
                  required:
                  - enable
                  - schemaName
                  type: object
                type: array
              serviceAccountName:
                type: string
              serviceAnnotations:
                additionalProperties:
                  type: string
                type: object
            required:
            - adminPassword
            - databaseRef
            - ordsPassword
            type: object
          status:
            properties:
              apexConfigured:
                type: boolean
              apexUrl:
                type: string
              commonUsersCreated:
                type: boolean
              databaseActionsUrl:
                type: string
              databaseApiUrl:
                type: string
              databaseRef:
                type: string
              image:
                properties:
                  pullFrom:
                    type: string
                  pullSecrets:
                    type: string
                  version:
                    type: string
                required:
                - pullFrom
                type: object
              loadBalancer:
                type: string
              mongoDbApi:
                type: boolean
              mongoDbApiAccessUrl:
                type: string
              ordsInstalled:
                type: boolean
              replicas:
                type: integer
              serviceIP:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .spec.databaseRef
      name: Database
      type: string
    - jsonPath: .status.databaseApiUrl
      name: Database API URL
      type: string
    - jsonPath: .status.databaseActionsUrl
      name: Database Actions URL
      type: string
    - jsonPath: .status.apexUrl
      name: Apex URL
      type: string
    - jsonPath: .status.mongoDbApiAccessUrl
      name: MongoDbApi Access URL
      type: string
    name: v4
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminPassword:
                properties:
                  keepSecret:
                    type: boolean
                  secretKey:
                    default: oracle_pwd
                    type: string
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              databaseRef:
                type: string
              image:
                properties:
                  pullFrom:
                    type: string
                  pullSecrets:
                    type: string
                  version:
                    type: string
                required:
                - pullFrom
                type: object
              loadBalancer:
                type: boolean
              mongoDbApi:
                type: boolean
              nodeSelector:
                additionalProperties:
                  type: string
                type: object
              oracleService:
                type: string
              ordsPassword:
                properties:
                  keepSecret:
                    type: boolean
                  secretKey:
                    default: oracle_pwd
                    type: string
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              ordsUser:
                type: string
              persistence:
                properties:
                  accessMode:
                    enum:
                    - ReadWriteOnce
                    - ReadWriteMany
                    type: string
                  setWritePermissions:
                    type: boolean
                  size:
                    type: string
                  storageClass:
                    type: string
                  volumeName:
                    type: string
                type: object
              readinessCheckPeriod:
                type: integer
              replicas:
                minimum: 1
                type: integer
              restEnableSchemas:
                items:
                  properties:
                    enable:
                      type: boolean
                    pdbName:
                      type: string
                    schemaName:
                      type: string
                    urlMapping:
                      type: string
                  required:
                  - enable
                  - schemaName
                  type: object
                type: array
              serviceAccountName:
                type: string
              serviceAnnotations:
                additionalProperties:
                  type: string
                type: object
            required:
            - adminPassword
            - databaseRef
            - ordsPassword
            type: object
          status:
            properties:
              apexConfigured:
                type: boolean
              apexUrl:
                type: string
              commonUsersCreated:
                type: boolean
              databaseActionsUrl:
                type: string
              databaseApiUrl:
                type: string
              databaseRef:
                type: string
              image:
                properties:
                  pullFrom:
                    type: string
                  pullSecrets:
                    type: string
                  version:
                    type: string
                required:
                - pullFrom
                type: object
              loadBalancer:
                type: string
              mongoDbApi:
                type: boolean
              mongoDbApiAccessUrl:
                type: string
              ordsInstalled:
                type: boolean
              replicas:
                type: integer
              serviceIP:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
