apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-database-operator
  name: oracle-database-operator-privateai-privateai-viewer-role
rules:
- apiGroups:
  - privateai.oracle.com
  resources:
  - privateais
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - privateai.oracle.com
  resources:
  - privateais/status
  verbs:
  - get
