apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  creationTimestamp: null
  name: sonarusers.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: SonarUser
    listKind: SonarUserList
    plural: sonarusers
    singular: sonaruser
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SonarUser is the Schema for the sonarusers API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SonarUserSpec defines the desired state of SonarUser
            properties:
              email:
                description: Email is a user email.
                example: myname@email.com
                maxLength: 100
                type: string
              groups:
                description: Groups is a list of groups assigned to user.
                example:
                - sonar-administrators
                - developers
                items:
                  type: string
                nullable: true
                type: array
              login:
                description: |-
                  Login is a user login.
                  Do not edit this field after creation. Otherwise, the user will be recreated.
                example: myuser
                maxLength: 255
                minLength: 2
                type: string
              name:
                description: Name is a username.
                example: My Name
                maxLength: 200
                type: string
              permissions:
                description: Permissions is a list of permissions assigned to user.
                example:
                - admin
                - provisioning
                items:
                  type: string
                nullable: true
                type: array
              secret:
                description: |-
                  Secret is the name of the secret with the user password.
                  It should contain a password field with a user password.
                  User password can't be updated.
                example: sonar-user-password
                type: string
              sonarRef:
                description: SonarRef is a reference to Sonar custom resource.
                properties:
                  kind:
                    default: Sonar
                    description: Kind specifies the kind of the Sonar resource.
                    type: string
                  name:
                    description: Name specifies the name of the Sonar resource.
                    type: string
                required:
                - name
                type: object
            required:
            - login
            - name
            - secret
            - sonarRef
            type: object
          status:
            description: SonarUserStatus defines the observed state of SonarUser
            properties:
              error:
                description: Error is an error message if something went wrong.
                type: string
              value:
                description: Value is a status of the user.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
