apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: layer7-operator-system/layer7-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.16.5
  creationTimestamp: null
  name: l7apis.security.brcmlabs.com
spec:
  group: security.brcmlabs.com
  names:
    kind: L7Api
    listKind: L7ApiList
    plural: l7apis
    shortNames:
    - api
    - apis
    singular: l7api
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: L7Api is the Schema for the l7apis API
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represent
            type: string
          metadata:
            type: object
          spec:
            description: L7ApiSpec defines the desired state of L7Api
            properties:
              deploymentTags:
                description: DeploymentTags target Gateway deployments that this API
                  should be published
                items:
                  type: string
                type: array
              graphmanBundle:
                description: |-
                  GraphmanBundle associated with this API
                  currently limited to Service and Fr
                type: string
              l7Portal:
                description: L7Portal is the L7Portal that this API is associated
                  with when Portal Publi
                type: string
              portalMeta:
                description: PortalMeta is reserved for the API Developer Portal
                properties:
                  apiId:
                    type: string
                  apiUuid:
                    type: string
                  checksum:
                    type: string
                  createTs:
                    type: integer
                  customFieldValues:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  enabled:
                    type: boolean
                  locationUrl:
                    type: string
                  modifyTs:
                    type: integer
                  name:
                    type: string
                  policyEntities:
                    items:
                      properties:
                        policyEntityUuid:
                          type: string
                        policyTemplateArguments:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            required:
                            - name
                            - value
                            type: object
                          type: array
                      required:
                      - policyEntityUuid
                      - policyTemplateArguments
                      type: object
                    type: array
                  publishedTs:
                    type: integer
                  serviceId:
                    type: string
                  ssgServiceType:
                    type: string
                  ssgUrl:
                    type: string
                  ssgUrlEncoded:
                    type: string
                  tenantId:
                    type: string
                type: object
              portalPublished:
                description: PortalPublished
                type: boolean
              serviceUrl:
                description: ServiceUrl on the API Gateway
                type: string
            type: object
          status:
            description: L7ApiStatus defines the observed state of L7Api
            properties:
              checksum:
                type: string
              gateways:
                items:
                  properties:
                    checksum:
                      type: string
                    deployment:
                      description: Phase       corev1.
                      type: string
                    lastUpdated:
                      description: Ready       bool            `json:"ready,omitempty"`
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              ready:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
