apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: windup-operator.v0.0.25
  namespace: placeholder
  annotations:
    capabilities: Basic Install
    description: Windup is an analysis tool that supports the modernization and migration of Java applications.
    categories: Modernization & Migration
    certified: "false"
    support: https://issues.redhat.com/projects/WINDUP
    repository: https://github.com/windup/windup-operator/
    containerImage: quay.io/windupeng/windup-operator-native:0.0.25
    imagePullPolicy: Always
    createdAt: 01/22/24
    alm-examples: |-
      [
       {
         "apiVersion": "windup.jboss.org/v1",
         "kind": "Windup",
         "metadata": {
           "name": "windup",
           "labels": {
             "application": "windup"
           }
         },
         "spec": {}
       }
      ]
    operatorframework.io/suggested-namespace: windup
spec:
  customresourcedefinitions:
    owned:
      - name: windups.windup.jboss.org
        version: v1
        kind: Windup
        displayName: Windup
        description: >
          Create a Windup Web Console application.  


          To access the Windup Web Console application from the "Developer" perspective, please go to Topology and click on the "Open URL" icon on the web-console pod.  


          Alternatively from the "Administrator" perspective, please go to Networking->Routes and click on the Location hyperlink.  


          Known issue  

          If you want to customize the Windup Web Console instance's parameters and you can not see any in the `Form view`, please switch to the `YAML view` and change them as needed.
  description: >
    Windup is a web console application that supports large-scale Java application modernization and migration projects across a broad range of transformations and use cases.
    
    
    It analyzes application code, supports effort estimation, accelerates code migration, and enables users to move applications to containers.
    
    
    For more information please refer to the [https://windup.github.io/](https://windup.github.io/) page.

  displayName: Windup Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxNi4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB3aWR0aD0iMjU2cHgiIGhlaWdodD0iMjM4LjYxNnB4IiB2aWV3Qm94PSIwIDAgMjU2IDIzOC42MTYiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDI1NiAyMzguNjE2IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxnPg0KCTxwYXRoIGZpbGw9IiNGRkZGRkYiIGQ9Ik0yMDIuNjUxLDIyMC41NjdjLTE2Ljk4OS0yMS4wNTQtMjMuMTQ1LTM0LjM2My0yNi42MzUtNDIuMTcyYy0yLjI2Ni01LjA3LTMuMzExLTguNDMyLTMuNzg2LTEwLjQwNA0KCQljNC45NTktMy4zMzYsOS40MDMtNy4xNzEsMTMuMjE2LTExLjQxMmMyMS4yMzUtMjMuNjA4LDIyLjg4NS02Mi44NTEsMjIuMzgyLTc2LjI3M0wyNTYsNTguMjVsLTQzLjYwMS0xMy43MzYNCgkJYy0xLjk5NC0xLjM3OC0zLjk1My0zLjYtNi4yMDYtNi4xMzhjLTYuMjI3LTcuMDEyLTE0Ljc0NS0xNi42MjctMzIuNDUyLTE2LjYyN2MtNy43MDQsMC0xNi4zNjEsMS43NjUtMjYuNDM0LDUuNDAyDQoJCWMtMTguNTczLDYuNzEtMjQuMzA5LDE3LjMzNy0zNC43MzcsMzYuNjE3Yy04LjU2NCwxNS44NTYtMjEuNTE1LDM5LjgxOC00OC44NzIsNzUuMTE1TDMuNTcsMjAwLjM1MmMwLDAsMzEuMjYsMjguMzQsODUuMTYxLDI4LjM0DQoJCWMxOC41NzksMCwyOS4wNDgtMy43NzgsMjkuMDQ4LTMuNzc4bDEwLjY3OS00My41ODZjMC44MzgtMC4wMTEsMS42ODEtMC4wMjksMi41MDktMC4wNjdjMS4wMjcsOC43NjcsNC43NjMsMjUuNTY0LDE3Ljc2NCw0OS4zMTkNCgkJYy0xLjUsMC41ODgtMy4zNiwxLjU2NC01LjQ0MSwzLjI1MWMtMy44MzQsMy4wOTEsMy44NzEsMC42ODYsOC43NzYtMC4zNjFjNS4zMTQsMC41NzUsMjQuMDQsOS4yMTQsMTcuNDIsMi43NzENCgkJYy0xLjMwMy0xLjI1NS0yLjUzOC0yLjI0NS0zLjcyMS0zLjExNWM2LjM5OSwyLjE3MywxMi42MzMsNC4yNjgsOC4zNzMsMC4xMjhjLTUuNTc5LTUuNDI2LTEwLjM4OC02Ljk0My0xMi4yMTMtNy4zNDcNCgkJYy0xNS40MjgtMjQuMjczLTE4LjY2MS0zOS4wNDEtMTkuMTQzLTQ1Ljk3MWM2LjQ4OS0xLjIwOCwxMi42NjctMy4xNjksMTguMzktNS43OGMyLjc4MSw4Ljg0Miw4LjcwOSwyMi42MTQsMjguMDI4LDQ5LjkzNQ0KCQljLTEuNjE4LDAuNDE5LTQuMTY2LDEuNDExLTcuMTI4LDMuODA1Yy0zLjgzOSwzLjEwNCwzLjg4MSwwLjY5Nyw4Ljc4OS0wLjM0N2M1LjMyNywwLjU3NywyNC4wMiw5LjIwMywxNy40MDcsMi43NzENCgkJYy0xLjI5NS0xLjI2LTIuNTMzLTIuMjUtMy43MjQtMy4xMThjNi40MDIsMi4xNzYsMTIuNjM1LDQuMjYxLDguMzc0LDAuMTI5QzIwOC43NjMsMjIzLjI4NCwyMDUuMDQ2LDIyMS40MjgsMjAyLjY1MSwyMjAuNTY3eiIvPg0KCTxnPg0KCQk8cGF0aCBmaWxsPSIjMEIxRjJDIiBkPSJNMTYyLjI0NSw1My45NDhjMCw1LjQzNSw0LjQwNyw5Ljg0Niw5Ljg0Myw5Ljg0NmM1LjQzNCwwLDkuODQtNC40MTEsOS44NC05Ljg0Ng0KCQkJYzAtNS40NDItNC40MDYtOS44NDYtOS44NC05Ljg0NkMxNjYuNjUyLDQ0LjEwMiwxNjIuMjQ1LDQ4LjUwNiwxNjIuMjQ1LDUzLjk0OHoiLz4NCgkJPHBhdGggZmlsbD0iI0ZGRkZGRiIgZD0iTTE3NC40ODQsNDcuNjk1YzAuNTgsMCwxLjE1NywwLjA2MywxLjcxMywwLjE2Yy0xLjI1MS0wLjk3Mi0yLjgyLTEuNTU4LTQuNTI2LTEuNTU4DQoJCQljLTQuMDc2LDAtNy4zODgsMy4zMDMtNy4zODgsNy4zNzRjMCwxLjA3NSwwLjIzNywyLjA5MiwwLjY1OCwzLjAxNEMxNjUuMjM2LDUxLjY3NCwxNjkuMzksNDcuNjk1LDE3NC40ODQsNDcuNjk1eiIvPg0KCQk8cGF0aCBmaWxsPSIjRDkyNzJFIiBkPSJNMTA4Ljk3MSw4OC4wMDhsLTExLjM1OC02LjM3NWwxLjI4Ny0yLjA0OWMwLTAuMDA0LDAuMTI4LTAuMTk5LDAuMzA5LTAuNTINCgkJCWMzLjM2OC02LjAwOSwwLjc5OS04LjMwMi0wLjQ1Ny05LjAwOWMtMTEuOTczLTYuNzE3LTE3LjI4NS0yMC45NDMtMTIuNjM1LTMzLjgyMmwwLjM0MS0wLjk0DQoJCQljNS42ODgtMTEuNjgxLDEuMjgyLTI1LjgwNC0xMC4wMzktMzIuMTUzYy0xMS44MTEtNi42MjgtMjYuODE3LTIuNDE2LTMzLjQ0OSw5LjM5NGMtMi4xMTksMy43OC0zLjIsOC4wNjMtMy4xMTgsMTIuMzg1DQoJCQljMC4wNzMsNC4xNDYsMS4yLDguMjM2LDMuMjYsMTEuODVsMC4wMDcsMC4wNDRjMC4wMDYsMC4wMzIsMC4wMzEsMC4xOTksMC4zNjEsMC42NDNjMC45MTQsMS4yNSwxLjAxNiwyLjkyNCwwLjI2Miw0LjI3Ng0KCQkJYy0wLjQ4NywwLjg2NS0xLjI5NCwxLjUwOC0yLjI3OSwxLjgxYy0wLjA3OCwwLjAyLTAuMTU0LDAuMDQ2LTAuMjMyLDAuMDU4Yy0wLjE3MiwwLjAzOS0wLjM1NCwwLjA4My0wLjUxNiwwLjEyOQ0KCQkJYy0wLjU3MywwLjA5Ni0wLjgxMSwwLjI0NC0wLjg4OCwwLjI5NWMtNC4xMDIsMS40MTctNy41MjEsNC4yNTgtOS42MjEsOC4wMTJjLTIuMTAxLDMuNzM0LTIuNzQ0LDguMTEzLTEuODM1LDEyLjMzMg0KCQkJYy0wLjAyLDAuMDUxLTAuMDk4LDAuMzYxLDAuMjM3LDEuMTE0YzAuNTAyLDEuMTQ3LDAuNDM5LDIuNDI4LTAuMTc5LDMuNTE2Yy0wLjY3LDEuMjExLTEuOTM5LDEuOTU4LTMuMzc1LDEuOTgzDQoJCQljLTAuMTE0LDAtMC4yMzcsMC0wLjM2LDBjLTAuMDk3LDAuMDA3LTAuMTk1LDAuMDEyLTAuMjkxLDAuMDEyYy0wLjItMC4wMTItMC4zMTYsMC0wLjM1NCwwLjAxNA0KCQkJYy00LjIxMywwLjA5LTguMzMzLDEuMjYyLTExLjk1MiwzLjM3NWMtMy43MzUsMi4xODgtNi44MjgsNS4zNDQtOC45NTIsOS4xMjVsMCwwYy0zLjIwNyw1LjcxMS0zLjk5NCwxMi4zNDUtMi4yMTUsMTguNjY4DQoJCQljMS43NzgsNi4zMjQsNS45LDExLjU3MiwxMS42MTcsMTQuNzg2YzExLjMwOSw2LjM0MywyNS42NjksMi43NDksMzIuNjY5LTguMTc4bDAuNjMyLTAuNzk4DQoJCQljOC41NzItMTAuNjcsMjMuNDg2LTEzLjU0NCwzNS40NTEtNi44NGMwLjU2NywwLjMyMywxLjczOSwwLjc5OCwzLjE4MiwwLjM2OGMxLjY5OS0wLjUwMywzLjI5NS0yLjA2Nyw0Ljc1LTQuNjYyDQoJCQljMC4xNzYtMC4zMjIsMC4yNzgtMC41MzYsMC4yNzgtMC41MzZsMS4wNzQtMi4xNjVsMTAuODY1LDYuMTAzTDEwOC45NzEsODguMDA4eiBNMzUuMTc4LDEwMS40ODcNCgkJCWMtMy4yODUsNS44NjctMTAuNzA0LDcuOTQ1LTE2LjU2NCw0LjY1NmMtNS44NjYtMy4yOS03Ljk1NC0xMC43MTEtNC42NjItMTYuNTdjMy4yODQtNS44NjcsMTAuNzA4LTcuOTU0LDE2LjU3NS00LjY1NQ0KCQkJQzM2LjM4OCw4OC4yMDIsMzguNDc1LDk1LjYxOSwzNS4xNzgsMTAxLjQ4N3ogTTc1LjAwNywzMC41MTRjLTMuMjg1LDUuODYtMTAuNzA4LDcuOTQ3LTE2LjU2OCw0LjY2Mg0KCQkJYy01Ljg2MS0zLjI5OC03Ljk0OC0xMC43MTUtNC42NjUtMTYuNTc2YzMuMjk4LTUuODYsMTAuNzEtNy45NDcsMTYuNTc3LTQuNjU2Qzc2LjIxMSwxNy4yMzQsNzguMjk4LDI0LjY1Myw3NS4wMDcsMzAuNTE0eiIvPg0KCQk8cGF0aCBmaWxsPSIjMEIxRjJDIiBkPSJNMjAyLjY1MSwyMjAuNTY3Yy0xNi45ODktMjEuMDU0LTIzLjE0NS0zNC4zNjMtMjYuNjM1LTQyLjE3MmMtMi4yNjYtNS4wNy0zLjMxMS04LjQzMi0zLjc4Ni0xMC40MDQNCgkJCWM0Ljk1OS0zLjMzNiw5LjQwMy03LjE3MSwxMy4yMTYtMTEuNDEyYzIxLjIzNS0yMy42MDgsMjIuMTkxLTU4LjcyOSwyMS42ODktNzIuMTUyYzAsMC01LjE3OCw0MC4wMy0yOC41ODIsNjYuMDIxDQoJCQljLTExLjQ2OSwxMi43MjUtMjcuOTA4LDE5LjE5My00OC44NzgsMTkuMTkzaC0wLjAxMmMwLDAtMTMuMTUsMC41NjMtMjQuMTc1LTMuMTA0YzAsMC0yLjI1NCwxMC45NzUsMTMuOTg3LDEzLjEyM2wtMTkuNDA5LDM5LjI3OA0KCQkJYy0yLjg3MiwwLjUwNy0zLjk2NywwLjUyOC0xMS4zMzQsMC41MjhjLTE2LjMwNSwwLTQwLjYxNS0zLjY2Ni02NS44Ni0yMC42MjFsNDMuNTAxLTQ5LjA2NQ0KCQkJYzQxLjMwMyw2LjA2MSw4OS44MzItMy4yMjEsMTAxLjgxOS00OS42MThjLTE1LjYwNSwzOC41NDMtNTUuMjk5LDQ0LjAyOC05MC43NjksMzUuOTM1YzIzLjQ2Ni0zMS4zMTYsMzUuMjUxLTUzLjExLDQzLjI3LTY3LjkzNA0KCQkJYzEwLjI1My0xOC45NjUsMTQuNDk2LTI2LjgxNSwyOS43NDItMzIuMzIyYzguOTM0LTMuMjI1LDE2Ljc4NC00Ljg2MSwyMy4zMDYtNC44NjFjMTMuNTU4LDAsMTkuNjQ5LDYuODcxLDI1LjU0OSwxMy41MjQNCgkJCWMyLjc3MSwzLjEyNCw1LjM4MSw2LjA3OCw4LjY0NCw4LjEyNmwwLjUwNywwLjMyMmwtMjcuMTcsMTQuMjMybDI2LjU1OCwxMy4xMjRMMjU2LDU4LjI1bC00My42MDEtMTMuNzM2DQoJCQljLTEuOTk0LTEuMzc4LTMuOTUzLTMuNi02LjIwNi02LjEzOGMtNi4yMjctNy4wMTItMTQuNzQ1LTE2LjYyNy0zMi40NTItMTYuNjI3Yy03LjcwNCwwLTE2LjM2MSwxLjc2NS0yNi40MzQsNS40MDINCgkJCWMtMTguNTczLDYuNzEtMjQuMzA5LDE3LjMzNy0zNC43MzcsMzYuNjE3Yy04LjU2NCwxNS44NTYtMjEuNTE1LDM5LjgxOC00OC44NzIsNzUuMTE1TDMuNTcsMjAwLjM1MmMwLDAsMzEuMjYsMjguMzQsODUuMTYxLDI4LjM0DQoJCQljMTguNTc5LDAsMjkuMDQ4LTMuNzc4LDI5LjA0OC0zLjc3OGwxMC42NzktNDMuNTg2YzAuODM4LTAuMDExLDEuNjgxLTAuMDI5LDIuNTA5LTAuMDY3YzEuMDI3LDguNzY3LDQuNzYzLDI1LjU2NCwxNy43NjQsNDkuMzE5DQoJCQljLTEuNSwwLjU4OC0zLjM2LDEuNTY0LTUuNDQxLDMuMjUxYy0zLjgzNCwzLjA5MSwzLjg3MSwwLjY4Niw4Ljc3Ni0wLjM2MWM1LjMxNCwwLjU3NSwyNC4wNCw5LjIxNCwxNy40MiwyLjc3MQ0KCQkJYy0xLjMwMy0xLjI1NS0yLjUzOC0yLjI0NS0zLjcyMS0zLjExNWM2LjM5OSwyLjE3MywxMi42MzMsNC4yNjgsOC4zNzMsMC4xMjhjLTUuNTc5LTUuNDI2LTEwLjM4OC02Ljk0My0xMi4yMTMtNy4zNDcNCgkJCWMtMTUuNDI4LTI0LjI3My0xOC42NjEtMzkuMDQxLTE5LjE0My00NS45NzFjNi40ODktMS4yMDgsMTIuNjY3LTMuMTY5LDE4LjM5LTUuNzhjMi43ODEsOC44NDIsOC43MDksMjIuNjE0LDI4LjAyOCw0OS45MzUNCgkJCWMtMS42MTgsMC40MTktNC4xNjYsMS40MTEtNy4xMjgsMy44MDVjLTMuODM5LDMuMTA0LDMuODgxLDAuNjk3LDguNzg5LTAuMzQ3YzUuMzI3LDAuNTc3LDI0LjAyLDkuMjAzLDE3LjQwNywyLjc3MQ0KCQkJYy0xLjI5NS0xLjI2LTIuNTMzLTIuMjUtMy43MjQtMy4xMThjNi40MDIsMi4xNzYsMTIuNjM1LDQuMjYxLDguMzc0LDAuMTI5QzIwOC43NjMsMjIzLjI4NCwyMDUuMDQ2LDIyMS40MjgsMjAyLjY1MSwyMjAuNTY3eiIvPg0KCQk8Zz4NCgkJCTxwYXRoIGZpbGw9IiM1RDdFOTUiIGQ9Ik0xNzQuOTg2LDE0Ni4xODZjLTExLjEyNywxMi4zNTktMjcuMDkzLDE4LjYyNC00Ny40NDMsMTguNjI0Yy0wLjAwNywwLTAuMDA3LDAtMC4wMTQsMA0KCQkJCWMwLDAtMTIuNzYyLDAuNTU1LTIzLjQ1OS0zLjAxYzAsMC0wLjY0NCwzLjE3MiwxLjMxOSw2LjM5MWMtMC4wMzEtMS4wMTIsMC4wOTgtMS42NTUsMC4wOTgtMS42NTUNCgkJCQljMTEuMDI1LDMuNjY4LDI0LjE3NSwzLjEwNCwyNC4xNzUsMy4xMDRoMC4wMTJjMjAuOTcsMCwzNy40MDktNi40NjgsNDguODc4LTE5LjE5M2MyMi40NS0yNC45MjgsMjguMTE4LTYyLjc1NCwyOC41NTYtNjUuODE1DQoJCQkJbDAuNzE5LTQuMzI3bC00LjQxOC0yLjE4OWwtMC42ODEsMy45NzlDMjAyLjcyOSw4Mi4wOTYsMTk3LjcxMiwxMjAuOTUyLDE3NC45ODYsMTQ2LjE4NnoiLz4NCgkJCTxwYXRoIGZpbGw9IiM1RDdFOTUiIGQ9Ik04Ny44MDQsMjEzLjE4NmMtMTUuMjc1LDAtMzcuNzg4LTMuMzI1LTYxLjM3Ny0xOC4zNTVsLTMuNTU2LDQuMDEzDQoJCQkJYzI1LjI0NSwxNi45NTUsNDkuNTU1LDIwLjYyMSw2NS44NiwyMC42MjFjNy4zNjcsMCw4LjQ2Mi0wLjAyMSwxMS4zMzQtMC41MjhsMTkuNDA5LTM5LjI3OA0KCQkJCWMtMS40NjgtMC4xOTItMi43ODItMC40NjItMy45NjctMC43ODVsLTE2LjcwNiwzMy43OThDOTYuMDA3LDIxMy4xNTksOTQuOTUxLDIxMy4xODYsODcuODA0LDIxMy4xODZ6Ii8+DQoJCTwvZz4NCgk8L2c+DQo8L2c+DQo8L3N2Zz4NCg==
      mediatype: image/svg+xml
  install:
    strategy: deployment
    spec:
      deployments:
        - name: windup-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: windup-operator
            template:
              metadata:
                labels:
                  name: windup-operator
              spec:
                serviceAccountName: windup-operator
                containers:
                  - name: windup-operator
                    image: quay.io/windupeng/windup-operator-native:0.0.25
                    imagePullPolicy: Always
                    env:
                      - name: KUBERNETES_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: RELATED_IMAGE_WINDUP_WEB
                        value: quay.io/windupeng/windup-web-openshift:6.3.5.Final
                      - name: RELATED_IMAGE_WINDUP_WEB_EXECUTOR
                        value: quay.io/windupeng/windup-web-openshift-messaging-executor:6.3.5.Final
                      - name: RELATED_IMAGE_POSTGRESQL
                        value: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
                    ports:
                      - containerPort: 8080
                        name: http
                        protocol: TCP
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /q/health/live
                        port: 8080
                        scheme: HTTP
                      initialDelaySeconds: 0
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 10
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /q/health/ready
                        port: 8080
                        scheme: HTTP
                      initialDelaySeconds: 0
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 10
                    resources:
                      limits:
                        cpu: 1
                        memory: 256Mi
                      requests:
                        cpu: 100m
                        memory: 64Mi
            strategy:
              type: Recreate
      permissions:
        - serviceAccountName: windup-operator
          rules:
            - apiGroups:
                - apps
                - extensions
              resources:
                - deployments
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - pods
                - persistentvolumeclaims
                - services
                - configmaps
                - secrets
              verbs:
                - "*"
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - "*"
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - "*"
        - serviceAccountName: windup-operator
          rules:
            - apiGroups:
                - windup.jboss.org
              resources:
                - windups
                - windups/status
                - windups/finalizers
              verbs:
                - "*"
      clusterPermissions:
        - serviceAccountName: windup-operator
          rules:
            - apiGroups:
                - config.openshift.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
                - list
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - migration
    - modernization
    - windup
  maintainers:
    - email: migrate@redhat.com
      name: Windup
  maturity: alpha
  provider:
    name: Windup
  links:
    - name: Website
      url: https://windup.github.io
    - name: GitHub
      url: https://github.com/windup/windup-operator
  version: 0.0.25
  replaces: windup-operator.v0.0.24
