apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 0.8.0
  name: dynatrace-oneagent-csi-driver
