---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iofog-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iofog-operator
subjects:
  - kind: ServiceAccount
    name: iofog-operator

