apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aquastarboards.aquasecurity.github.io
spec:
  group: aquasecurity.github.io
  names:
    kind: AquaStarboard
    listKind: AquaStarboardList
    plural: aquastarboards
    singular: aquastarboard
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: Replicas Number
          jsonPath: .spec.deploy.replicas
        - name: Age
          type: date
          description: Aqua Starboard Age
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          description: Aqua Starboard status
          jsonPath: .status.state
        - name: Nodes
          type: string
          description: List Of Nodes (Pods)
          jsonPath: .status.nodes
      served: true
      storage: true
      subresources:
        status: {}
