apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: cronhotbackups.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: CronHotBackup
    listKind: CronHotBackupList
    plural: cronhotbackups
    shortNames:
    - chb
    singular: cronhotbackup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Suspention status of the CronHotBackup
      jsonPath: .spec.suspend
      name: SUSPENDED
      type: boolean
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CronHotBackup is the Schema for the cronhotbackups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CronHotBackupSpec defines the desired state of CronHotBackup
            properties:
              failedHotBackupsHistoryLimit:
                default: 3
                description: The number of failed finished hot backups to retain.
                  This is a pointer to distinguish between explicit zero and not specified.
                format: int32
                type: integer
              hotBackupTemplate:
                description: Specifies the hot backup that will be created when executing
                  a CronHotBackup.
                properties:
                  metadata:
                    description: Standard object's metadata of the hot backups created
                      from this template.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  spec:
                    description: Specification of the desired behavior of the hot
                      backup.
                    properties:
                      bucketURI:
                        description: URL of the bucket to download HotBackup folders.
                        type: string
                      hazelcastResourceName:
                        description: HazelcastResourceName defines the name of the
                          Hazelcast resource
                        type: string
                      secret:
                        description: Name of the secret with credentials for cloud
                          providers.
                        type: string
                    required:
                    - hazelcastResourceName
                    type: object
                required:
                - spec
                type: object
              schedule:
                description: "Schedule contains a crontab-like expression that defines
                  the schedule in which HotBackup will be started. If the Schedule
                  is empty the HotBackup will start only once when applied. --- Several
                  pre-defined schedules in place of a cron expression can be used.
                  \tEntry                  | Description                                |
                  Equivalent To \t-----                  | -----------                                |
                  ------------- \t@yearly (or @annually) | Run once a year, midnight,
                  Jan. 1st        | 0 0 1 1 * \t@monthly               | Run once
                  a month, midnight, first of month | 0 0 1 * * \t@weekly                |
                  Run once a week, midnight between Sat/Sun  | 0 0 * * 0 \t@daily
                  (or @midnight)  | Run once a day, midnight                   | 0
                  0 * * * \t@hourly                | Run once an hour, beginning of
                  hour        | 0 * * * *"
                minLength: 1
                type: string
              successfulHotBackupsHistoryLimit:
                default: 5
                description: The number of successful finished hot backups to retain.
                  This is a pointer to distinguish between explicit zero and not specified.
                format: int32
                type: integer
              suspend:
                default: false
                description: When true, CronHotBackup will stop creating HotBackup
                  CRs until it is disabled
                type: boolean
            required:
            - hotBackupTemplate
            - schedule
            type: object
          status:
            description: CronHotBackupStatus defines the observed state of CronHotBackup
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
