apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: wanreplications.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: WanReplication
    listKind: WanReplicationList
    plural: wanreplications
    shortNames:
    - wr
    singular: wanreplication
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the Hazelcast WAN Replication
      jsonPath: .status.status
      name: Status
      type: string
    - description: Message for the current WanReplication Config
      jsonPath: .status.message
      name: Message
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: WanReplication is the Schema for the wanreplications API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WanReplicationSpec defines the desired state of WanReplication
            properties:
              acknowledgement:
                description: Acknowledgement is the configuration for the condition
                  when the next batch of WAN events are sent.
                properties:
                  timeout:
                    default: 60000
                    description: Timeout represents the time the source cluster waits
                      for the acknowledgement. After timeout, the events will be resent.
                    format: int32
                    type: integer
                  type:
                    default: ACK_ON_OPERATION_COMPLETE
                    description: Type represents how a batch of replication events
                      is considered successfully replicated.
                    enum:
                    - ACK_ON_OPERATION_COMPLETE
                    - ACK_ON_RECEIPT
                    type: string
                type: object
              batch:
                description: Batch is the configuration for WAN events batch.
                properties:
                  maximumDelay:
                    default: 1000
                    description: MaximumDelay represents the maximum delay in milliseconds.
                      If the batch size is not reached, the events will be sent after
                      the maximum delay.
                    format: int32
                    type: integer
                  size:
                    default: 500
                    description: Size represents the maximum batch size.
                    format: int32
                    type: integer
                type: object
              endpoints:
                description: Endpoints is the target cluster endpoints.
                minLength: 1
                type: string
              queue:
                description: Queue is the configuration for WAN events queue.
                properties:
                  capacity:
                    default: 10000
                    description: Capacity is the total capacity of WAN queue.
                    format: int32
                    type: integer
                  fullBehavior:
                    default: DISCARD_AFTER_MUTATION
                    description: FullBehavior represents the behavior of the new arrival
                      when the queue is full.
                    enum:
                    - DISCARD_AFTER_MUTATION
                    - THROW_EXCEPTION
                    - THROW_EXCEPTION_ONLY_IF_REPLICATION_ACTIVE
                    type: string
                type: object
              resources:
                description: Resources is the list of custom resources to which WAN
                  replication applies.
                items:
                  properties:
                    kind:
                      default: Map
                      description: Kind is the kind of custom resource to which WAN
                        replication applies.
                      enum:
                      - Map
                      - Hazelcast
                      type: string
                    name:
                      description: Name is the name of custom resource to which WAN
                        replication applies.
                      minLength: 1
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                minItems: 1
                type: array
              targetClusterName:
                description: ClusterName is the clusterName field of the target Hazelcast
                  resource.
                minLength: 1
                type: string
            required:
            - endpoints
            - resources
            - targetClusterName
            type: object
          status:
            description: WanReplicationStatus defines the observed state of WanReplication
            properties:
              message:
                description: Message is the field to show detail information or error
                type: string
              status:
                description: Status is the status of WAN replication
                type: string
              wanReplicationMapsStatus:
                additionalProperties:
                  properties:
                    message:
                      description: Message is the field to show detail information
                        or error
                      type: string
                    publisherId:
                      description: PublisherId is the ID used for WAN publisher ID
                      type: string
                    status:
                      description: Status is the status of WAN replication
                      type: string
                  type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
