---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometurbos.charts.helm.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/operator-framework/operator-sdk/pull/2703"
spec:
  group: charts.helm.k8s.io
  names:
    kind: Prometurbo
    listKind: PrometurboList
    plural: prometurbos
    singular: prometurbo
  scope: Namespaced
  versions:
  # Each version can be enabled/disabled by Served flag.
  # One and only one version must be marked as the storage version.
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        description: Prometurbo is the Schema for the prometurbos API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Prometurbo
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of Prometurbo
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Prometurbo is the Schema for the prometurboes API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Prometurbo
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              replicaCount:
                description: Prometurbo replicaCount
                type: integer
              image:
                description: Prometurbo image details for deployments outside of RH Operator Hub
                type: object
                properties:
                  prometurboRepository:
                    description: Container repository. default is docker hub
                    type: string
                  prometurboTag:
                    description: Prometurbo container image tag
                    type: string
                  turbodifRepository:
                    description: Container repository. default is docker hub
                    type: string
                  turbodifTag:
                    description: Turbodif container image tag
                    type: string
                  pullPolicy:
                    description: Define pull policy, Always is default
                    type: string
                  imagePullSecret:
                    description: Define the secret used to authenticate to the container image registry
                    type: string
              serverMeta:
                description: Configuration for Turbo Server
                type: object
                properties:
                  version:
                    description: Turbo Server major version
                    type: string
                  turboServer:
                    description: URL for Turbo Server endpoint
                    type: string
              restAPIConfig:
                description: Credentials to register probe with Turbo Server
                type: object
                properties:
                  turbonomicCredentialsSecretName:
                    description: Name of k8s secret that contains the turbo credentials
                    type: string
                  opsManagerUserName:
                    description: Turbo admin user id
                    type: string
                  opsManagerPassword:
                    description: Turbo admin user password
                    type: string
              targetName:
                description: Optional target name for registration
                type: string
              targetAddress:
                description: Optional target address for registration
                type: string
              args:
                description: Prometurbo command line arguments
                type: object
                properties:
                  logginglevel:
                    description: Define logging level, default is info = 2
                    type: integer
                  ignoreCommodityIfPresent:
                    description: Ignore merging a commodity if a commodity of the same type already exists
                    type: boolean
              resources:
                description: Prometurbo resource configuration
                type: object
                properties:
                  limits:
                    description: Define limits
                    type: object
                    properties:
                      memory:
                        description: Define memory limits in Gi or Mi, include units
                        type: string
                      cpu:
                        description: Define cpu limits in cores or millicores, include units
                        type: string
                  requests:
                    description: Define requests
                    type: object
                    properties:
                      memory:
                        description: Define memory requests in Gi or Mi, include units
                        type: string
                      cpu:
                        description: Define cpu requests in cores or millicores, include units
                        type: string
          status:
            description: Status defines the observed state of Prometurbo
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
