apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: elasticsearches.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: ElasticSearch
    plural: elasticsearches
    shortNames:
    - es
    singular: elasticsearch
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    - description: Instance
      jsonPath: .spec.instance.plan
      name: instance
      type: string
    - description: Version
      jsonPath: .spec.options.version
      name: version
      type: integer
    - description: Cold encryption
      jsonPath: .spec.options.encryption
      name: encrypted
      type: boolean
    - description: Kibana
      jsonPath: .spec.options.kibana
      name: kibana
      type: boolean
    - description: Application Perfomance Monitoring
      jsonPath: .spec.options.apm
      name: apm
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  plan:
                    type: string
                  region:
                    type: string
                required:
                - plan
                - region
                type: object
              options:
                properties:
                  apm:
                    type: boolean
                  encryption:
                    type: boolean
                  kibana:
                    type: boolean
                  version:
                    enum:
                    - 6
                    - 7
                    - 8
                    type: integer
                required:
                - apm
                - encryption
                - kibana
                - version
                type: object
              organisation:
                type: string
            required:
            - instance
            - options
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: ElasticSearch
        type: object
    served: true
    storage: true
    subresources:
      status: {}
