apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: "quay.io/debezium/operator:2.5.3.Final"
    repository: "https://github.com/debezium/debezium-operator/debezium-operator-dist"
    capabilities: Basic Install
    categories: "Big Data, Database, Integration & Delivery, Streaming & Messaging"
    certified: "false"
    alm-examples: |
      [
          {
            "apiVersion": "debezium.io/v1alpha1",
            "kind": "DebeziumServer",
            "metadata": {
              "name": "debezium-test"
            },
            "spec": {
              "quarkus": {
                "config": {
                  "log.console.json": false
                }
              },
              "sink": {
                "type": "kafka",
                "config": {
                  "producer.bootstrap.servers": "dbz-kafka-kafka-bootstrap.debezium:9092",
                  "producer.key.serializer": "org.apache.kafka.common.serialization.StringSerializer",
                  "producer.value.serializer": "org.apache.kafka.common.serialization.StringSerializer"
                }
              },
              "source": {
                "class": "io.debezium.connector.mongodb.MongoDbConnector",
                "config": {
                  "topic.prefix": "dbserver1",
                  "offset.storage.file.filename": "/debezium/data/offsets.dat",
                  "database.history": "io.debezium.relational.history.FileDatabaseHistory",
                  "mongodb.connection.string": "mongodb://debezium:dbz@mongo.debezium:27017/?replicaSet=rs0"
                }
              }
            }
          }
      ]
    createdAt: "2024-03-19T08:17:17Z"
    support: Debezium Authors
    description: An Operator for installing and managing Debezium
  name: "debezium-operator.v2.5.3-final"
spec:
  customresourcedefinitions:
    owned:
    - kind: DebeziumServer
      description: Represents a Debezium Server
      displayName: DebeziumServer
      name: debeziumservers.debezium.io
      version: v1alpha1
  description: "Debezium is an open source distributed platform for change data capture.\
    \ Start it up, point it at your databases, and your apps can start responding\
    \ to all of the inserts, updates, and deletes that other apps commit to your databases"
  displayName: Debezium Operator
  icon:
  - base64data: PHN2ZyBpZD0iY29sb3IiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHZpZXdCb3g9IjAgMCA0OCA0OCI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50KTt9LmNscy0ye2ZpbGw6dXJsKCNsaW5lYXItZ3JhZGllbnQtMik7fS5jbHMtM3tmaWxsOnVybCgjbGluZWFyLWdyYWRpZW50LTMpO30uY2xzLTR7ZmlsbDp1cmwoI2xpbmVhci1ncmFkaWVudC00KTt9LmNscy01e2ZpbGw6dXJsKCNsaW5lYXItZ3JhZGllbnQtNSk7fTwvc3R5bGU+PGxpbmVhckdyYWRpZW50IGlkPSJsaW5lYXItZ3JhZGllbnQiIHgxPSI3LjI3IiB5MT0iNy4yNyIgeDI9IjQxLjc2IiB5Mj0iNDEuNzYiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiM5MWQ0NDMiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiM0OGJmZTAiLz48L2xpbmVhckdyYWRpZW50PjxsaW5lYXJHcmFkaWVudCBpZD0ibGluZWFyLWdyYWRpZW50LTIiIHgxPSIxNS44NSIgeTE9Ii0xLjMxIiB4Mj0iNTAuMzQiIHkyPSIzMy4xOCIgeGxpbms6aHJlZj0iI2xpbmVhci1ncmFkaWVudCIvPjxsaW5lYXJHcmFkaWVudCBpZD0ibGluZWFyLWdyYWRpZW50LTMiIHgxPSIyNC40IiB5MT0iLTkuODYiIHgyPSI1OC44OSIgeTI9IjI0LjYzIiB4bGluazpocmVmPSIjbGluZWFyLWdyYWRpZW50Ii8+PGxpbmVhckdyYWRpZW50IGlkPSJsaW5lYXItZ3JhZGllbnQtNCIgeDE9Ii0xLjMxIiB5MT0iMTUuODUiIHgyPSIzMy4xOCIgeTI9IjUwLjM0IiB4bGluazpocmVmPSIjbGluZWFyLWdyYWRpZW50Ii8+PGxpbmVhckdyYWRpZW50IGlkPSJsaW5lYXItZ3JhZGllbnQtNSIgeDE9Ii05Ljg2IiB5MT0iMjQuNCIgeDI9IjI0LjYzIiB5Mj0iNTguODkiIHhsaW5rOmhyZWY9IiNsaW5lYXItZ3JhZGllbnQiLz48L2RlZnM+PHRpdGxlPmNvbG9yPC90aXRsZT48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0zNC4zNiw0MS44NmE2LjA5LDYuMDksMCwwLDAsNi4wOCw2LjA4aDcuNTFWNDAuNDNhNi4wOSw2LjA5LDAsMCwwLTYuMDgtNi4wOEg0MC40NGE5LjY1LDkuNjUsMCwwLDEtOS42NC05LjY0VjIzLjI4YTYuMDksNi4wOSwwLDAsMC02LjA4LTYuMDhIMjMuMjlhOS42NSw5LjY1LDAsMCwxLTkuNjQtOS42NGgwVjYuMTNBNi4wOSw2LjA5LDAsMCwwLDcuNTYsMEguMDVWNy41NmE2LjA5LDYuMDksMCwwLDAsNi4wOCw2LjA4SDcuNTZhOS42NSw5LjY1LDAsMCwxLDkuNjQsOS42NHYxLjQyYTYuMDksNi4wOSwwLDAsMCw2LjA4LDYuMDhoMS40M2E5LjY1LDkuNjUsMCwwLDEsOS42NCw5LjY0aDBaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNDcuOTUsMjMuMjhhNi4wOSw2LjA5LDAsMCwwLTYuMDgtNi4wOEg0MC40NGE5LjY1LDkuNjUsMCwwLDEtOS42NC05LjY0VjYuMTNBNi4wOSw2LjA5LDAsMCwwLDI0LjcxLDBoLTcuNVY3LjY0YTYuMDksNi4wOSwwLDAsMCw2LjA4LDZoMS40M2E5LjY1LDkuNjUsMCwwLDEsOS42NCw5LjY0aDB2MS40MmE2LjA5LDYuMDksMCwwLDAsNi4wNiw2LjA4aDcuNTNaIi8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNNDcuOTUsNi4wOGE2LjA4LDYuMDgsMCwwLDAtNS44NC02SDM0LjI0VjcuNjJhNi4wOSw2LjA5LDAsMCwwLDYuMDgsNmg3LjYzWiIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTS4wNSwyNC43MkE2LjA5LDYuMDksMCwwLDAsNi4xNCwzMC44SDcuNTdhOS42NSw5LjY1LDAsMCwxLDkuNjQsOS42NHYxLjQyQTYuMDksNi4wOSwwLDAsMCwyMy4yOSw0OGg3LjVWNDAuMzZhNi4wOSw2LjA5LDAsMCwwLTYuMDgtNkgyMy4yOWE5LjY1LDkuNjUsMCwwLDEtOS42NC05LjY0aDBWMjMuMjlhNi4wOSw2LjA5LDAsMCwwLTYuMDYtNi4wOEguMDVaIi8+PHBhdGggY2xhc3M9ImNscy01IiBkPSJNLjA1LDQxLjkyYTYuMDgsNi4wOCwwLDAsMCw1Ljg0LDZoNy44N1Y0MC4zOGE2LjA5LDYuMDksMCwwLDAtNi4wOC02SC4wNVoiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: debezium-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: debezium-operator
          template:
            metadata:
              annotations:
                app.quarkus.io/quarkus-version: 3.7.2
              labels:
                app.kubernetes.io/managed-by: quarkus
                app.kubernetes.io/name: debezium-operator
            spec:
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_DEBEZIUMSERVER_NAMESPACES
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.annotations['olm.targetNamespaces']"
                image: quay.io/debezium/operator:2.5.3.Final
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                name: debezium-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                startupProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/started
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
              serviceAccountName: debezium-operator
      permissions:
      - rules:
        - apiGroups:
          - debezium.io
          resources:
          - debeziumservers
          - debeziumservers/status
          - debeziumservers/finalizers
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - delete
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        serviceAccountName: debezium-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: AllNamespaces
  - supported: true
    type: MultiNamespace
  keywords:
  - Debezium
  - CDC
  - Data
  - Streaming
  links:
  - name: Debezium
    url: https://debezium.io/
  - name: Documentation
    url: https://debezium.io/documentation/reference/stable/
  - name: Debezium Zulip Chat
    url: https://debezium.zulipchat.com
  maintainers:
  - email: debezium@googlegroups.com
    name: Debezium Authors
  nativeAPIs:
  - kind: ConfigMap
    group: ""
    version: v1
  - kind: PersistentVolumeClaim
    group: ""
    version: v1
  - kind: ServiceAccount
    group: ""
    version: v1
  - kind: Service
    group: ""
    version: v1
  - kind: Deployment
    group: apps
    version: v1
  - kind: RoleBinding
    group: rbac.authorization.k8s.io
    version: v1
  - kind: Role
    group: rbac.authorization.k8s.io
    version: v1
  provider:
    name: Debezium Authors
    url: https://debezium.io/
  version: 2.5.3-final
  replaces: debezium-operator.v2.5.2-final
