apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: validation-runner
    app.kubernetes.io/name: jupyter-notebook-validator-operator
  name: notebook-validator-jupyter-notebook-validator-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notebook-validator-jupyter-notebook-validator-runner-role
subjects:
- kind: ServiceAccount
  name: notebook-validator-jupyter-notebook-validator-runner
  namespace: jupyter-notebook-validator-operator
