apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  creationTimestamp: null
  name: dbinstances.documentdb.services.k8s.aws
spec:
  group: documentdb.services.k8s.aws
  names:
    kind: DBInstance
    listKind: DBInstanceList
    plural: dbinstances
    singular: dbinstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.dbInstanceStatus
      name: STATUS
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DBInstance is the Schema for the DBInstances API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              DBInstanceSpec defines the desired state of DBInstance.


              Detailed information about an instance.
            properties:
              autoMinorVersionUpgrade:
                description: |-
                  This parameter does not apply to Amazon DocumentDB. Amazon DocumentDB does
                  not perform minor version upgrades regardless of the value set.


                  Default: false
                type: boolean
              availabilityZone:
                description: |-
                  The Amazon EC2 Availability Zone that the instance is created in.


                  Default: A random, system-chosen Availability Zone in the endpoint's Amazon
                  Web Services Region.


                  Example: us-east-1d
                type: string
              caCertificateIdentifier:
                description: |-
                  The CA certificate identifier to use for the DB instance's server certificate.


                  For more information, see Updating Your Amazon DocumentDB TLS Certificates
                  (https://docs.aws.amazon.com/documentdb/latest/developerguide/ca_cert_rotation.html)
                  and Encrypting Data in Transit (https://docs.aws.amazon.com/documentdb/latest/developerguide/security.encryption.ssl.html)
                  in the Amazon DocumentDB Developer Guide.
                type: string
              copyTagsToSnapshot:
                description: |-
                  A value that indicates whether to copy tags from the DB instance to snapshots
                  of the DB instance. By default, tags are not copied.
                type: boolean
              dbClusterIdentifier:
                description: The identifier of the cluster that the instance will
                  belong to.
                type: string
              dbInstanceClass:
                description: The compute and memory capacity of the instance; for
                  example, db.r5.large.
                type: string
              dbInstanceIdentifier:
                description: |-
                  The instance identifier. This parameter is stored as a lowercase string.


                  Constraints:


                     * Must contain from 1 to 63 letters, numbers, or hyphens.


                     * The first character must be a letter.


                     * Cannot end with a hyphen or contain two consecutive hyphens.


                  Example: mydbinstance
                type: string
              engine:
                description: |-
                  The name of the database engine to be used for this instance.


                  Valid value: docdb
                type: string
              performanceInsightsEnabled:
                description: |-
                  A value that indicates whether to enable Performance Insights for the DB
                  Instance. For more information, see Using Amazon Performance Insights (https://docs.aws.amazon.com/documentdb/latest/developerguide/performance-insights.html).
                type: boolean
              performanceInsightsKMSKeyID:
                description: |-
                  The KMS key identifier for encryption of Performance Insights data.


                  The KMS key identifier is the key ARN, key ID, alias ARN, or alias name for
                  the KMS key.


                  If you do not specify a value for PerformanceInsightsKMSKeyId, then Amazon
                  DocumentDB uses your default KMS key. There is a default KMS key for your
                  Amazon Web Services account. Your Amazon Web Services account has a different
                  default KMS key for each Amazon Web Services region.
                type: string
              performanceInsightsKMSKeyRef:
                description: "AWSResourceReferenceWrapper provides a wrapper around
                  *AWSResourceReference\ntype to provide more user friendly syntax
                  for references using 'from' field\nEx:\nAPIIDRef:\n\n\n\tfrom:\n\t
                  \ name: my-api"
                properties:
                  from:
                    description: |-
                      AWSResourceReference provides all the values necessary to reference another
                      k8s resource for finding the identifier(Id/ARN/Name)
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                type: object
              preferredMaintenanceWindow:
                description: |-
                  The time range each week during which system maintenance can occur, in Universal
                  Coordinated Time (UTC).


                  Format: ddd:hh24:mi-ddd:hh24:mi


                  The default is a 30-minute window selected at random from an 8-hour block
                  of time for each Amazon Web Services Region, occurring on a random day of
                  the week.


                  Valid days: Mon, Tue, Wed, Thu, Fri, Sat, Sun


                  Constraints: Minimum 30-minute window.
                type: string
              promotionTier:
                description: |-
                  A value that specifies the order in which an Amazon DocumentDB replica is
                  promoted to the primary instance after a failure of the existing primary
                  instance.


                  Default: 1


                  Valid values: 0-15
                format: int64
                type: integer
              tags:
                description: |-
                  The tags to be assigned to the instance. You can assign up to 10 tags to
                  an instance.
                items:
                  description: |-
                    Metadata assigned to an Amazon DocumentDB resource consisting of a key-value
                    pair.
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            required:
            - dbClusterIdentifier
            - dbInstanceClass
            - dbInstanceIdentifier
            - engine
            type: object
          status:
            description: DBInstanceStatus defines the observed state of DBInstance
            properties:
              ackResourceMetadata:
                description: |-
                  All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
                  that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: |-
                      ARN is the Amazon Resource Name for the resource. This is a
                      globally-unique identifier and is set only by the ACK service controller
                      once the controller has orchestrated the creation of the resource OR
                      when it has verified that an "adopted" resource (a resource where the
                      ARN annotation was set by the Kubernetes user on the CR) exists and
                      matches the supplied CR's Spec field values.
                      TODO(vijat@): Find a better strategy for resources that do not have ARN in CreateOutputResponse
                      https://github.com/aws/aws-controllers-k8s/issues/270
                    type: string
                  ownerAccountID:
                    description: |-
                      OwnerAccountID is the AWS Account ID of the account that owns the
                      backend AWS service API resource.
                    type: string
                  region:
                    description: Region is the AWS region in which the resource exists
                      or will exist.
                    type: string
                required:
                - ownerAccountID
                - region
                type: object
              backupRetentionPeriod:
                description: Specifies the number of days for which automatic snapshots
                  are retained.
                format: int64
                type: integer
              certificateDetails:
                description: The details of the DB instance's server certificate.
                properties:
                  cAIdentifier:
                    type: string
                  validTill:
                    format: date-time
                    type: string
                type: object
              conditions:
                description: |-
                  All CRS managed by ACK have a common `Status.Conditions` member that
                  contains a collection of `ackv1alpha1.Condition` objects that describe
                  the various terminal states of the CR and its backend AWS service API
                  resource
                items:
                  description: |-
                    Condition is the common struct used by all CRDs managed by ACK service
                    controllers to indicate terminal states  of the CR and its backend AWS
                    service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              dbInstanceStatus:
                description: Specifies the current state of this database.
                type: string
              dbSubnetGroup:
                description: |-
                  Specifies information on the subnet group that is associated with the instance,
                  including the name, description, and subnets in the subnet group.
                properties:
                  dbSubnetGroupARN:
                    type: string
                  dbSubnetGroupDescription:
                    type: string
                  dbSubnetGroupName:
                    type: string
                  subnetGroupStatus:
                    type: string
                  subnets:
                    items:
                      description: Detailed information about a subnet.
                      properties:
                        subnetAvailabilityZone:
                          description: Information about an Availability Zone.
                          properties:
                            name:
                              type: string
                          type: object
                        subnetIdentifier:
                          type: string
                        subnetStatus:
                          type: string
                      type: object
                    type: array
                  vpcID:
                    type: string
                type: object
              dbiResourceID:
                description: |-
                  The Amazon Web Services Region-unique, immutable identifier for the instance.
                  This identifier is found in CloudTrail log entries whenever the KMS key for
                  the instance is accessed.
                type: string
              enabledCloudwatchLogsExports:
                description: |-
                  A list of log types that this instance is configured to export to CloudWatch
                  Logs.
                items:
                  type: string
                type: array
              endpoint:
                description: Specifies the connection endpoint.
                properties:
                  address:
                    type: string
                  hostedZoneID:
                    type: string
                  port:
                    format: int64
                    type: integer
                type: object
              engineVersion:
                description: Indicates the database engine version.
                type: string
              instanceCreateTime:
                description: Provides the date and time that the instance was created.
                format: date-time
                type: string
              kmsKeyID:
                description: If StorageEncrypted is true, the KMS key identifier for
                  the encrypted instance.
                type: string
              latestRestorableTime:
                description: |-
                  Specifies the latest time to which a database can be restored with point-in-time
                  restore.
                format: date-time
                type: string
              pendingModifiedValues:
                description: |-
                  Specifies that changes to the instance are pending. This element is included
                  only when changes are pending. Specific changes are identified by subelements.
                properties:
                  allocatedStorage:
                    format: int64
                    type: integer
                  backupRetentionPeriod:
                    format: int64
                    type: integer
                  caCertificateIdentifier:
                    type: string
                  dbInstanceClass:
                    type: string
                  dbInstanceIdentifier:
                    type: string
                  dbSubnetGroupName:
                    type: string
                  engineVersion:
                    type: string
                  iops:
                    format: int64
                    type: integer
                  licenseModel:
                    type: string
                  masterUserPassword:
                    type: string
                  multiAZ:
                    type: boolean
                  pendingCloudwatchLogsExports:
                    description: |-
                      A list of the log types whose configuration is still pending. These log types
                      are in the process of being activated or deactivated.
                    properties:
                      logTypesToDisable:
                        items:
                          type: string
                        type: array
                      logTypesToEnable:
                        items:
                          type: string
                        type: array
                    type: object
                  port:
                    format: int64
                    type: integer
                  storageType:
                    type: string
                type: object
              preferredBackupWindow:
                description: |-
                  Specifies the daily time range during which automated backups are created
                  if automated backups are enabled, as determined by the BackupRetentionPeriod.
                type: string
              publiclyAccessible:
                description: |-
                  Not supported. Amazon DocumentDB does not currently support public endpoints.
                  The value of PubliclyAccessible is always false.
                type: boolean
              statusInfos:
                description: |-
                  The status of a read replica. If the instance is not a read replica, this
                  is blank.
                items:
                  description: Provides a list of status information for an instance.
                  properties:
                    message:
                      type: string
                    normal:
                      type: boolean
                    status:
                      type: string
                    statusType:
                      type: string
                  type: object
                type: array
              storageEncrypted:
                description: Specifies whether or not the instance is encrypted.
                type: boolean
              vpcSecurityGroups:
                description: |-
                  Provides a list of VPC security group elements that the instance belongs
                  to.
                items:
                  description: |-
                    Used as a response element for queries on virtual private cloud (VPC) security
                    group membership.
                  properties:
                    status:
                      type: string
                    vpcSecurityGroupID:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
