apiVersion: v1
data:
  redkey_operator_config.yaml: |
    # SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
    # SPDX-License-Identifier: Apache-2.0

    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: db95d8a6.inditex.dev
kind: ConfigMap
metadata:
  name: redkey-operator-config
