apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: hotbackups.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: HotBackup
    listKind: HotBackupList
    plural: hotbackups
    singular: hotbackup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HotBackup is the Schema for the hot backup API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HotBackupSpec defines the Spec of HotBackup
            properties:
              hazelcastResourceName:
                description: HazelcastResourceName defines the name of the Hazelcast
                  resource
                type: string
              schedule:
                description: "Schedule contains a crontab-like expression that defines
                  the schedule in which HotBackup will be started. If the Schedule
                  is empty the HotBackup will start only once when applied. --- Several
                  pre-defined schedules in place of a cron expression can be used.
                  \tEntry                  | Description                                |
                  Equivalent To \t-----                  | -----------                                |
                  ------------- \t@yearly (or @annually) | Run once a year, midnight,
                  Jan. 1st        | 0 0 1 1 * \t@monthly               | Run once
                  a month, midnight, first of month | 0 0 1 * * \t@weekly                |
                  Run once a week, midnight between Sat/Sun  | 0 0 * * 0 \t@daily
                  (or @midnight)  | Run once a day, midnight                   | 0
                  0 * * * \t@hourly                | Run once an hour, beginning of
                  hour        | 0 * * * *"
                type: string
            required:
            - hazelcastResourceName
            type: object
          status:
            description: HotBackupStatus defines the observed state of HotBackup
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
