apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: turbines.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: Turbine
    listKind: TurbineList
    plural: turbines
    singular: turbine
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Turbine is the Schema for the turbines API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TurbineSpec defines the desired state of Turbine
            properties:
              hazelcast:
                description: Hazelcast cluster to connect. If present, only one of
                  "clusterAddress" or "cluster" must be defined.
                maxProperties: 1
                minProperties: 1
                properties:
                  cluster:
                    description: Reference to Hazelcast CR
                    properties:
                      name:
                        description: Name of Hazelcast CR
                        type: string
                      namespace:
                        default: default
                        description: Namespace of Hazelcast CR
                        type: string
                    required:
                    - name
                    type: object
                  clusterAddress:
                    description: Address of the Hazelcast cluster
                    type: string
                type: object
              pods:
                description: Pod configuration
                properties:
                  portName:
                    description: The name of the container port that Turbine will
                      register
                    type: string
                type: object
              sidecar:
                default:
                  name: turbine-sidecar
                description: Sidecar configuration
                properties:
                  name:
                    default: turbine-sidecar
                    description: Name of the Turbine sidecar container
                    type: string
                  repository:
                    default: hazelcast/turbine-sidecar
                    description: Repository of the image used for Turbine sidecar
                      container
                    type: string
                  version:
                    default: latest
                    description: Version of the image used for Turbine sidecar container
                    type: string
                type: object
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
