apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: layer7-operator-system/layer7-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.16.5
  creationTimestamp: null
  name: repositories.security.brcmlabs.com
spec:
  group: security.brcmlabs.com
  names:
    kind: Repository
    listKind: RepositoryList
    plural: repositories
    shortNames:
    - repo
    - repos
    - l7repo
    - l7repos
    - l7repository
    - l7repositories
    singular: repository
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Repository is the Schema for the repositories API
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represent
            type: string
          metadata:
            type: object
          spec:
            description: Spec - Repository Spec
            properties:
              annotations:
                additionalProperties:
                  type: string
                description: Annotations - Custom Annotations
                type: object
              auth:
                description: Auth contains a reference to the credentials required
                  to connect to your Gi
                properties:
                  existingSecretName:
                    description: ExistingSecretName reference an existing secret
                    type: string
                  knownHosts:
                    description: KnownHosts is required for SSH Auth
                    type: string
                  password:
                    description: |-
                      Password repository Password
                      password or token are acceptable
                    type: string
                  sshKey:
                    description: SSHKey for Git SSH Authentication
                    type: string
                  sshKeyPass:
                    description: SSHKeyPass
                    type: string
                  token:
                    description: Token repository Access Token
                    type: string
                  type:
                    description: |-
                      Auth Type defaults to basic, possible options are
                      none, basic or ssh
                    type: string
                  username:
                    description: Username repository username
                    type: string
                  vendor:
                    description: Vendor i.e. Github, Gitlab, BitBucket, Azure
                    type: string
                type: object
              branch:
                description: |-
                  Branch - specify which branch to clone
                  if branch and tag are both specified
                type: string
              enabled:
                description: Enabled - if enabled this repository will be synced
                type: boolean
              endpoint:
                description: Endoint - Git repository endpoint
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Labels - Custom Labels
                type: object
              localReference:
                description: LocalReference lets the Repository controller use a local
                  Kubernetes Secret
                properties:
                  secretName:
                    type: string
                type: object
              remoteName:
                description: Remote Name - defaults to "origin"
                type: string
              stateStoreKey:
                description: "StateStoreKey where the repository is stored in the
                  L7StateStore\nthis only "
                type: string
              stateStoreReference:
                description: StateStoreReference which L7StateStore connection should
                  be used to store o
                type: string
              sync:
                description: RepositorySyncConfig defines how often this repository
                  is synced
                properties:
                  interval:
                    description: Configure how frequently the remote is checked for
                      new commits
                    type: integer
                type: object
              tag:
                description: Tag - clone a specific tag.
                type: string
              type:
                description: Type of Repository - git, http, local, statestore
                type: string
            type: object
          status:
            description: Status - Repository Status
            properties:
              commit:
                description: Commit is either current git commit that has been synced
                  or a sha1sum of th
                type: string
              lastAppliedSummary:
                type: string
              name:
                description: Name of the Repository
                type: string
              ready:
                description: Ready to apply to Gateway Deployments
                type: boolean
              stateStoreSynced:
                description: StateStoreSynced whether or not the state store has been
                  written to correct
                type: boolean
              stateStoreVersion:
                description: StateStoreVersion tracks version in state store
                type: integer
              storageSecretName:
                description: StorageSecretName is the Kubernetes Secret that this
                  repository is stored i
                type: string
              summary:
                type: string
              updated:
                description: Updated the last time this repository was successfully
                  updated
                type: string
              vendor:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
