apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: layer7-operator-system/layer7-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.16.5
  creationTimestamp: null
  name: l7portals.security.brcmlabs.com
spec:
  group: security.brcmlabs.com
  names:
    kind: L7Portal
    listKind: L7PortalList
    plural: l7portals
    shortNames:
    - portal
    - portals
    singular: l7portal
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: L7Portal is the Schema for the l7portals API
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represent
            type: string
          metadata:
            type: object
          spec:
            description: L7PortalSpec defines the desired state of L7Portal
            properties:
              auth:
                description: Auth - Portal credentials
                properties:
                  clientId:
                    type: string
                  clientSecret:
                    type: string
                  endpoint:
                    type: string
                  existingSecretName:
                    type: string
                type: object
              deploymentTags:
                description: Deployment Tags - determines which Gateway deployments
                  these APIs will be a
                items:
                  type: string
                type: array
              enabled:
                description: Enabled - if enabled this Portal and its APIs will be
                  synced
                type: boolean
              endpoint:
                description: Endoint - Portal endpoint
                type: string
              enrollmentBundle:
                description: EnrollmentBundle - allows a custom enrollment bundle
                  to be set in the Porta
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Labels - Custom Labels
                type: object
              portalTenant:
                description: PortalTenant is the tenantId of the API Developer Portal
                type: string
              syncIntervalSeconds:
                description: SyncIntervalSeconds how often the Portal CR is reconciled.
                type: integer
            type: object
          status:
            description: L7PortalStatus defines the observed state of L7Portal
            properties:
              apiCount:
                type: integer
              apiSummaryConfigMap:
                type: string
              checksum:
                type: string
              enrollmentBundle:
                description: EnrollmentBundle
                properties:
                  lastUpdated:
                    type: string
                  secretName:
                    type: string
                type: object
              lastUpdated:
                format: int64
                type: integer
              proxies:
                items:
                  description: GatewayProxy
                  properties:
                    gateways:
                      items:
                        properties:
                          lastUpdated:
                            type: string
                          name:
                            type: string
                          synchronised:
                            type: boolean
                        type: object
                      type: array
                    name:
                      type: string
                    type:
                      description: Type - Ephemeral or DbBacked
                      type: string
                  type: object
                type: array
              ready:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
