apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: mongodb-atlas-kubernetes-operator
    app.kubernetes.io/name: mongodb-atlas-kubernetes-operator
  name: atlasstreaminstances.atlas.mongodb.com
spec:
  group: atlas.mongodb.com
  names:
    categories:
    - atlas
    kind: AtlasStreamInstance
    listKind: AtlasStreamInstanceList
    plural: atlasstreaminstances
    shortNames:
    - asi
    singular: atlasstreaminstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.name
      name: Name
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.id
      name: Atlas ID
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: AtlasStreamInstance is the Schema for the atlasstreaminstances
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterConfig:
                description: The configuration to be used to connect to a Atlas Cluster
                properties:
                  provider:
                    default: AWS
                    description: Name of the cluster configured for this connection
                    enum:
                    - AWS
                    - GCP
                    - AZURE
                    - TENANT
                    - SERVERLESS
                    type: string
                  region:
                    description: Name of the cloud provider region hosting Atlas Stream
                      Processing.
                    type: string
                  tier:
                    default: SP10
                    description: Selected tier for the Stream Instance. Configures
                      Memory / VCPU allowances.
                    enum:
                    - SP10
                    - SP30
                    - SP50
                    type: string
                required:
                - provider
                - region
                - tier
                type: object
              connectionRegistry:
                description: List of connections of the stream instance for the specified
                  project
                items:
                  description: ResourceRefNamespaced is a reference to a Kubernetes
                    Resource that allows to configure the namespace
                  properties:
                    name:
                      description: Name is the name of the Kubernetes Resource
                      type: string
                    namespace:
                      description: Namespace is the namespace of the Kubernetes Resource
                      type: string
                  required:
                  - name
                  type: object
                type: array
              name:
                description: Human-readable label that identifies the stream connection
                type: string
              projectRef:
                description: Project which the instance belongs to
                properties:
                  name:
                    description: Name is the name of the Kubernetes Resource
                    type: string
                  namespace:
                    description: Namespace is the namespace of the Kubernetes Resource
                    type: string
                required:
                - name
                type: object
            required:
            - clusterConfig
            - name
            - projectRef
            type: object
          status:
            properties:
              conditions:
                description: Conditions is the list of statuses showing the current
                  state of the Atlas Custom Resource
                items:
                  description: Condition describes the state of an Atlas Custom Resource
                    at a certain point.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of Atlas Custom Resource condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              connections:
                description: List of connections configured in the stream instance.
                items:
                  properties:
                    name:
                      description: Human-readable label that uniquely identifies the
                        stream connection
                      type: string
                    resourceRef:
                      description: Reference for the resource that contains connection
                        configuration
                      properties:
                        name:
                          description: Name is the name of the Kubernetes Resource
                          type: string
                        namespace:
                          description: Namespace is the namespace of the Kubernetes
                            Resource
                          type: string
                      required:
                      - name
                      type: object
                  type: object
                type: array
              hostnames:
                description: List that contains the hostnames assigned to the stream
                  instance.
                items:
                  type: string
                type: array
              id:
                description: Unique 24-hexadecimal character string that identifies
                  the instance
                type: string
              observedGeneration:
                description: |-
                  ObservedGeneration indicates the generation of the resource specification that the Atlas Operator is aware of.
                  The Atlas Operator updates this field to the 'metadata.generation' as soon as it starts reconciliation of the resource.
                format: int64
                type: integer
            required:
            - conditions
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
