apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "media.rm3l.org/v1alpha1",
          "kind": "Immich",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "immich-operator"
            },
            "name": "immich-sample"
          },
          "spec": {
            "immich": {
              "configuration": {
                "storageTemplate": {
                  "enabled": true,
                  "template": "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
                },
                "trash": {
                  "days": 30,
                  "enabled": true
                }
              },
              "configurationKind": "ConfigMap",
              "metrics": {
                "enabled": false
              },
              "persistence": {
                "library": {
                  "size": "100Gi"
                }
              }
            },
            "machineLearning": {
              "enabled": true,
              "persistence": {
                "enabled": true,
                "size": "10Gi"
              },
              "replicas": 1,
              "resources": {
                "limits": {
                  "memory": "4Gi"
                },
                "requests": {
                  "cpu": "100m",
                  "memory": "512Mi"
                }
              }
            },
            "postgres": {
              "enabled": true,
              "persistence": {
                "size": "10Gi"
              }
            },
            "server": {
              "enabled": true,
              "ingress": {
                "annotations": {
                  "nginx.ingress.kubernetes.io/proxy-body-size": "0"
                },
                "enabled": true,
                "hosts": [
                  {
                    "host": "immich.example.com",
                    "paths": [
                      {
                        "path": "/",
                        "pathType": "Prefix"
                      }
                    ]
                  }
                ],
                "ingressClassName": "nginx",
                "tls": [
                  {
                    "hosts": [
                      "immich.example.com"
                    ],
                    "secretName": "immich-tls"
                  }
                ]
              },
              "replicas": 1,
              "resources": {
                "limits": {
                  "memory": "2Gi"
                },
                "requests": {
                  "cpu": "100m",
                  "memory": "256Mi"
                }
              }
            },
            "valkey": {
              "enabled": true,
              "persistence": {
                "enabled": false,
                "size": "5Gi"
              },
              "resources": {
                "limits": {
                  "memory": "256Mi"
                },
                "requests": {
                  "cpu": "50m",
                  "memory": "64Mi"
                }
              }
            }
          }
        },
        {
          "apiVersion": "media.rm3l.org/v1alpha1",
          "kind": "Immich",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "immich-operator"
            },
            "name": "my-immich"
          },
          "spec": {
            "immich": {
              "configuration": {
                "storageTemplate": {
                  "enabled": true,
                  "template": "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
                },
                "trash": {
                  "days": 30,
                  "enabled": true
                }
              },
              "configurationKind": "ConfigMap",
              "metrics": {
                "enabled": false
              },
              "persistence": {
                "library": {
                  "existingClaim": "my-existing-pvc"
                }
              }
            },
            "machineLearning": {
              "enabled": true,
              "persistence": {
                "enabled": true,
                "size": "10Gi"
              },
              "replicas": 1,
              "resources": {
                "limits": {
                  "memory": "4Gi"
                },
                "requests": {
                  "cpu": "100m",
                  "memory": "512Mi"
                }
              }
            },
            "postgres": {
              "enabled": true,
              "persistence": {
                "size": "10Gi"
              }
            },
            "server": {
              "enabled": true,
              "ingress": {
                "annotations": {
                  "nginx.ingress.kubernetes.io/proxy-body-size": "0"
                },
                "enabled": true,
                "hosts": [
                  {
                    "host": "my-immich.example.com",
                    "paths": [
                      {
                        "path": "/",
                        "pathType": "Prefix"
                      }
                    ]
                  }
                ],
                "ingressClassName": "nginx",
                "tls": [
                  {
                    "hosts": [
                      "my-immich.example.com"
                    ],
                    "secretName": "immich-tls"
                  }
                ]
              },
              "replicas": 1,
              "resources": {
                "limits": {
                  "memory": "2Gi"
                },
                "requests": {
                  "cpu": "100m",
                  "memory": "256Mi"
                }
              }
            },
            "valkey": {
              "enabled": true,
              "persistence": {
                "enabled": false,
                "size": "5Gi"
              },
              "resources": {
                "limits": {
                  "memory": "256Mi"
                },
                "requests": {
                  "cpu": "50m",
                  "memory": "64Mi"
                }
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Application Runtime,AI/Machine Learning
    containerImage: ghcr.io/rm3l/immich-operator:0.1.0
    createdAt: "2026-01-05T08:06:11Z"
    description: |-
      An Operator for deploying and managing Immich,
      a self-hosted photo and video management solution.
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    repository: https://github.com/rm3l/immich-operator
    support: rm3l
  name: immich-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Immich is the Schema for the immiches API.
      displayName: Immich
      kind: Immich
      name: immiches.media.rm3l.org
      version: v1alpha1
  description: A Kubernetes Operator for deploying and managing Immich, a self-hosted
    photo and video management solution.
  displayName: Immich
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTguNTEgMjU4LjUxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2QxZDFkMTt9LmNscy0ye2ZpbGw6IzhkOGQ4Zjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkFzc2V0IDQ8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl8xLTIiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTI5LjI1LDIwQTEwOS4xLDEwOS4xLDAsMCwxLDIwNi40LDIwNi40LDEwOS4xLDEwOS4xLDAsMSwxLDUyLjExLDUyLjExLDEwOC40NSwxMDguNDUsMCwwLDEsMTI5LjI1LDIwbTAtMjBoMEM1OC4xNiwwLDAsNTguMTYsMCwxMjkuMjVIMGMwLDcxLjA5LDU4LjE2LDEyOS4yNiwxMjkuMjUsMTI5LjI2aDBjNzEuMDksMCwxMjkuMjYtNTguMTcsMTI5LjI2LTEyOS4yNmgwQzI1OC41MSw1OC4xNiwyMDAuMzQsMCwxMjkuMjUsMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzcuNTQsMTAzLjQxSDE0MS42NkwxNTQuOSw2NS43NmMxLjI1LTQuNC0yLjMzLTguNzYtNy4yMS04Ljc2SDEwMi45M2E3LjMyLDcuMzIsMCwwLDAtNy40LDZsLTEwLDY5LjYxYy0uNTksNC4xNywyLjg5LDcuODksNy40LDcuODloMzYuOUwxMTUuNTUsMTk3Yy0xLjEyLDQuNDEsMi40OCw4LjU1LDcuMjQsOC41NWE3LjU4LDcuNTgsMCwwLDAsNi40Ny0zLjQ4TDE4NCwxMTMuODVDMTg2Ljg2LDEwOS4yNCwxODMuMjksMTAzLjQxLDE3Ny41NCwxMDMuNDFaIi8+PC9nPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - persistentvolumeclaims
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - media.rm3l.org
          resources:
          - immiches
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - media.rm3l.org
          resources:
          - immiches/finalizers
          verbs:
          - update
        - apiGroups:
          - media.rm3l.org
          resources:
          - immiches/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: immich-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: immich-operator
          control-plane: controller-manager
        name: immich-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: immich-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: immich-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                env:
                - name: RELATED_IMAGE_immich
                  value: ghcr.io/immich-app/immich-server:v2.4.1
                - name: RELATED_IMAGE_machineLearning
                  value: ghcr.io/immich-app/immich-machine-learning:v2.4.1
                - name: RELATED_IMAGE_valkey
                  value: docker.io/valkey/valkey:9-alpine
                - name: RELATED_IMAGE_postgres
                  value: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
                - name: RELATED_IMAGE_immich_initContainer
                  value: docker.io/library/busybox:1.37
                image: ghcr.io/rm3l/immich-operator:0.1.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: immich-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: immich-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - album
  - ai/ml
  - immich
  - photo
  - self-hosting
  - video
  links:
  - name: Immich Operator
    url: https://github.com/rm3l/immich-operator
  maintainers:
  - email: armel@rm3l.org
    name: Armel Soro
  maturity: alpha
  minKubeVersion: 1.26.0
  provider:
    name: Armel Soro
    url: https://armel.rm3l.org
  relatedImages:
  - image: ghcr.io/immich-app/immich-server:v2.4.1
    name: immich
  - image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
    name: machinelearning
  - image: docker.io/valkey/valkey:9-alpine
    name: valkey
  - image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    name: postgres
  - image: docker.io/library/busybox:1.37
    name: immich-initcontainer
  version: 0.1.0
