apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  creationTimestamp: null
  name: nexusroles.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: NexusRole
    listKind: NexusRoleList
    plural: nexusroles
    singular: nexusrole
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NexusRole is the Schema for the nexusroles API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NexusRoleSpec defines the desired state of NexusRole.
            properties:
              description:
                description: Description of nexus role.
                example: Administrator role
                type: string
              id:
                description: |-
                  ID is the id of the role.
                  ID should be unique across all roles.
                example: nx-admin
                maxLength: 512
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              name:
                description: Name is the name of the role.
                example: nx-admin
                type: string
              nexusRef:
                description: NexusRef is a reference to Nexus custom resource.
                properties:
                  kind:
                    default: Nexus
                    description: Kind specifies the kind of the Nexus resource.
                    type: string
                  name:
                    description: Name specifies the name of the Nexus resource.
                    type: string
                required:
                - name
                type: object
              privileges:
                description: Privileges is a list of privileges assigned to role.
                example:
                - nx-all
                items:
                  type: string
                nullable: true
                type: array
            required:
            - id
            - name
            - nexusRef
            type: object
          status:
            description: NexusRoleStatus defines the observed state of NexusRole.
            properties:
              error:
                description: Error is an error message if something went wrong.
                type: string
              value:
                description: Value is a status of the role.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
