apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  creationTimestamp: null
  name: nexuscleanuppolicies.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: NexusCleanupPolicy
    listKind: NexusCleanupPolicyList
    plural: nexuscleanuppolicies
    singular: nexuscleanuppolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NexusCleanupPolicy is the Schema for the cleanuppolicies API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NexusCleanupPolicySpec defines the desired state of NexusCleanupPolicy.
            properties:
              criteria:
                description: Criteria for the cleanup policy.
                properties:
                  assetRegex:
                    description: AssetRegex removes components that match the given
                      regex.
                    example: .*
                    type: string
                  lastBlobUpdated:
                    description: LastBlobUpdated removes components published over
                      “x” days ago.
                    example: "30"
                    maximum: 24855
                    minimum: 1
                    type: integer
                  lastDownloaded:
                    description: LastDownloaded removes components downloaded over
                      “x” days.
                    example: "30"
                    maximum: 24855
                    minimum: 1
                    type: integer
                  releaseType:
                    description: ReleaseType removes components that are of the following
                      release type.
                    enum:
                    - RELEASES
                    - PRERELEASES
                    - ""
                    example: RELEASES
                    type: string
                type: object
              description:
                description: Description of the cleanup policy.
                example: Cleanup policy for go format
                type: string
              format:
                description: Format that this cleanup policy can be applied to.
                enum:
                - apt
                - bower
                - cocoapods
                - conan
                - conda
                - docker
                - gitlfs
                - go
                - helm
                - maven2
                - npm
                - nuget
                - p2
                - pypi
                - r
                - raw
                - rubygems
                - yum
                example: go
                type: string
              name:
                description: Name is a unique name for the cleanup policy.
                example: go-cleanup-policy
                maxLength: 512
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              nexusRef:
                description: NexusRef is a reference to Nexus custom resource.
                properties:
                  kind:
                    default: Nexus
                    description: Kind specifies the kind of the Nexus resource.
                    type: string
                  name:
                    description: Name specifies the name of the Nexus resource.
                    type: string
                required:
                - name
                type: object
            required:
            - criteria
            - format
            - name
            - nexusRef
            type: object
          status:
            description: NexusCleanupPolicyStatus defines the observed state of NexusCleanupPolicy.
            properties:
              error:
                description: Error is an error message if something went wrong.
                type: string
              value:
                description: Value is a status of the cleanup policy.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
