apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "registry.apicur.io/v1",
          "kind": "ApicurioRegistry3",
          "metadata": {
            "name": "simple"
          },
          "spec": {
            "app": {
              "ingress": {
                "host": "simple-app.apps.cluster.example"
              }
            },
            "ui": {
              "ingress": {
                "host": "simple-ui.apps.cluster.example"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Streaming & Messaging
    certified: "false"
    containerImage: quay.io/apicurio/apicurio-registry-3-operator:3.0.7
    createdAt: "2025-04-25T10:44:51Z"
    description: Deploy and manage Apicurio Registry 3 on Kubernetes.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/infrastructure-features: '[]'
    operators.operatorframework.io/builder: operator-sdk-v1.37.0
    operators.operatorframework.io/project_layout: unknown
    repository: https://github.com/Apicurio/apicurio-registry/tree/main/operator
    support: Apicurio
  name: apicurio-registry-3.v3.0.7
  namespace: PLACEHOLDER_NAMESPACE
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ApicurioRegistry3 represents an instance of Apicurio Registry version
        3.
      displayName: Apicurio Registry 3
      kind: ApicurioRegistry3
      name: apicurioregistries3.registry.apicur.io
      version: v1
  description: |
    ## Apicurio Registry 3

    Apicurio Registry stores and retrieves API designs and event schemas,
    and gives you control of their evolution.

    **Features**
    - Supports: Apache Avro, AsyncAPI, GraphQL, JSON Schema, Kafka Connect Schema, OpenAPI, Protobuf
    - Allows you manage event schemas and API designs using the Apicurio Registry web console, REST API, Maven plug-in, or Java client
    - Includes Serializers and Deserializers for Kafka client integration
    - Configurable rules to control schema validity and evolution (compatibility)
    - Storage options: Kafka, PostgreSQL, MySQL, SQL Server, in-memory
    - Compatible with Confluent APIs
    - Runs on a lightweight Quarkus platform

    ## Apicurio Registry 3 Operator

    Provides a quick and easy way to deploy and manage Apicurio Registry 3 on Kubernetes.

    **Features**
    - Supports installation and configuration of Apicurio Registry 3
    - Perform a rolling upgrade of Apicurio Registry 3

    ## Prerequisites

    This operator does not deploy storage for Apicurio Registry 3. Therefore, some storage options require that the chosen persistence service is already set up.

    ## License

    Apicurio Registry 3 and Apicurio Registry 3 Operator are licensed under the [Apache 2.0 license](https://github.com/Apicurio/apicurio-registry/blob/main/LICENSE)
  displayName: Apicurio Registry 3
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMTAyNCAxMDI0Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2MwMDt9PC9zdHlsZT48L2RlZnM+PHBhdGggZD0ibTQ2Niw2MTEuOTdjLS40NSwwLS44Ny4xMS0xLjMyLjEzdi0uMTNjLTU3LjI2LTMuNzctMTA3LTY0LjItMTA3LjA2LTEwOC41Ljk2LTM0LjMxLDMuMDItNzUuNDYsNC44Ny04Mi4xOCwzMS44Ny0xNzguMjQsMTY1LjYzLTMyMS4xNSwzMzguOTYtMzY2LjEyLTYyLjAyLTMxLjk5LTEzMi4yOC01MC4xNy0yMDYuNzQtNTAuMTdDMjQ1LjA5LDUsNDIuMDIsMjA4LjA3LDQyLjAyLDQ1Ny42OXY0MDMuNjFjMCw4Ny4xLDcwLjYxLDE1Ny43LDE1Ny43MSwxNTcuN3MxNTcuNzEtNzAuNjEsMTU3LjcxLTE1Ny43di04NC4zNGMwLTYxLjEyLDQ3LjEzLTExMSwxMDcuMjUtMTE0Ljk2di0uMTRjLjQ1LjAyLjg3LjEzLDEuMzIuMTMsMTMuODEsMCwyNS4wMS0xMS4yLDI1LjAxLTI1LjAxcy0xMS4yLTI1LjAxLTI1LjAxLTI1LjAxWiIvPjxnPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0ibTg0OS4xMSwyMjMuNzZjMjQsMCw0Ny41OCwxLjgyLDcwLjYyLDUuMjYtMjguNzQtNDguODMtNjYuMzQtOTEuODUtMTEwLjYyLTEyNi43OC0xNjEuNzgsMTUuMDgtMjk5LjMsMTEzLjQxLTM2OS40NywyNTEuNzMsMjQuMDgtMjAuODQsNTUuMzgtMzMuNTUsODkuNjUtMzMuNTUsOS44NywwLDE5LjQ4LDEuMSwyOC43NywzLjA5LDgwLjQtNjIuNDcsMTgxLjM0LTk5Ljc0LDI5MS4wNC05OS43NFoiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Im05NTkuMTksMzE1Ljg1Yy00MC40OC0xMS4yMi04My4wOC0xNy4zNS0xMjcuMTQtMTcuMzUtNzguMTIsMC0xNTEuNzksMTguOTItMjE2Ljc5LDUyLjMzLDMxLjI0LDI1LjE4LDUxLjMsNjMuNyw1MS4zLDEwNi44NnY0NS43NmMtLjA0LDQ0LjMtNDkuOCwxMDQuNzUtMTA3LjA2LDEwOC41MnYuMTNjLS40NS0uMDItLjg3LS4xMy0xLjMyLS4xMy0xMy44MSwwLTI1LjAxLDExLjItMjUuMDEsMjUuMDFzMTEuMiwyNS4wMSwyNS4wMSwyNS4wMWMuNDUsMCwuODctLjExLDEuMzItLjEzdi4xNGM1OC4wMywzLjgyLDEwMy45NSw1MC40NCwxMDcuMDYsMTA4LjY0djkwLjY1YzAsODcuMSw3MC42MSwxNTcuNywxNTcuNzEsMTU3LjdzMTU3LjcxLTcwLjYxLDE1Ny43MS0xNTcuN3YtNDAzLjYxYzAtNDkuNTMtOC4wMS05Ny4yMS0yMi43OS0xNDEuODRaIi8+PC9nPjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - registry.apicur.io
          resources:
          - apicurioregistries3
          - apicurioregistries3/status
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - events.k8s.io
          resources:
          - events
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          - networkpolicies
          verbs:
          - '*'
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - list
          - get
          - create
        serviceAccountName: apicurio-registry-operator
      deployments:
      - label:
          app: apicurio-registry-operator
          app.kubernetes.io/component: operator
          app.kubernetes.io/name: apicurio-registry-operator
          app.kubernetes.io/part-of: apicurio-registry
          app.kubernetes.io/version: 3.0.7
        name: apicurio-registry-operator-v3.0.7
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: apicurio-registry-operator
              app.kubernetes.io/component: operator
              app.kubernetes.io/name: apicurio-registry-operator
              app.kubernetes.io/part-of: apicurio-registry
              app.kubernetes.io/version: 3.0.7
          strategy: {}
          template:
            metadata:
              labels:
                app: apicurio-registry-operator
                app.kubernetes.io/component: operator
                app.kubernetes.io/name: apicurio-registry-operator
                app.kubernetes.io/part-of: apicurio-registry
                app.kubernetes.io/version: 3.0.7
            spec:
              containers:
              - env:
                - name: APICURIO_OPERATOR_WATCHED_NAMESPACES
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: QUARKUS_PROFILE
                  value: prod
                - name: REGISTRY_APP_IMAGE
                  value: quay.io/apicurio/apicurio-registry:3.0.7
                - name: REGISTRY_UI_IMAGE
                  value: quay.io/apicurio/apicurio-registry-ui:3.0.7
                image: quay.io/apicurio/apicurio-registry-3-operator:3.0.7
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /q/health/live
                    port: 8080
                name: apicurio-registry-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                resources:
                  limits:
                    cpu: 200m
                    memory: 500Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
                startupProbe:
                  failureThreshold: 6
                  httpGet:
                    path: /q/health/started
                    port: 8080
              serviceAccountName: apicurio-registry-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - integration
  - streaming
  - messaging
  - api
  - schemas
  - registry
  - apicurio
  - apicurio-registry
  links:
  - name: Website
    url: https://www.apicur.io/
  - name: GitHub
    url: https://github.com/Apicurio/apicurio-registry/
  - name: Issues
    url: https://github.com/Apicurio/apicurio-registry/issues
  maintainers:
  - email: apicurio@lists.jboss.org
    name: Apicurio
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: Apicurio
  selector: {}
  version: 3.0.7
