apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sn-operator-pulsarfunctionsworker-viewer-role
rules:
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarfunctionsworkers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarfunctionsworkers/status
  verbs:
  - get
