apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kmm-hub
    app.kubernetes.io/created-by: kernel-module-management
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kmm-hub
    app.kubernetes.io/part-of: kmm
  name: kmm-operator-hub-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/component: kmm-hub
    app.kubernetes.io/name: kmm-hub
    app.kubernetes.io/part-of: kmm
    control-plane: webhook-server
status:
  loadBalancer: {}
