# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: ethernetclusterconfigs.ethernet.intel.com
spec:
  group: ethernet.intel.com
  names:
    kind: EthernetClusterConfig
    listKind: EthernetClusterConfigList
    plural: ethernetclusterconfigs
    shortNames:
    - ecc
    singular: ethernetclusterconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: EthernetClusterConfig is the Schema for the ethernetclusterconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EthernetClusterConfigSpec defines the desired state of EthernetClusterConfig
            properties:
              deviceConfig:
                description: Contains configuration which will be applied to selected devices
                properties:
                  ddpChecksum:
                    description: SHA-1 checksum of .zip DDP package
                    pattern: ^[a-fA-F0-9]{40}$
                    type: string
                  ddpURL:
                    description: Path to .zip DDP package to be applied
                    pattern: '[a-zA-Z0-9\.\-\/]+'
                    type: string
                  fwChecksum:
                    description: SHA-1 checksum of .tar.gz Firmware
                    pattern: ^[a-fA-F0-9]{40}$
                    type: string
                  fwURL:
                    description: Path to .tar.gz Firmware (NVMUpdate package) to be applied
                    pattern: '[a-zA-Z0-9\.\-\/]+'
                    type: string
                type: object
              deviceSelector:
                description: Selector for devices on nodes. If value is not set, then configuration is applied to all CLV cards on selected nodes
                properties:
                  deviceId:
                    description: DeviceId of devices to be selected. If value is not set, then CLV cards with any DeviceId are selected
                    type: string
                  pciAddress:
                    description: PciAdress of devices to be selected. If value is not set, then CLV cards with any PciAddress are selected
                    pattern: ^[a-fA-F0-9]{4}:[a-fA-F0-9]{2}:[01][a-fA-F0-9]\.[0-7]$
                    type: string
                  vendorId:
                    description: VendorId of devices to be selected. If value is not set, then CLV cards with any VendorId are selected
                    type: string
                type: object
              nodeSelectors:
                additionalProperties:
                  type: string
                description: Selector for nodes. If value is not set, then configuration is applied to all nodes with CLV cards in cluster
                type: object
              priority:
                description: Higher priority policies can override lower ones. If several ClusterConfigs have same Priority, then operator will apply ClusterConfig with highest CreationTimestamp (newest one)
                type: integer
            required:
            - deviceConfig
            type: object
          status:
            description: EthernetClusterConfigStatus defines the observed state of EthernetClusterConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
