# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: nodeflowconfigs.flowconfig.intel.com
spec:
  group: flowconfig.intel.com
  names:
    kind: NodeFlowConfig
    listKind: NodeFlowConfigList
    plural: nodeflowconfigs
    singular: nodeflowconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: NodeFlowConfig is the Schema for the nodeflowconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NodeFlowConfigSpec defines the desired state of NodeFlowConfig
            properties:
              rules:
                description: Rules is a list of FlowCreate rules
                items:
                  description: FlowRules struct for flow rules creation and validation
                  properties:
                    action:
                      items:
                        description: FlowAction defines flow actions
                        properties:
                          conf:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          type:
                            type: string
                        type: object
                      type: array
                    attr:
                      description: FlowAttr defines Flow rule attributes
                      properties:
                        egress:
                          format: int32
                          type: integer
                        group:
                          format: int32
                          type: integer
                        ingress:
                          format: int32
                          type: integer
                        priority:
                          format: int32
                          type: integer
                        reserved:
                          format: int32
                          type: integer
                        transfer:
                          format: int32
                          type: integer
                      type: object
                    pattern:
                      items:
                        description: FlowItem defines flow pattern definition
                        properties:
                          last:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          mask:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          spec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          type:
                            type: string
                        type: object
                      type: array
                    portId:
                      format: int32
                      type: integer
                  type: object
                type: array
            type: object
          status:
            description: NodeFlowConfigStatus defines the observed state of NodeFlowConfig
            properties:
              portInfo:
                items:
                  description: PortsInformation defines port information
                  properties:
                    portId:
                      format: int32
                      type: integer
                    portMode:
                      type: string
                    portPci:
                      type: string
                  required:
                  - portId
                  type: object
                type: array
              rules:
                description: Last applied rules
                items:
                  description: FlowRules struct for flow rules creation and validation
                  properties:
                    action:
                      items:
                        description: FlowAction defines flow actions
                        properties:
                          conf:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          type:
                            type: string
                        type: object
                      type: array
                    attr:
                      description: FlowAttr defines Flow rule attributes
                      properties:
                        egress:
                          format: int32
                          type: integer
                        group:
                          format: int32
                          type: integer
                        ingress:
                          format: int32
                          type: integer
                        priority:
                          format: int32
                          type: integer
                        reserved:
                          format: int32
                          type: integer
                        transfer:
                          format: int32
                          type: integer
                      type: object
                    pattern:
                      items:
                        description: FlowItem defines flow pattern definition
                        properties:
                          last:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          mask:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          spec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          type:
                            type: string
                        type: object
                      type: array
                    portId:
                      format: int32
                      type: integer
                  type: object
                type: array
              syncMsg:
                type: string
              syncStatus:
                type: string
            required:
            - portInfo
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
