# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: intel-ethernet-operator-flowconfignodeagentdeployment-viewer-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments/status
  verbs:
  - get
