# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: intel-ethernet-operator-nodeflowconfig-editor-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - nodeflowconfigs/status
  verbs:
  - get
