apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 0.10.1
  name: dynatrace-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: server-port
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 0.10.1
status:
  loadBalancer: {}
