apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.2
  creationTimestamp: null
  name: patchbaselines.ssm.services.k8s.aws
spec:
  group: ssm.services.k8s.aws
  names:
    kind: PatchBaseline
    listKind: PatchBaselineList
    plural: patchbaselines
    singular: patchbaseline
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PatchBaseline is the Schema for the PatchBaselines API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PatchBaselineSpec defines the desired state of PatchBaseline.
            properties:
              approvalRules:
                description: A set of rules used to include patches in the baseline.
                properties:
                  patchRules:
                    items:
                      description: Defines an approval rule for a patch baseline.
                      properties:
                        approveAfterDays:
                          format: int64
                          type: integer
                        approveUntilDate:
                          type: string
                        complianceLevel:
                          type: string
                        enableNonSecurity:
                          type: boolean
                        patchFilterGroup:
                          description: A set of patch filters, typically used for
                            approval rules.
                          properties:
                            patchFilters:
                              items:
                                description: |-
                                  Defines which patches should be included in a patch baseline.

                                  A patch filter consists of a key and a set of values. The filter key is a
                                  patch property. For example, the available filter keys for WINDOWS are PATCH_SET,
                                  PRODUCT, PRODUCT_FAMILY, CLASSIFICATION, and MSRC_SEVERITY.

                                  The filter values define a matching criterion for the patch property indicated
                                  by the key. For example, if the filter key is PRODUCT and the filter values
                                  are ["Office 2013", "Office 2016"], then the filter accepts all patches where
                                  product name is either "Office 2013" or "Office 2016". The filter values
                                  can be exact values for the patch property given as a key, or a wildcard
                                  (*), which matches all values.

                                  You can view lists of valid values for the patch properties by running the
                                  DescribePatchProperties command. For information about which patch properties
                                  can be used with each major operating system, see DescribePatchProperties.
                                properties:
                                  key:
                                    type: string
                                  values:
                                    items:
                                      type: string
                                    type: array
                                type: object
                              type: array
                          type: object
                      type: object
                    type: array
                type: object
              approvedPatches:
                description: |-
                  A list of explicitly approved patches for the baseline.

                  For information about accepted formats for lists of approved patches and
                  rejected patches, see Package name formats for approved and rejected patch
                  lists (https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-approved-rejected-package-name-formats.html)
                  in the Amazon Web Services Systems Manager User Guide.
                items:
                  type: string
                type: array
              approvedPatchesComplianceLevel:
                description: |-
                  Defines the compliance level for approved patches. When an approved patch
                  is reported as missing, this value describes the severity of the compliance
                  violation. The default value is UNSPECIFIED.
                type: string
              approvedPatchesEnableNonSecurity:
                description: |-
                  Indicates whether the list of approved patches includes non-security updates
                  that should be applied to the managed nodes. The default value is false.
                  Applies to Linux managed nodes only.
                type: boolean
              clientToken:
                description: User-provided idempotency token.
                type: string
              description:
                description: A description of the patch baseline.
                type: string
              globalFilters:
                description: |-
                  A set of global filters used to include patches in the baseline.

                  The GlobalFilters parameter can be configured only by using the CLI or an
                  Amazon Web Services SDK. It can't be configured from the Patch Manager console,
                  and its value isn't displayed in the console.
                properties:
                  patchFilters:
                    items:
                      description: |-
                        Defines which patches should be included in a patch baseline.

                        A patch filter consists of a key and a set of values. The filter key is a
                        patch property. For example, the available filter keys for WINDOWS are PATCH_SET,
                        PRODUCT, PRODUCT_FAMILY, CLASSIFICATION, and MSRC_SEVERITY.

                        The filter values define a matching criterion for the patch property indicated
                        by the key. For example, if the filter key is PRODUCT and the filter values
                        are ["Office 2013", "Office 2016"], then the filter accepts all patches where
                        product name is either "Office 2013" or "Office 2016". The filter values
                        can be exact values for the patch property given as a key, or a wildcard
                        (*), which matches all values.

                        You can view lists of valid values for the patch properties by running the
                        DescribePatchProperties command. For information about which patch properties
                        can be used with each major operating system, see DescribePatchProperties.
                      properties:
                        key:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                type: object
              name:
                description: The name of the patch baseline.
                type: string
              operatingSystem:
                description: |-
                  Defines the operating system the patch baseline applies to. The default value
                  is WINDOWS.
                type: string
              rejectedPatches:
                description: |-
                  A list of explicitly rejected patches for the baseline.

                  For information about accepted formats for lists of approved patches and
                  rejected patches, see Package name formats for approved and rejected patch
                  lists (https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-approved-rejected-package-name-formats.html)
                  in the Amazon Web Services Systems Manager User Guide.
                items:
                  type: string
                type: array
              rejectedPatchesAction:
                description: |-
                  The action for Patch Manager to take on patches included in the RejectedPackages
                  list.

                  ALLOW_AS_DEPENDENCY

                  Linux and macOS: A package in the rejected patches list is installed only
                  if it is a dependency of another package. It is considered compliant with
                  the patch baseline, and its status is reported as INSTALLED_OTHER. This is
                  the default action if no option is specified.

                  Windows Server: Windows Server doesn't support the concept of package dependencies.
                  If a package in the rejected patches list and already installed on the node,
                  its status is reported as INSTALLED_OTHER. Any package not already installed
                  on the node is skipped. This is the default action if no option is specified.

                  BLOCK

                  All OSs: Packages in the rejected patches list, and packages that include
                  them as dependencies, aren't installed by Patch Manager under any circumstances.
                  If a package was installed before it was added to the rejected patches list,
                  or is installed outside of Patch Manager afterward, it's considered noncompliant
                  with the patch baseline and its status is reported as INSTALLED_REJECTED.
                type: string
              sources:
                description: |-
                  Information about the patches to use to update the managed nodes, including
                  target operating systems and source repositories. Applies to Linux managed
                  nodes only.
                items:
                  description: |-
                    Information about the patches to use to update the managed nodes, including
                    target operating systems and source repository. Applies to Linux managed
                    nodes only.
                  properties:
                    configuration:
                      type: string
                    name:
                      type: string
                    products:
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              tags:
                description: |-
                  Optional metadata that you assign to a resource. Tags enable you to categorize
                  a resource in different ways, such as by purpose, owner, or environment.
                  For example, you might want to tag a patch baseline to identify the severity
                  level of patches it specifies and the operating system family it applies
                  to. In this case, you could specify the following key-value pairs:

                     * Key=PatchSeverity,Value=Critical

                     * Key=OS,Value=Windows

                  To add tags to an existing patch baseline, use the AddTagsToResource operation.
                items:
                  description: |-
                    Metadata that you assign to your Amazon Web Services resources. Tags enable
                    you to categorize your resources in different ways, for example, by purpose,
                    owner, or environment. In Amazon Web Services Systems Manager, you can apply
                    tags to Systems Manager documents (SSM documents), managed nodes, maintenance
                    windows, parameters, patch baselines, OpsItems, and OpsMetadata.
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            required:
            - name
            type: object
          status:
            description: PatchBaselineStatus defines the observed state of PatchBaseline
            properties:
              ackResourceMetadata:
                description: |-
                  All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
                  that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: |-
                      ARN is the Amazon Resource Name for the resource. This is a
                      globally-unique identifier and is set only by the ACK service controller
                      once the controller has orchestrated the creation of the resource OR
                      when it has verified that an "adopted" resource (a resource where the
                      ARN annotation was set by the Kubernetes user on the CR) exists and
                      matches the supplied CR's Spec field values.
                      https://github.com/aws/aws-controllers-k8s/issues/270
                    type: string
                  ownerAccountID:
                    description: |-
                      OwnerAccountID is the AWS Account ID of the account that owns the
                      backend AWS service API resource.
                    type: string
                  region:
                    description: Region is the AWS region in which the resource exists
                      or will exist.
                    type: string
                required:
                - ownerAccountID
                - region
                type: object
              baselineID:
                description: The ID of the created patch baseline.
                type: string
              conditions:
                description: |-
                  All CRs managed by ACK have a common `Status.Conditions` member that
                  contains a collection of `ackv1alpha1.Condition` objects that describe
                  the various terminal states of the CR and its backend AWS service API
                  resource
                items:
                  description: |-
                    Condition is the common struct used by all CRDs managed by ACK service
                    controllers to indicate terminal states  of the CR and its backend AWS
                    service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
