apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: mongodb-atlas-kubernetes-operator
    app.kubernetes.io/name: mongodb-atlas-kubernetes-operator
  name: atlascustomroles.atlas.mongodb.com
spec:
  group: atlas.mongodb.com
  names:
    categories:
    - atlas
    kind: AtlasCustomRole
    listKind: AtlasCustomRoleList
    plural: atlascustomroles
    shortNames:
    - acr
    singular: atlascustomrole
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .spec.role.name
      name: Name
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: AtlasCustomRole is the Schema for the AtlasCustomRole API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: AtlasCustomRoleSpec defines the desired state of CustomRole
              in Atlas
            properties:
              connectionSecret:
                description: Name of the secret containing Atlas API private and public
                  keys
                properties:
                  name:
                    description: |-
                      Name of the resource being referred to
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                required:
                - name
                type: object
              externalProjectRef:
                description: Optional ID of the Atlas Project this role is attached
                  to. Mutually exclusive with "projectRef" field
                properties:
                  id:
                    description: ID is the Atlas project ID
                    type: string
                required:
                - id
                type: object
              projectRef:
                description: Optional reference to an AtlasProject custom resource.
                  Mutually exclusive with "externalProjectRef" field
                properties:
                  name:
                    description: Name is the name of the Kubernetes Resource
                    type: string
                  namespace:
                    description: Namespace is the namespace of the Kubernetes Resource
                    type: string
                required:
                - name
                type: object
              role:
                properties:
                  actions:
                    description: List of the individual privilege actions that the
                      role grants.
                    items:
                      properties:
                        name:
                          description: Human-readable label that identifies the privilege
                            action.
                          type: string
                        resources:
                          description: List of resources on which you grant the action.
                          items:
                            properties:
                              cluster:
                                description: Flag that indicates whether to grant
                                  the action on the cluster resource. If true, MongoDB
                                  Cloud ignores Database and Collection parameters.
                                type: boolean
                              collection:
                                description: Human-readable label that identifies
                                  the collection on which you grant the action to
                                  one MongoDB user.
                                type: string
                              database:
                                description: Human-readable label that identifies
                                  the database on which you grant the action to one
                                  MongoDB user.
                                type: string
                            type: object
                          type: array
                      required:
                      - name
                      - resources
                      type: object
                    type: array
                  inheritedRoles:
                    description: List of the built-in roles that this custom role
                      inherits.
                    items:
                      properties:
                        database:
                          description: Human-readable label that identifies the database
                            on which someone grants the action to one MongoDB user.
                          type: string
                        name:
                          description: Human-readable label that identifies the role
                            inherited.
                          type: string
                      required:
                      - database
                      - name
                      type: object
                    type: array
                  name:
                    description: Human-readable label that identifies the role. This
                      name must be unique for this custom role in this project.
                    type: string
                required:
                - name
                type: object
            required:
            - role
            type: object
            x-kubernetes-validations:
            - message: must define only one project reference through externalProjectRef
                or projectRef
              rule: (has(self.externalProjectRef) && !has(self.projectRef)) || (!has(self.externalProjectRef)
                && has(self.projectRef))
            - message: must define a local connection secret when referencing an external
                project
              rule: (has(self.externalProjectRef) && has(self.connectionSecret)) ||
                !has(self.externalProjectRef)
          status:
            description: |-
              AtlasCustomRoleStatus is a status for the AtlasCustomRole Custom resource.
              Not the one included in the AtlasProject
            properties:
              conditions:
                description: Conditions is the list of statuses showing the current
                  state of the Atlas Custom Resource
                items:
                  description: Condition describes the state of an Atlas Custom Resource
                    at a certain point.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of Atlas Custom Resource condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: |-
                  ObservedGeneration indicates the generation of the resource specification that the Atlas Operator is aware of.
                  The Atlas Operator updates this field to the 'metadata.generation' as soon as it starts reconciliation of the resource.
                format: int64
                type: integer
            required:
            - conditions
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
