apiVersion: v1
data:
  defaultConfig: |-
    match:
      name: ".*-auto-recovery-config"
      groupVersionKinds:
      - kind: ConfigMap
    manifest: |-
      #! template=true
      data:
        {{ defaultConfig .origin.data "lostBookieRecoveryDelay" "600" }}
  defaultJVMOptions: |-
    match:
      name: ".*-auto-recovery-config"
      groupVersionKinds:
      - kind: ConfigMap
    manifest: |-
      #! template=true
      {{- if not .owner.spec.autoRecovery.pod.jvmOptions }}
      {{- $mem := 0 }}
      {{- with .owner.spec.autoRecovery.pod.resources }}
      {{- if .limits.memory }}
      {{ $mem = parseMemoryMiB .limits.memory }}
      {{- else if .requests.memory }}
      {{ $mem = parseMemoryMiB .requests.memory }}
      {{- end }}
      {{- end }}
      {{- if eq $mem 0 }}
      {{ $mem = parseMemoryMiB "1.5Gi" }}
      {{- end }}
      {{- if gt $mem 0 }}
      {{- $heapSize := mulf $mem 0.3 | int64 }}
      {{- $directMem := mulf $mem 0.66 | int64 }}
      data:
        BOOKIE_MEM: "-Xms{{ $heapSize }}m -Xmx{{ $heapSize }}m -XX:MaxDirectMemorySize={{ $directMem }}m"
      {{- end }}
      {{- end }}
  defaultResources: |-
    match:
      name: ".*-auto-recovery"
      groupVersionKinds:
      - kind: StatefulSet
    manifest: |-
      #! template=true
      {{- if not .owner.spec.autoRecovery.pod.resources }}
      spec:
        template:
          spec:
            initContainers:
            - name: sysctl-init
              resources:
                requests:
                  cpu: 100m
                  memory: 1.2Gi
                limits:
                  cpu: 1
                  memory: 1.5Gi
            containers:
            - name: bookie-recovery
              resources:
                requests:
                  cpu: 100m
                  memory: 1.2Gi
                limits:
                  cpu: 1
                  memory: 1.5Gi
      {{- end }}
  prometheusAnnotations: |-
    match:
      name: ".*-auto-recovery"
      groupVersionKinds:
      - kind: StatefulSet
    manifest: |-
      #! template=true
      {{- if index .origin.spec.template.metadata.annotations "prometheus.io/port" | not }}
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/port: "8000"
              prometheus.io/scrape: "true"
      {{- end }}
kind: ConfigMap
metadata:
  labels:
    cloud.streamnative.io/customization-kind: BookKeeperCluster
  name: bookkeeper-operator-autorecovery-default-config
