apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "m4e.krestomat.io/v1alpha1",
          "kind": "Moodle",
          "metadata": {
            "name": "moodle-sample"
          },
          "spec": {
            "moodleNewAdminpassHash": "$2b$10$zbRuwPil1wNWQUkvlkchwe3/rOljJvoheydndKH1X0bdIIigy0xim",
            "moodleNewInstanceAdminmail": "admin@example.com",
            "moodleNewInstanceAdminuser": "admin",
            "moodleNewInstanceAgreeLicense": true,
            "moodleNewInstanceFullname": "Demo site",
            "moodleNewInstanceShortname": "demo",
            "moodleNewInstanceSummary": "A demo site",
            "nginxExtraConfig": "# This passes 404 pages to Moodle so they can be themed\nerror_page 404 /error/index.php;    error_page 403 =404 /error/index.php;",
            "phpFpmExtraConfig": "[global]\nlog_level = debug\nemergency_restart_threshold = 10\nemergency_restart_interval = 1m\n[www]\npm = static\npm.max_children = 20\nsecurity.limit_extensions = .php",
            "phpFpmPhpExtraIni": "upload_max_filesize = 10M\npost_max_size = 10M"
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Application Runtime
    containerImage: quay.io/krestomatio/moodle-operator:0.6.31
    createdAt: "2025-06-30T22:56:21Z"
    description: |-
      This operator simplifies Moodle deployments in Kubernetes by leveraging
      the Ansible Operator SDK for automation
    operators.operatorframework.io/builder: operator-sdk-v1.39.1
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
    repository: https://github.com/krestomatio/moodle-operator
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/os.linux: supported
  name: moodle-operator.v0.6.31
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Moodle
      name: moodles.m4e.krestomat.io
      version: v1alpha1
    - kind: Nginx
      name: nginxes.m4e.krestomat.io
      version: v1alpha1
    - kind: Phpfpm
      name: phpfpms.m4e.krestomat.io
      version: v1alpha1
    - kind: Routine
      name: routines.m4e.krestomat.io
      version: v1alpha1
  description: |-
    This operator simplifies Moodle deployments in Kubernetes by leveraging
    the Ansible Operator SDK for automation
  displayName: Moodle Operator
  icon:
  - base64data: |-
      PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcK
      ICAgdmVyc2lvbj0iMS4xIgogICBpZD0iTGF5ZXJfMSIKICAgeD0iMHB4IgogICB5PSIwcHgiCiAgIHZp
      ZXdCb3g9IjAgMCAxMDAwIDk5OS45OTk5NyIKICAgeG1sOnNwYWNlPSJwcmVzZXJ2ZSIKICAgc29kaXBv
      ZGk6ZG9jbmFtZT0ibG9nb19pY29uX3NxdWFyZS5zdmciCiAgIGlua3NjYXBlOnZlcnNpb249IjEuMy4y
      ICgwOTFlMjBlZjBmLCAyMDIzLTExLTI1KSIKICAgd2lkdGg9IjEwMDAiCiAgIGhlaWdodD0iMTAwMCIK
      ICAgeG1sbnM6aW5rc2NhcGU9Imh0dHA6Ly93d3cuaW5rc2NhcGUub3JnL25hbWVzcGFjZXMvaW5rc2Nh
      cGUiCiAgIHhtbG5zOnNvZGlwb2RpPSJodHRwOi8vc29kaXBvZGkuc291cmNlZm9yZ2UubmV0L0RURC9z
      b2RpcG9kaS0wLmR0ZCIKICAgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxu
      czpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cu
      dzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOmNjPSJodHRwOi8vY3JlYXRp
      dmVjb21tb25zLm9yZy9ucyMiCiAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMv
      MS4xLyI+PG1ldGFkYXRhCiAgIGlkPSJtZXRhZGF0YTExMyI+PHJkZjpSREY+PGNjOldvcmsKICAgICAg
      IHJkZjphYm91dD0iIj48ZGM6Zm9ybWF0PmltYWdlL3N2Zyt4bWw8L2RjOmZvcm1hdD48ZGM6dHlwZQog
      ICAgICAgICByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdl
      IiAvPjwvY2M6V29yaz48L3JkZjpSREY+PC9tZXRhZGF0YT48ZGVmcwogICBpZD0iZGVmczExMSIgLz48
      c29kaXBvZGk6bmFtZWR2aWV3CiAgIHBhZ2Vjb2xvcj0iI2ZmZmZmZiIKICAgYm9yZGVyY29sb3I9IiM2
      NjY2NjYiCiAgIGJvcmRlcm9wYWNpdHk9IjEiCiAgIG9iamVjdHRvbGVyYW5jZT0iMTAiCiAgIGdyaWR0
      b2xlcmFuY2U9IjEwIgogICBndWlkZXRvbGVyYW5jZT0iMTAiCiAgIGlua3NjYXBlOnBhZ2VvcGFjaXR5
      PSIwIgogICBpbmtzY2FwZTpwYWdlc2hhZG93PSIyIgogICBpbmtzY2FwZTp3aW5kb3ctd2lkdGg9IjE5
      MjAiCiAgIGlua3NjYXBlOndpbmRvdy1oZWlnaHQ9IjExMTUiCiAgIGlkPSJuYW1lZHZpZXcxMDkiCiAg
      IHNob3dncmlkPSJmYWxzZSIKICAgaW5rc2NhcGU6em9vbT0iMC41MDA4Nzc4NCIKICAgaW5rc2NhcGU6
      Y3g9IjIyMy42MDc0MiIKICAgaW5rc2NhcGU6Y3k9IjU1OC4wMjAyOSIKICAgaW5rc2NhcGU6d2luZG93
      LXg9IjAiCiAgIGlua3NjYXBlOndpbmRvdy15PSIwIgogICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVk
      PSIxIgogICBpbmtzY2FwZTpjdXJyZW50LWxheWVyPSJMYXllcl8xIgogICBpbmtzY2FwZTpzaG93cGFn
      ZXNoYWRvdz0iMiIKICAgaW5rc2NhcGU6cGFnZWNoZWNrZXJib2FyZD0iMCIKICAgaW5rc2NhcGU6ZGVz
      a2NvbG9yPSIjZDFkMWQxIiAvPgo8c3R5bGUKICAgdHlwZT0idGV4dC9jc3MiCiAgIGlkPSJzdHlsZTIi
      PgoJLnN0MHtlbmFibGUtYmFja2dyb3VuZDpuZXcgICAgO30KCS5zdDF7ZmlsbDojMzczNjRFO30KCS5z
      dDJ7ZmlsbDojRjI2NzJDO30KPC9zdHlsZT4KCjxnCiAgIGlkPSJnNDQiCiAgIHRyYW5zZm9ybT0ibWF0
      cml4KDEwLjMyNTAwNiwwLDAsMTAuNzk2Nzg3LC0xMDg2LjEwOTIsLTM2NC4wMjcwOSkiPgoJPGcKICAg
      aWQ9ImczMCI+CgkJPHBhdGgKICAgY2xhc3M9InN0MiIKICAgZD0ibSAxNjkuNjIsODEuMjMgMTcuNTks
      MTguNzYgYyAwLjY4LDAuNzIgMC4xNywxLjkxIC0wLjgzLDEuOTEgaCAtMTAuODQgYyAtMC4zMSwwIC0w
      LjYxLC0wLjEzIC0wLjgyLC0wLjM2IEwgMTU5LjU2LDg1LjQ3IgogICBpZD0icGF0aDI4IiAvPgoJPC9n
      PgoJPHBhdGgKICAgY2xhc3M9InN0MiIKICAgZD0ibSAxNjIuOTcsNTguNDcgLTcuMDUsNi43OSBjIC0w
      LjIyLDAuMjEgLTAuMzUsMC41MSAtMC4zNSwwLjgxIHYgMTQuNTkgYyAwLDAuOTkgMS4xNywxLjUgMS45
      LDAuODMgbCA3LjA1LC02LjQ4IGMgMC4yMywtMC4yMSAwLjM3LC0wLjUyIDAuMzcsLTAuODMgdiAtMTQu
      OSBjIC0wLjAxLC0wLjk5IC0xLjIsLTEuNSAtMS45MiwtMC44MSB6IgogICBpZD0icGF0aDMyIiAvPgoJ
      PHBhdGgKICAgY2xhc3M9InN0MiIKICAgZD0ibSAxODYuOCw3My45MiAtMjkuMzMsMjYuMzYgYyAtMC43
      MywwLjY1IC0xLjg5LDAuMTQgLTEuODksLTAuODQgdiAtOS44MiBjIDAsLTAuMzIgMC4xMywtMC42MiAw
      LjM3LC0wLjg0IGwgMTguMDksLTE2LjU0IGMgMC4yMSwtMC4xOSAwLjQ4LC0wLjMgMC43NiwtMC4zIGgg
      MTEuMjQgYyAxLjA0LDAuMDEgMS41MywxLjI5IDAuNzYsMS45OCB6IgogICBpZD0icGF0aDM0IiAvPgoJ
      PGcKICAgaWQ9ImczOCI+CgkJPHBhdGgKICAgY2xhc3M9InN0MiIKICAgZD0ibSAxNDcuNjcsODUuNDcg
      LTE1LjE2LDE2LjA3IGMgLTAuMjEsMC4yMyAtMC41MSwwLjM2IC0wLjgyLDAuMzYgaCAtMTAuODQgYyAt
      MC45OSwwIC0xLjUsLTEuMTggLTAuODMsLTEuOTEgbCAxNy41OSwtMTguNzYiCiAgIGlkPSJwYXRoMzYi
      IC8+Cgk8L2c+Cgk8cGF0aAogICBjbGFzcz0ic3QyIgogICBkPSJtIDE0NC4yNyw1OC40NyA3LjA1LDYu
      NzkgYyAwLjIyLDAuMjEgMC4zNSwwLjUxIDAuMzUsMC44MSB2IDE0LjU5IGMgMCwwLjk5IC0xLjE3LDEu
      NSAtMS45LDAuODMgbCAtNy4wNSwtNi40OCBjIC0wLjIzLC0wLjIxIC0wLjM3LC0wLjUyIC0wLjM3LC0w
      LjgzIHYgLTE0LjkgYyAwLjAxLC0wLjk5IDEuMjEsLTEuNSAxLjkyLC0wLjgxIHoiCiAgIGlkPSJwYXRo
      NDAiIC8+Cgk8cGF0aAogICBjbGFzcz0ic3QyIgogICBkPSJtIDEyMC40NSw3My45MiAyOS4zMywyNi4z
      NiBjIDAuNzMsMC42NSAxLjg5LDAuMTQgMS44OSwtMC44NCB2IC05LjgyIGMgMCwtMC4zMiAtMC4xMywt
      MC42MiAtMC4zNywtMC44NCBMIDEzMy4yMSw3Mi4yNCBjIC0wLjIxLC0wLjE5IC0wLjQ4LC0wLjMgLTAu
      NzYsLTAuMyBIIDEyMS4yIGMgLTEuMDQsMC4wMSAtMS41MywxLjI5IC0wLjc1LDEuOTggeiIKICAgaWQ9
      InBhdGg0MiIgLz4KPC9nPgoKPC9zdmc+Cg==
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - pods
          - pods/exec
          - pods/log
          - persistentvolumeclaims
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - autoscaling
          - autoscaling.k8s.io
          resources:
          - horizontalpodautoscalers
          - verticalpodautoscalers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - m4e.krestomat.io
          resources:
          - moodles
          - moodles/status
          - moodles/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          - cronjobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - m4e.krestomat.io
          resources:
          - routines
          - routines/status
          - routines/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - m4e.krestomat.io
          resources:
          - nginxes
          - nginxes/status
          - nginxes/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - m4e.krestomat.io
          resources:
          - phpfpms
          - phpfpms/status
          - phpfpms/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: moodle-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: moodle-operator
          control-plane: controller-manager
        name: moodle-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-require-rbac
                - --metrics-secure
                - --metrics-bind-address=:8443
                - --leader-elect
                - --leader-election-id=moodle-operator
                - --health-probe-bind-address=:6789
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/krestomatio/moodle-operator:0.6.31
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: "2"
                    memory: 4Gi
                  requests:
                    cpu: 25m
                    memory: 50Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: moodle-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: moodle-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - moodle
  - nginx
  - php-fpm
  - ansible
  links:
  - name: Moodle Operator
    url: https://krestomatio.com/docs/moodle-operator
  - name: Moodle Image
    url: https://krestomatio.com/docs/container-builder/moodle
  - name: Moodle Repo
    url: https://github.com/moodle/moodle
  - name: Moodle Docs
    url: https://docs.moodle.org/
  maintainers:
  - email: jobcespedes@krestomatio.com
    name: Job Cespedes Ortiz
  maturity: alpha
  minKubeVersion: 1.26.0
  provider:
    name: Krestomatio
    url: https://krestomatio.com
  version: 0.6.31
