apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: mongodb-atlas-kubernetes-operator
    app.kubernetes.io/name: mongodb-atlas-kubernetes-operator
  name: atlasfederatedauths.atlas.mongodb.com
spec:
  group: atlas.mongodb.com
  names:
    categories:
    - atlas
    kind: AtlasFederatedAuth
    listKind: AtlasFederatedAuthList
    plural: atlasfederatedauths
    shortNames:
    - afa
    singular: atlasfederatedauth
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: AtlasFederatedAuth is the Schema for the Atlasfederatedauth API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              connectionSecretRef:
                description: |-
                  Connection secret with API credentials for configuring the federation.
                  These credentials must have OrganizationOwner permissions.
                properties:
                  name:
                    description: Name is the name of the Kubernetes Resource
                    type: string
                  namespace:
                    description: Namespace is the namespace of the Kubernetes Resource
                    type: string
                required:
                - name
                type: object
              dataAccessIdentityProviders:
                description: |-
                  The collection of unique ids representing the identity providers that can be used for data access in this organization.
                  Currently connected data access identity providers missing from the this field will be disconnected.
                items:
                  type: string
                type: array
              domainAllowList:
                description: Approved domains that restrict users who can join the
                  organization based on their email address.
                items:
                  type: string
                type: array
              domainRestrictionEnabled:
                default: false
                description: |-
                  Prevent users in the federation from accessing organizations outside of the federation, and creating new organizations.
                  This option applies to the entire federation.
                  See more information at https://www.mongodb.com/docs/atlas/security/federation-advanced-options/#restrict-user-membership-to-the-federation
                type: boolean
              enabled:
                default: false
                type: boolean
              postAuthRoleGrants:
                description: Atlas roles that are granted to a user in this organization
                  after authenticating.
                items:
                  type: string
                type: array
              roleMappings:
                description: Map IDP groups to Atlas roles.
                items:
                  description: RoleMapping maps an external group from an identity
                    provider to roles within Atlas.
                  properties:
                    externalGroupName:
                      description: ExternalGroupName is the name of the IDP group
                        to which this mapping applies.
                      maxLength: 200
                      minLength: 1
                      type: string
                    roleAssignments:
                      description: RoleAssignments define the roles within projects
                        that should be given to members of the group.
                      items:
                        properties:
                          projectName:
                            description: The Atlas project in the same org in which
                              the role should be given.
                            type: string
                          role:
                            description: The role in Atlas that should be given to
                              group members.
                            enum:
                            - ORG_MEMBER
                            - ORG_READ_ONLY
                            - ORG_BILLING_ADMIN
                            - ORG_GROUP_CREATOR
                            - ORG_OWNER
                            - ORG_BILLING_READ_ONLY
                            - ORG_TEAM_MEMBERS_ADMIN
                            - GROUP_AUTOMATION_ADMIN
                            - GROUP_BACKUP_ADMIN
                            - GROUP_MONITORING_ADMIN
                            - GROUP_OWNER
                            - GROUP_READ_ONLY
                            - GROUP_USER_ADMIN
                            - GROUP_BILLING_ADMIN
                            - GROUP_DATA_ACCESS_ADMIN
                            - GROUP_DATA_ACCESS_READ_ONLY
                            - GROUP_DATA_ACCESS_READ_WRITE
                            - GROUP_CHARTS_ADMIN
                            - GROUP_CLUSTER_MANAGER
                            - GROUP_SEARCH_INDEX_EDITOR
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
              ssoDebugEnabled:
                default: false
                type: boolean
            type: object
          status:
            properties:
              conditions:
                description: Conditions is the list of statuses showing the current
                  state of the Atlas Custom Resource
                items:
                  description: Condition describes the state of an Atlas Custom Resource
                    at a certain point.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of Atlas Custom Resource condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: |-
                  ObservedGeneration indicates the generation of the resource specification that the Atlas Operator is aware of.
                  The Atlas Operator updates this field to the 'metadata.generation' as soon as it starts reconciliation of the resource.
                format: int64
                type: integer
            required:
            - conditions
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
