apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ack-kms-metrics-service
spec:
  ports:
  - name: metricsport
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    control-plane: controller
  type: NodePort
status:
  loadBalancer: {}
