apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-keyspaces-reader
rules:
- apiGroups:
  - keyspaces.services.k8s.aws
  resources:
  - keyspaces
  verbs:
  - get
  - list
  - watch
