apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.2
  creationTimestamp: null
  name: documents.ssm.services.k8s.aws
spec:
  group: ssm.services.k8s.aws
  names:
    kind: Document
    listKind: DocumentList
    plural: documents
    singular: document
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Document is the Schema for the Documents API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DocumentSpec defines the desired state of Document.
            properties:
              attachments:
                description: A list of key-value pairs that describe attachments to
                  a version of a document.
                items:
                  description: |-
                    Identifying information about a document attachment, including the file name
                    and a key-value pair that identifies the location of an attachment to a document.
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                    values:
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              content:
                description: |-
                  The content for the new SSM document in JSON or YAML format. The content
                  of the document must not exceed 64KB. This quota also includes the content
                  specified for input parameters at runtime. We recommend storing the contents
                  for your new document in an external JSON or YAML file and referencing the
                  file in a command.

                  For examples, see the following topics in the Amazon Web Services Systems
                  Manager User Guide.

                     * Create an SSM document (console) (https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-using.html#create-ssm-console)

                     * Create an SSM document (command line) (https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-using.html#create-ssm-document-cli)

                     * Create an SSM document (API) (https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-using.html#create-ssm-document-api)
                type: string
              displayName:
                description: |-
                  An optional field where you can specify a friendly name for the SSM document.
                  This value can differ for each version of the document. You can update this
                  value at a later time using the UpdateDocument operation.

                  Regex Pattern: `^[\w\.\-\:\/ ]*$`
                type: string
              documentFormat:
                description: |-
                  Specify the document format for the request. The document format can be JSON,
                  YAML, or TEXT. JSON is the default format.
                type: string
              documentType:
                description: |-
                  The type of document to create.

                  The DeploymentStrategy document type is an internal-use-only document type
                  reserved for AppConfig.
                type: string
              name:
                description: |-
                  A name for the SSM document.

                  You can't use the following strings as document name prefixes. These are
                  reserved by Amazon Web Services for use as document name prefixes:

                     * aws

                     * amazon

                     * amzn

                     * AWSEC2

                     * AWSConfigRemediation

                     * AWSSupport

                  Regex Pattern: `^[a-zA-Z0-9_\-.]{3,128}$`
                type: string
              requires:
                description: |-
                  A list of SSM documents required by a document. This parameter is used exclusively
                  by AppConfig. When a user creates an AppConfig configuration in an SSM document,
                  the user must also specify a required document for validation purposes. In
                  this case, an ApplicationConfiguration document requires an ApplicationConfigurationSchema
                  document for validation purposes. For more information, see What is AppConfig?
                  (https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html)
                  in the AppConfig User Guide.
                items:
                  description: An SSM document required by the current document.
                  properties:
                    name:
                      type: string
                    requireType:
                      type: string
                    version:
                      type: string
                    versionName:
                      type: string
                  type: object
                type: array
              tags:
                description: |-
                  Optional metadata that you assign to a resource. Tags enable you to categorize
                  a resource in different ways, such as by purpose, owner, or environment.
                  For example, you might want to tag an SSM document to identify the types
                  of targets or the environment where it will run. In this case, you could
                  specify the following key-value pairs:

                     * Key=OS,Value=Windows

                     * Key=Environment,Value=Production

                  To add tags to an existing SSM document, use the AddTagsToResource operation.
                items:
                  description: |-
                    Metadata that you assign to your Amazon Web Services resources. Tags enable
                    you to categorize your resources in different ways, for example, by purpose,
                    owner, or environment. In Amazon Web Services Systems Manager, you can apply
                    tags to Systems Manager documents (SSM documents), managed nodes, maintenance
                    windows, parameters, patch baselines, OpsItems, and OpsMetadata.
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
              targetType:
                description: |-
                  Specify a target type to define the kinds of resources the document can run
                  on. For example, to run a document on EC2 instances, specify the following
                  value: /AWS::EC2::Instance. If you specify a value of '/' the document can
                  run on all types of resources. If you don't specify a value, the document
                  can't run on any resources. For a list of valid resource types, see Amazon
                  Web Services resource and property types reference (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html)
                  in the CloudFormation User Guide.

                  Regex Pattern: `^\/[\w\.\-\:\/]*$`
                type: string
              versionName:
                description: |-
                  An optional field specifying the version of the artifact you are creating
                  with the document. For example, Release12.1. This value is unique across
                  all versions of a document, and can't be changed.

                  Regex Pattern: `^[a-zA-Z0-9_\-.]{1,128}$`
                type: string
            required:
            - content
            - name
            type: object
          status:
            description: DocumentStatus defines the observed state of Document
            properties:
              ackResourceMetadata:
                description: |-
                  All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
                  that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: |-
                      ARN is the Amazon Resource Name for the resource. This is a
                      globally-unique identifier and is set only by the ACK service controller
                      once the controller has orchestrated the creation of the resource OR
                      when it has verified that an "adopted" resource (a resource where the
                      ARN annotation was set by the Kubernetes user on the CR) exists and
                      matches the supplied CR's Spec field values.
                      https://github.com/aws/aws-controllers-k8s/issues/270
                    type: string
                  ownerAccountID:
                    description: |-
                      OwnerAccountID is the AWS Account ID of the account that owns the
                      backend AWS service API resource.
                    type: string
                  region:
                    description: Region is the AWS region in which the resource exists
                      or will exist.
                    type: string
                required:
                - ownerAccountID
                - region
                type: object
              approvedVersion:
                description: |-
                  The version of the document currently approved for use in the organization.

                  Regex Pattern: `^([$]LATEST|[$]DEFAULT|^[1-9][0-9]*$)$`
                type: string
              attachmentsInformation:
                description: |-
                  Details about the document attachments, including names, locations, sizes,
                  and so on.
                items:
                  description: An attribute of an attachment, such as the attachment
                    name.
                  properties:
                    name:
                      type: string
                  type: object
                type: array
              author:
                description: The user in your organization who created the document.
                type: string
              category:
                description: |-
                  The classification of a document to help you identify and categorize its
                  use.
                items:
                  type: string
                type: array
              categoryEnum:
                description: The value that identifies a document's category.
                items:
                  type: string
                type: array
              conditions:
                description: |-
                  All CRs managed by ACK have a common `Status.Conditions` member that
                  contains a collection of `ackv1alpha1.Condition` objects that describe
                  the various terminal states of the CR and its backend AWS service API
                  resource
                items:
                  description: |-
                    Condition is the common struct used by all CRDs managed by ACK service
                    controllers to indicate terminal states  of the CR and its backend AWS
                    service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              createdDate:
                description: The date when the document was created.
                format: date-time
                type: string
              defaultVersion:
                description: |-
                  The default version.

                  Regex Pattern: `^([$]LATEST|[$]DEFAULT|^[1-9][0-9]*$)$`
                type: string
              description:
                description: A description of the document.
                type: string
              documentVersion:
                description: |-
                  The document version.

                  Regex Pattern: `^([$]LATEST|[$]DEFAULT|^[1-9][0-9]*$)$`
                type: string
              hash:
                description: |-
                  The Sha256 or Sha1 hash created by the system when the document was created.

                  Sha1 hashes have been deprecated.
                type: string
              hashType:
                description: |-
                  The hash type of the document. Valid values include Sha256 or Sha1.

                  Sha1 hashes have been deprecated.
                type: string
              latestVersion:
                description: |-
                  The latest version of the document.

                  Regex Pattern: `^([$]LATEST|[$]DEFAULT|^[1-9][0-9]*$)$`
                type: string
              owner:
                description: The Amazon Web Services user that created the document.
                type: string
              parameters:
                description: A description of the parameters for a document.
                items:
                  description: |-
                    Parameters specified in a Systems Manager document that run on the server
                    when the command is run.
                  properties:
                    defaultValue:
                      type: string
                    description:
                      type: string
                    name:
                      type: string
                    type_:
                      type: string
                  type: object
                type: array
              pendingReviewVersion:
                description: |-
                  The version of the document that is currently under review.

                  Regex Pattern: `^([$]LATEST|[$]DEFAULT|^[1-9][0-9]*$)$`
                type: string
              platformTypes:
                description: The list of operating system (OS) platforms compatible
                  with this SSM document.
                items:
                  type: string
                type: array
              reviewInformation:
                description: Details about the review of a document.
                items:
                  description: Information about the result of a document review request.
                  properties:
                    reviewedTime:
                      format: date-time
                      type: string
                    reviewer:
                      type: string
                    status:
                      type: string
                  type: object
                type: array
              reviewStatus:
                description: The current status of the review.
                type: string
              schemaVersion:
                description: |-
                  The schema version.

                  Regex Pattern: `^([0-9]+)\.([0-9]+)$`
                type: string
              sha1:
                description: The SHA1 hash of the document, which you can use for
                  verification.
                type: string
              status:
                description: The status of the SSM document.
                type: string
              statusInformation:
                description: |-
                  A message returned by Amazon Web Services Systems Manager that explains the
                  Status value. For example, a Failed status might be explained by the StatusInformation
                  message, "The specified S3 bucket doesn't exist. Verify that the URL of the
                  S3 bucket is correct."
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
