apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: knative-operator
    app.kubernetes.io/version: v1.8.0
    operator.knative.dev/release: v1.8.0
  name: operator-webhook-certs
