apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  creationTimestamp: null
  labels:
    alloydb-omni: "true"
  name: tdeconfigs.alloydbomni.dbadmin.goog
spec:
  group: alloydbomni.dbadmin.goog
  names:
    kind: TdeConfig
    listKind: TdeConfigList
    plural: tdeconfigs
    singular: tdeconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Schema for the TdeConfig CRD.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TdeConfigSpec defines the desired state of TDEConfig.
            properties:
              kekUrlRef:
                description: KekUrlRef is a reference to the Key Encryption Key (KEK)
                  URL stored in a ConfigMap.
                properties:
                  key:
                    description: The key to select.
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                  optional:
                    description: Specify whether the ConfigMap or its key must be
                      defined
                    type: boolean
                required:
                - key
                type: object
                x-kubernetes-map-type: atomic
              kmsProvider:
                description: KmsProvider specifies the KMS provider.
                properties:
                  vault:
                    description: Vault specifies the Hashicorp Vault provider.
                    properties:
                      authMount:
                        description: Path on the Vault server where the authentication
                          engine is mounted.
                        type: string
                      authType:
                        description: Authentication method
                        enum:
                        - jwt
                        type: string
                      jwt:
                        description: JWT specifies the JWT authentication method.
                        properties:
                          pathRef:
                            description: PathRef is a reference to the path to the
                              JWT token on the host stored in a ConfigMap.
                            properties:
                              key:
                                description: The key to select.
                                type: string
                              name:
                                description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                  TODO: Add other useful fields. apiVersion, kind,
                                  uid?'
                                type: string
                              optional:
                                description: Specify whether the ConfigMap or its
                                  key must be defined
                                type: boolean
                            required:
                            - key
                            type: object
                            x-kubernetes-map-type: atomic
                          role:
                            description: Role is the role for JWT authentication.
                            type: string
                        required:
                        - pathRef
                        type: object
                    required:
                    - authMount
                    - authType
                    - jwt
                    type: object
                required:
                - vault
                type: object
            required:
            - kekUrlRef
            - kmsProvider
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
