apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    alloydbomni.internal.dbadmin.goog/task-type: monitoring
    control-plane: controller-manager
  name: fleet-controller-manager-metrics-service
spec:
  ports:
  - name: metricsalloydbomni
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    fleet-control-plane: controller-manager
status:
  loadBalancer: {}
