apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configauditreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/managed-by: starboard
spec:
  group: aquasecurity.github.io
  names:
    kind: ConfigAuditReport
    listKind: ConfigAuditReportList
    plural: configauditreports
    singular: configauditreport
    categories: []
    shortNames:
      - configaudit
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      additionalPrinterColumns:
        - name: Scanner
          type: string
          description: The name of the config audit scanner
          jsonPath: .report.scanner.name
        - name: Age
          type: date
          description: The age of the report
          jsonPath: .metadata.creationTimestamp
        - name: Danger
          type: integer
          priority: 1
          description: The number of checks that failed with Danger status
          jsonPath: .report.summary.dangerCount
        - name: Warning
          type: integer
          priority: 1
          description: The number of checks that failed with Warning status
          jsonPath: .report.summary.warningCount
        - name: Pass
          type: integer
          priority: 1
          description: The number of checks that passed
          jsonPath: .report.summary.passCount
      served: true
      storage: true
      subresources:
        status: {}
