---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  creationTimestamp: null
  name: vectorcollections.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: VectorCollection
    listKind: VectorCollectionList
    plural: vectorcollections
    shortNames:
    - vc
    singular: vectorcollection
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the Vector Collection Config
      jsonPath: .status.state
      name: Status
      type: string
    - description: Name of the Hazelcast resource that this resource is created for
      jsonPath: .spec.hazelcastResourceName
      name: Hazelcast-Resource
      priority: 1
      type: string
    - description: Message for the current Vector Collection Config
      jsonPath: .status.message
      name: Message
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VectorCollection is the Schema for the vectorcollections API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: VectorCollectionSpec defines the desired state of VectorCollection
            properties:
              hazelcastResourceName:
                description: |-
                  HazelcastResourceName defines the name of the Hazelcast resource that this resource is
                  created for.
                minLength: 1
                type: string
              indexes:
                description: Information about indexes configuration
                items:
                  properties:
                    dimension:
                      description: Dimension of the vector.
                      format: int32
                      type: integer
                    efConstruction:
                      description: EfConstruction is the size of the search queue
                        to use when finding nearest neighbors.
                      format: int32
                      type: integer
                    maxDegree:
                      description: MaxDegree is used to calculate the maximum number
                        of neighbors per node. The calculation used is max-degree
                        * 2.
                      format: int32
                      type: integer
                    metric:
                      description: Metric is used to calculate the distance between
                        two vectors.
                      enum:
                      - Euclidean
                      - Cosine
                      - Dot
                      type: string
                    name:
                      description: |-
                        Name is name of the vector index. Can include letters, numbers, and the symbols - and _.
                        Required for single-index vector collections. Optional for multi-index collection.
                      pattern: ^[a-zA-Z0-9_\-]*$
                      type: string
                    useDeduplication:
                      description: UseDeduplication specify whether to use vector
                        deduplication.
                      type: boolean
                  required:
                  - dimension
                  - efConstruction
                  - maxDegree
                  - metric
                  - useDeduplication
                  type: object
                minItems: 1
                type: array
              name:
                description: |-
                  Name of the data structure config to be created. If empty, CR name will be used.
                  It cannot be updated after the config is created successfully.
                pattern: ^[a-zA-Z0-9_\-*]*$
                type: string
            required:
            - hazelcastResourceName
            - indexes
            type: object
          status:
            description: VectorCollectionStatus defines the observed state of VectorCollection
            properties:
              memberStatuses:
                additionalProperties:
                  enum:
                  - Success
                  - Failed
                  - Pending
                  - Persisting
                  - Terminating
                  type: string
                description: Holds status of data structure for each Hazelcast member
                type: object
              message:
                description: Message explaining the current state
                type: string
              state:
                description: State of the data structure
                enum:
                - Success
                - Failed
                - Pending
                - Persisting
                - Terminating
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
