apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: keycloaks.v1.edp.epam.com
spec:
  group: v1.edp.epam.com
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Is connected to keycloak
      jsonPath: .status.connected
      name: Connected
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Keycloak is the Schema for the keycloaks API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeycloakSpec defines the desired state of Keycloak.
            properties:
              adminType:
                description: AdminType can be user or serviceAccount, if serviceAccount
                  was specified, then client_credentials grant type should be used
                  for getting admin realm token.
                enum:
                - serviceAccount
                - user
                type: string
              secret:
                description: Secret is a secret name which contains admin credentials.
                type: string
              url:
                description: URL of keycloak service.
                type: string
            required:
            - secret
            - url
            type: object
          status:
            description: KeycloakStatus defines the observed state of Keycloak.
            properties:
              connected:
                description: Connected shows if keycloak service is up and running.
                type: boolean
            required:
            - connected
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - deprecated: true
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Keycloak is the Schema for the keycloaks API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeycloakSpec defines the desired state of Keycloak.
            properties:
              adminType:
                description: AdminType can be user or serviceAccount, if serviceAccount
                  was specified, then client_credentials grant type should be used
                  for getting admin realm token
                enum:
                - serviceAccount
                - user
                type: string
              installMainRealm:
                nullable: true
                type: boolean
              realmName:
                type: string
              secret:
                description: Secret is the name of the k8s object Secret related to
                  keycloak
                type: string
              ssoRealmName:
                type: string
              url:
                description: URL of keycloak service
                type: string
              users:
                description: Users is a list of keycloak users
                items:
                  properties:
                    realmRoles:
                      description: RealmRoles is a list of roles attached to keycloak
                        user
                      items:
                        type: string
                      type: array
                    username:
                      description: Username of keycloak user
                      type: string
                  required:
                  - username
                  type: object
                nullable: true
                type: array
            required:
            - secret
            - url
            type: object
          status:
            description: KeycloakStatus defines the observed state of Keycloak.
            properties:
              connected:
                type: boolean
            required:
            - connected
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
