apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  creationTimestamp: null
  name: nfsprovisioners.cache.jhouse.com
spec:
  group: cache.jhouse.com
  names:
    kind: NFSProvisioner
    listKind: NFSProvisionerList
    plural: nfsprovisioners
    singular: nfsprovisioner
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NFSProvisioner is the Schema for the nfsprovisioners API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NFSProvisionerSpec defines the desired state of NFSProvisioner
            properties:
              hostPathDir:
                description: HostPathDir is the direcotry where NFS server will use.
                type: string
              nfsImageConfiguration:
                description: NFSImageConfigurations hold the image configuration
                properties:
                  image:
                    default: k8s.gcr.io/sig-storage/nfs-provisioner@sha256:e943bb77c7df05ebdc8c7888b2db289b13bf9f012d6a3a5a74f14d4d5743d439
                    description: Set nfs provisioner operator image
                    type: string
                  imagePullPolicy:
                    default: IfNotPresent
                    description: Image PullPolicy is for nfs provisioner operator
                      image.
                    type: string
                required:
                - image
                - imagePullPolicy
                type: object
              nodeSelector:
                additionalProperties:
                  type: string
                description: NFS server will be running on a specific node by NodeSeletor
                type: object
              pvc:
                description: |-
                  PVC Name is the PVC resource that already created for NFS server.
                  Do not set StorageClass name with this param. Then, operator will fail to deploy NFS Server.
                type: string
              scForNFS:
                description: StorageClass Name for NFS Provisioner is the StorageClass
                  name that NFS Provisioner will use. Default value is `nfs`
                type: string
              scForNFSPvc:
                description: |-
                  StorageClass Name for NFS server will provide a PVC for NFS server.
                  Do not set PVC name with this param. Then, operator will fail to deploy NFS Server
                type: string
              storageSize:
                description: |-
                  StorageSize is the PVC size for NFS server.
                  By default, it sets 10G.
                type: string
            type: object
          status:
            description: NFSProvisionerStatus defines the observed state of NFSProvisioner
            properties:
              error:
                description: Error show error messages briefly
                type: string
              nodes:
                description: Nodes are the names of the NFS pods
                items:
                  type: string
                type: array
            required:
            - error
            - nodes
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
