apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qualys-nanny
  name: qualys-qualysplatformconfig-viewer-role
rules:
- apiGroups:
  - qualys.io
  resources:
  - qualysplatformconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qualys.io
  resources:
  - qualysplatformconfigs/status
  verbs:
  - get
