apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 1.4.1
  name: dynatrace-edgeconnect
