production:
  type: k8s
  bundle:
    registry: quay.io
    organization: operatorhubio
  index:
    registry: quay.io
    organization: operatorhubio
    name: catalog_tmp
    tags:
      - latest
    latest: ""
    signature:
      enabled: 0
      alias: not-defined
      endpoint: https://not-defined
  mirror:
    enabled: 1
    multiarch:
      base: quay.io/operator-framework/opm
      base_tags:
        - v1.57.0
      postfix: s
    registry: quay.io
    organization: operatorhubio
    name: catalog
    username:
      in: framework_automation
      out: framework_automation
  test:
    installation_skip:
      - ack-
      - otc-rds-operator

pipeline:
  base: https://github.com
  repo: k8s-operatorhub/community-operators
  branch: main
  ci_scripts_dir: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts
  image: quay.io/operator_testing/operator-test-playbooks:latest
  playbooks:
    repo: https://github.com/redhat-openshift-ecosystem/operator-test-playbooks
    branch: "upstream-community"
  assignees:
    - mporrato
    - Allda
  automerge:
    enabled: 1
  reviewers:
    enabled: 1
  notifications:
    slack: 1
  package_manifest_disabled: 1
operatorhubio:
  enabled: 1
  registry: quay.io
  organization: operator-framework
  name: upstream-community-operators
  tag: latest

#base:
#  organisation: operator-framework
#  project: operator-test-playbooks
#  tag: master
tools:
  kind_version: v0.23.0
  kind_kube_version: v1.30.0
  operator_sdk_version: v1.36.0
