apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ack-ec2-metrics-service
spec:
  ports:
  - name: metricsport
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: ack-ec2-controller
  type: ClusterIP
status:
  loadBalancer: {}
