apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: operator-webhook
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/version: v1.21.0
  name: operator-webhook-certs
