annotations:
  # Core bundle annotations.
  operators.operatorframework.io.bundle.mediatype.v1: registry+v1
  operators.operatorframework.io.bundle.manifests.v1: manifests/
  operators.operatorframework.io.bundle.metadata.v1: metadata/
  operators.operatorframework.io.bundle.package.v1: prometheus-exporter-operator
  operators.operatorframework.io.bundle.channels.v1: alpha
  operators.operatorframework.io.bundle.channel.default.v1: alpha

  # Annotations for testing.
  operators.operatorframework.io.test.mediatype.v1: scorecard+v1
  operators.operatorframework.io.test.config.v1: tests/scorecard/

  # Adding com.redhat.openshift.versions programmatically
  # This annotation was added because was possible to identify that this distribution uses API(s),
  # which were removed in the k8s version 1.22 and OpenShift version OCP 4.9. Then, it will prevent the bundle from being distributed on 4.9.
  # Please, ensure that your project is no longer using these API(s) and that you start to
  # distribute solutions which is compatible with OpenShift 4.9.
  # For further information, see: https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138
  com.redhat.openshift.versions: "v4.6-v4.8"
  operatorhub.io/ui-metadata-max-k8s-version: "1.21"