apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: sn-operator-system/sn-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.15.0
  creationTimestamp: null
  name: connectorcatalogs.k8s.streamnative.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: sn-operator-webhook-service
          namespace: sn-operator-system
          path: /convert
      conversionReviewVersions:
      - v1
  group: k8s.streamnative.io
  names:
    kind: ConnectorCatalog
    listKind: ConnectorCatalogList
    plural: connectorcatalogs
    singular: connectorcatalog
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ConnectorCatalog is the Schema for the connectorcatalogs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ConnectorCatalogSpec defines the desired state of ConnectorCatalog
            properties:
              connectorDefinitions:
                items:
                  properties:
                    defaultSchemaType:
                      type: string
                    defaultSerdeClassName:
                      type: string
                    description:
                      type: string
                    iconLink:
                      type: string
                    id:
                      type: string
                    imageRegistry:
                      type: string
                    imageRepository:
                      type: string
                    imageTag:
                      type: string
                    jarFullName:
                      type: string
                    name:
                      type: string
                    sinkClass:
                      type: string
                    sinkConfigClass:
                      type: string
                    sinkConfigFieldDefinitions:
                      items:
                        properties:
                          attributes:
                            additionalProperties:
                              type: string
                            type: object
                          fieldName:
                            type: string
                          typeName:
                            type: string
                        required:
                        - fieldName
                        - typeName
                        type: object
                      type: array
                    sinkDocLink:
                      type: string
                    sinkTypeClassName:
                      type: string
                    sourceClass:
                      type: string
                    sourceConfigClass:
                      type: string
                    sourceConfigFieldDefinitions:
                      items:
                        properties:
                          attributes:
                            additionalProperties:
                              type: string
                            type: object
                          fieldName:
                            type: string
                          typeName:
                            type: string
                        required:
                        - fieldName
                        - typeName
                        type: object
                      type: array
                    sourceDocLink:
                      type: string
                    sourceTypeClassName:
                      type: string
                    typeClassName:
                      type: string
                    version:
                      type: string
                  required:
                  - id
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - id
                x-kubernetes-list-type: map
            required:
            - connectorDefinitions
            type: object
          status:
            description: ConnectorCatalogStatus defines the observed state of ConnectorCatalog
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
