apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    aerospike-kubernetes-operator/version: 4.0.1
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  name: aerospikebackups.asdb.aerospike.com
spec:
  group: asdb.aerospike.com
  names:
    kind: AerospikeBackup
    listKind: AerospikeBackupList
    plural: aerospikebackups
    singular: aerospikebackup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.backupService.name
      name: Backup Service Name
      type: string
    - jsonPath: .spec.backupService.namespace
      name: Backup Service Namespace
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: AerospikeBackup is the Schema for the aerospikebackup API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: AerospikeBackupSpec defines the desired state of AerospikeBackup
              for a given AerospikeCluster
            properties:
              backupService:
                description: |-
                  BackupService is the backup service reference i.e. name and namespace.
                  It is used to communicate to the backup service to trigger backups. This field is immutable
                properties:
                  name:
                    description: Backup service name
                    type: string
                  namespace:
                    description: Backup service namespace
                    type: string
                required:
                - name
                - namespace
                type: object
              config:
                description: |-
                  Config is the free form configuration for the backup in YAML format.
                  This config is used to trigger backups. It includes: aerospike-cluster, backup-routines.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              onDemandBackups:
                description: OnDemandBackups is the configuration for on-demand backups.
                items:
                  properties:
                    delay:
                      description: Delay is the interval before starting the on-demand
                        backup.
                      type: string
                    id:
                      description: ID is the unique identifier for the on-demand backup.
                      minLength: 1
                      type: string
                    routineName:
                      description: RoutineName is the routine name used to trigger
                        on-demand backup.
                      type: string
                  required:
                  - id
                  - routineName
                  type: object
                maxItems: 1
                type: array
            required:
            - backupService
            - config
            type: object
          status:
            description: AerospikeBackupStatus defines the observed state of AerospikeBackup
            properties:
              backupService:
                description: BackupService is the backup service reference i.e. name
                  and namespace.
                properties:
                  name:
                    description: Backup service name
                    type: string
                  namespace:
                    description: Backup service namespace
                    type: string
                required:
                - name
                - namespace
                type: object
              config:
                description: |-
                  Config is the configuration for the backup in YAML format.
                  This config is used to trigger backups. It includes: aerospike-cluster, backup-routines.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              onDemandBackups:
                description: OnDemandBackups is the configuration for on-demand backups.
                items:
                  properties:
                    delay:
                      description: Delay is the interval before starting the on-demand
                        backup.
                      type: string
                    id:
                      description: ID is the unique identifier for the on-demand backup.
                      minLength: 1
                      type: string
                    routineName:
                      description: RoutineName is the routine name used to trigger
                        on-demand backup.
                      type: string
                  required:
                  - id
                  - routineName
                  type: object
                type: array
            required:
            - backupService
            - config
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
