apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: mongodb-atlas-kubernetes-operator
    app.kubernetes.io/name: mongodb-atlas-kubernetes-operator
  name: atlasbackuppolicies.atlas.mongodb.com
spec:
  group: atlas.mongodb.com
  names:
    kind: AtlasBackupPolicy
    listKind: AtlasBackupPolicyList
    plural: atlasbackuppolicies
    singular: atlasbackuppolicy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: AtlasBackupPolicy is the Schema for the atlasbackuppolicies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AtlasBackupPolicySpec defines the desired state of AtlasBackupPolicy
            properties:
              items:
                description: A list of BackupPolicy items
                items:
                  properties:
                    frequencyInterval:
                      description: Desired frequency of the new backup policy item
                        specified by FrequencyType. A value of 1 specifies the first
                        instance of the corresponding FrequencyType. The only accepted
                        value you can set for frequency interval with NVMe clusters
                        is 12.
                      enum:
                      - 1
                      - 2
                      - 4
                      - 6
                      - 8
                      - 12
                      type: integer
                    frequencyType:
                      description: 'Frequency associated with the backup policy item.
                        One of the following values: hourly, daily, weekly or monthly.
                        You cannot specify multiple hourly and daily backup policy
                        items.'
                      enum:
                      - hourly
                      - daily
                      - weekly
                      - monthly
                      type: string
                    retentionUnit:
                      description: 'Scope of the backup policy item: days, weeks,
                        or months'
                      enum:
                      - days
                      - weeks
                      - months
                      type: string
                    retentionValue:
                      description: Value to associate with RetentionUnit
                      type: integer
                  required:
                  - frequencyInterval
                  - frequencyType
                  - retentionUnit
                  - retentionValue
                  type: object
                type: array
            required:
            - items
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
