apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: lm-credentials
    app.kubernetes.io/part-of: logicmonitor-operator
  name: lm-credentials
stringData:
  accessID: REPLACE_WITH_ACCESS_ID
  accessKey: REPLACE_WITH_ACCESS_KEY
  account: REPLACE_WITH_ACCOUNT
type: Opaque
