apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: logicmonitor-openshift-operator
  name: logicmonitor-openshift-operator-lmcontainer-viewer-role
rules:
- apiGroups:
  - monitoring.logicmonitor.com
  resources:
  - lmcontainers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.logicmonitor.com
  resources:
  - lmcontainers/status
  verbs:
  - get
