apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  creationTimestamp: null
  name: jetjobs.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: JetJob
    listKind: JetJobList
    plural: jetjobs
    shortNames:
    - jj
    singular: jetjob
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the JetJob
      jsonPath: .status.phase
      name: Status
      type: string
    - description: ID of the JetJob
      jsonPath: .status.id
      name: Id
      type: string
    - description: Name of the Hazelcast resource that this resource is created for
      jsonPath: .spec.hazelcastResourceName
      name: Hazelcast-Resource
      priority: 1
      type: string
    - description: Time when the JetJob was submitted
      jsonPath: .status.submissionTime
      name: SubmissionTime
      type: string
    - description: Time when the JetJob was completed
      jsonPath: .status.completionTime
      name: CompletionTime
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: JetJob is the Schema for the jetjobs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JetJobSpec defines the desired state of JetJob
            properties:
              bucketConfig:
                description: Bucket config from where the JAR files will be downloaded.
                properties:
                  bucketURI:
                    description: 'URL of the bucket to download HotBackup folders.
                      AWS S3, GCP Bucket and Azure Blob storage buckets are supported.
                      Example bucket URIs: - AWS S3     -> s3://bucket-name/path/to/folder
                      - GCP Bucket -> gs://bucket-name/path/to/folder - Azure Blob
                      -> azblob://bucket-name/path/to/folder'
                    minLength: 6
                    type: string
                  secret:
                    description: secret is a deprecated alias for secretName.
                    type: string
                  secretName:
                    description: Name of the secret with credentials for cloud providers.
                    type: string
                required:
                - bucketURI
                type: object
              hazelcastResourceName:
                description: HazelcastResourceName defines the name of the Hazelcast
                  resource that this resource is created for.
                minLength: 1
                type: string
              initialSnapshotResourceName:
                description: InitialSnapshotResourceName specify the name of the JetJobSnapshot
                  object from which the JetJob is initialized.
                type: string
              jarName:
                description: JarName specify the name of the Jar to run that is present
                  on the member.
                minLength: 1
                type: string
              mainClass:
                description: MainClass is the name of the main class that will be
                  run on the submitted job.
                type: string
              name:
                description: Name of the JetJob to be created. If empty, CR name will
                  be used. It cannot be updated after the config is created successfully.
                type: string
              parameters:
                description: Parameters to be passed to Jet Job.
                items:
                  type: string
                type: array
              remoteURL:
                description: URL from where the file will be downloaded.
                type: string
              state:
                default: Running
                description: State is used to manage the job state.
                enum:
                - Running
                - Suspended
                - Canceled
                - Restarted
                type: string
            required:
            - hazelcastResourceName
            - jarName
            - state
            type: object
          status:
            description: JetJobStatus defines the observed state of JetJob
            properties:
              completionTime:
                format: date-time
                type: string
              failureText:
                type: string
              id:
                format: int64
                type: integer
              phase:
                enum:
                - Failed
                - NotRunning
                - Starting
                - Running
                - Suspended
                - SuspendedExportingSnapshot
                - Completing
                - ExecutionFailed
                - Completed
                type: string
              submissionTime:
                format: date-time
                type: string
              suspensionCause:
                type: string
            required:
            - id
            - phase
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
