apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  creationTimestamp: null
  name: caches.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: Cache
    listKind: CacheList
    plural: caches
    shortNames:
    - ch
    singular: cache
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the Cache Config
      jsonPath: .status.state
      name: Status
      type: string
    - description: Name of the Hazelcast resource that this resource is created for
      jsonPath: .spec.hazelcastResourceName
      name: Hazelcast-Resource
      priority: 1
      type: string
    - description: Message for the current Cache Config
      jsonPath: .status.message
      name: Message
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Cache is the Schema for the caches API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CacheSpec defines the desired state of Cache It cannot be
              updated after the Cache is created
            properties:
              asyncBackupCount:
                default: 0
                description: Number of asynchronous backups.
                format: int32
                maximum: 6
                minimum: 0
                type: integer
              backupCount:
                default: 1
                description: Number of synchronous backups.
                format: int32
                maximum: 6
                minimum: 0
                type: integer
              eventJournal:
                description: EventJournal specifies event journal configuration of
                  the Cache
                properties:
                  capacity:
                    default: 10000
                    description: Capacity sets the capacity of the ringbuffer underlying
                      the event journal.
                    format: int32
                    type: integer
                  timeToLiveSeconds:
                    default: 0
                    description: TimeToLiveSeconds indicates how long the items remain
                      in the event journal before they are expired.
                    format: int32
                    type: integer
                type: object
              hazelcastResourceName:
                description: HazelcastResourceName defines the name of the Hazelcast
                  resource that this resource is created for.
                minLength: 1
                type: string
              inMemoryFormat:
                default: BINARY
                description: InMemoryFormat specifies in which format data will be
                  stored in your cache
                enum:
                - BINARY
                - OBJECT
                - NATIVE
                type: string
              keyType:
                description: Class name of the key type
                type: string
              name:
                description: Name of the data structure config to be created. If empty,
                  CR name will be used. It cannot be updated after the config is created
                  successfully.
                type: string
              persistenceEnabled:
                default: false
                description: When enabled, cache data will be persisted.
                type: boolean
              userCodeNamespace:
                description: Name of the User Code Namespace applied to this instance
                minLength: 1
                type: string
              valueType:
                description: Class name of the value type
                type: string
            required:
            - hazelcastResourceName
            type: object
          status:
            description: CacheStatus defines the observed state of Cache
            properties:
              memberStatuses:
                additionalProperties:
                  enum:
                  - Success
                  - Failed
                  - Pending
                  - Persisting
                  - Terminating
                  type: string
                description: Holds status of data structure for each Hazelcast member
                type: object
              message:
                description: Message explaining the current state
                type: string
              state:
                description: State of the data structure
                enum:
                - Success
                - Failed
                - Pending
                - Persisting
                - Terminating
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
