apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  creationTimestamp: null
  name: repositorycreationtemplates.ecr.services.k8s.aws
spec:
  group: ecr.services.k8s.aws
  names:
    kind: RepositoryCreationTemplate
    listKind: RepositoryCreationTemplateList
    plural: repositorycreationtemplates
    singular: repositorycreationtemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RepositoryCreationTemplate is the Schema for the RepositoryCreationTemplates
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              RepositoryCreationTemplateSpec defines the desired state of RepositoryCreationTemplate.

              The details of the repository creation template associated with the request.
            properties:
              appliedFor:
                description: |-
                  A list of enumerable strings representing the Amazon ECR repository creation
                  scenarios that this template will apply towards. The two supported scenarios
                  are PULL_THROUGH_CACHE and REPLICATION
                items:
                  type: string
                type: array
              customRoleARN:
                description: |-
                  The ARN of the role to be assumed by Amazon ECR. This role must be in the
                  same account as the registry that you are configuring. Amazon ECR will assume
                  your supplied role when the customRoleArn is specified. When this field isn't
                  specified, Amazon ECR will use the service-linked role for the repository
                  creation template.
                type: string
              customRoleRef:
                description: "AWSResourceReferenceWrapper provides a wrapper around
                  *AWSResourceReference\ntype to provide more user friendly syntax
                  for references using 'from' field\nEx:\nAPIIDRef:\n\n\tfrom:\n\t
                  \ name: my-api"
                properties:
                  from:
                    description: |-
                      AWSResourceReference provides all the values necessary to reference another
                      k8s resource for finding the identifier(Id/ARN/Name)
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                type: object
              description:
                description: A description for the repository creation template.
                type: string
              encryptionConfiguration:
                description: The encryption configuration to use for repositories
                  created using the template.
                properties:
                  encryptionType:
                    type: string
                  kmsKey:
                    type: string
                type: object
              imageTagMutability:
                description: |-
                  The tag mutability setting for the repository. If this parameter is omitted,
                  the default setting of MUTABLE will be used which will allow image tags to
                  be overwritten. If IMMUTABLE is specified, all image tags within the repository
                  will be immutable which will prevent them from being overwritten.
                type: string
              imageTagMutabilityExclusionFilters:
                description: |-
                  A list of filters that specify which image tags should be excluded from the
                  repository creation template's image tag mutability setting.
                items:
                  description: |-
                    A filter that specifies which image tags should be excluded from the repository's
                    image tag mutability setting.
                  properties:
                    filter:
                      type: string
                    filterType:
                      type: string
                  type: object
                type: array
              lifecyclePolicy:
                description: The lifecycle policy to use for repositories created
                  using the template.
                type: string
              prefix:
                description: |-
                  The repository namespace prefix to associate with the template. All repositories
                  created using this namespace prefix will have the settings defined in this
                  template applied. For example, a prefix of prod would apply to all repositories
                  beginning with prod/. Similarly, a prefix of prod/team would apply to all
                  repositories beginning with prod/team/.

                  To apply a template to all repositories in your registry that don't have
                  an associated creation template, you can use ROOT as the prefix.

                  There is always an assumed / applied to the end of the prefix. If you specify
                  ecr-public as the prefix, Amazon ECR treats that as ecr-public/. When using
                  a pull through cache rule, the repository prefix you specify during rule
                  creation is what you should specify as your repository creation template
                  prefix as well.

                  Regex Pattern: `^((?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*/?|ROOT)$`
                type: string
                x-kubernetes-validations:
                - message: Value is immutable once set
                  rule: self == oldSelf
              repositoryPolicy:
                description: |-
                  The repository policy to apply to repositories created using the template.
                  A repository policy is a permissions policy associated with a repository
                  to control access permissions.
                type: string
              resourceTags:
                description: |-
                  The metadata to apply to the repository to help you categorize and organize.
                  Each tag consists of a key and an optional value, both of which you define.
                  Tag keys can have a maximum character length of 128 characters, and tag values
                  can have a maximum length of 256 characters.
                items:
                  description: |-
                    The metadata to apply to a resource to help you categorize and organize them.
                    Each tag consists of a key and a value, both of which you define. Tag keys
                    can have a maximum character length of 128 characters, and tag values can
                    have a maximum length of 256 characters.
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            required:
            - appliedFor
            - prefix
            type: object
          status:
            description: RepositoryCreationTemplateStatus defines the observed state
              of RepositoryCreationTemplate
            properties:
              ackResourceMetadata:
                description: |-
                  All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
                  that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: |-
                      ARN is the Amazon Resource Name for the resource. This is a
                      globally-unique identifier and is set only by the ACK service controller
                      once the controller has orchestrated the creation of the resource OR
                      when it has verified that an "adopted" resource (a resource where the
                      ARN annotation was set by the Kubernetes user on the CR) exists and
                      matches the supplied CR's Spec field values.
                      https://github.com/aws/aws-controllers-k8s/issues/270
                    type: string
                  ownerAccountID:
                    description: |-
                      OwnerAccountID is the AWS Account ID of the account that owns the
                      backend AWS service API resource.
                    type: string
                  region:
                    description: Region is the AWS region in which the resource exists
                      or will exist.
                    type: string
                required:
                - ownerAccountID
                - region
                type: object
              conditions:
                description: |-
                  All CRs managed by ACK have a common `Status.Conditions` member that
                  contains a collection of `ackv1alpha1.Condition` objects that describe
                  the various terminal states of the CR and its backend AWS service API
                  resource
                items:
                  description: |-
                    Condition is the common struct used by all CRDs managed by ACK service
                    controllers to indicate terminal states  of the CR and its backend AWS
                    service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              createdAt:
                description: |-
                  The date and time, in JavaScript date format, when the repository creation
                  template was created.
                format: date-time
                type: string
              updatedAt:
                description: |-
                  The date and time, in JavaScript date format, when the repository creation
                  template was last updated.
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
