apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: fence-agents-remediation-operator
  name: fenceagentsremediationtemplates.fence-agents-remediation.medik8s.io
spec:
  group: fence-agents-remediation.medik8s.io
  names:
    kind: FenceAgentsRemediationTemplate
    listKind: FenceAgentsRemediationTemplateList
    plural: fenceagentsremediationtemplates
    shortNames:
    - fartemplate
    singular: fenceagentsremediationtemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FenceAgentsRemediationTemplate is the Schema for the fenceagentsremediationtemplates
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FenceAgentsRemediationTemplateSpec defines the desired state
              of FenceAgentsRemediationTemplate
            properties:
              template:
                description: Template defines the desired state of FenceAgentsRemediationTemplate
                properties:
                  spec:
                    description: FenceAgentsRemediationSpec defines the desired state
                      of FenceAgentsRemediation
                    properties:
                      agent:
                        description: |-
                          Agent is the name of fence agent that will be used.
                          It should have a fence_ prefix.
                        pattern: fence_.+
                        type: string
                      nodeSecretNames:
                        additionalProperties:
                          type: string
                        description: NodeSecretNames maps the node name to the Secret
                          name which contains params relevant for that node.
                        type: object
                      nodeparameters:
                        additionalProperties:
                          additionalProperties:
                            type: string
                          type: object
                        description: NodeParameters are passed to the fencing agent
                          according to the node that is fenced, since they are node
                          specific
                        type: object
                      remediationStrategy:
                        default: ResourceDeletion
                        description: |-
                          RemediationStrategy is the remediation method for unhealthy nodes.
                          Currently, it could be either "OutOfServiceTaint" or "ResourceDeletion".
                          ResourceDeletion will iterate over all pods related to the unhealthy node and delete them.
                          OutOfServiceTaint will add the out-of-service taint which is a new well-known taint "node.kubernetes.io/out-of-service"
                          that enables automatic deletion of pv-attached pods on failed nodes, "out-of-service" taint is only supported on clusters with k8s version 1.26+ or OCP/OKD version 4.13+.
                        enum:
                        - ResourceDeletion
                        - OutOfServiceTaint
                        type: string
                      retrycount:
                        default: 5
                        description: RetryCount is the number of times the fencing
                          agent will be executed
                        type: integer
                      retryinterval:
                        default: 5s
                        description: RetryInterval is the interval between each fencing
                          agent execution
                        pattern: ^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$
                        type: string
                      sharedSecretName:
                        default: fence-agents-credentials-shared
                        description: |-
                          SharedSecretName is the name of the Secret which will contain params needed for FAR in order to remediate any node.
                          Using this Secret is optional.
                        type: string
                      sharedparameters:
                        additionalProperties:
                          type: string
                        description: SharedParameters are parameters common to all
                          nodes
                        type: object
                      timeout:
                        default: 60s
                        description: Timeout is the timeout for each fencing agent
                          execution
                        pattern: ^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$
                        type: string
                    required:
                    - agent
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
          status:
            description: FenceAgentsRemediationTemplateStatus defines the observed
              state of FenceAgentsRemediationTemplate
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
