apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: oracle-database-operator-system/oracle-database-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.17.3
  creationTimestamp: null
  name: ordssrvs.database.oracle.com
spec:
  group: database.oracle.com
  names:
    kind: OrdsSrvs
    listKind: OrdsSrvsList
    plural: ordssrvs
    singular: ordssrvs
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: status
      type: string
    - jsonPath: .status.workloadType
      name: workloadType
      type: string
    - jsonPath: .status.ordsVersion
      name: ordsVersion
      type: string
    - jsonPath: .status.httpPort
      name: httpPort
      type: integer
    - jsonPath: .status.httpsPort
      name: httpsPort
      type: integer
    - jsonPath: .status.mongoPort
      name: MongoPort
      type: integer
    - jsonPath: .status.restartRequired
      name: restartRequired
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    - jsonPath: .status.ordsInstalled
      name: OrdsInstalled
      type: boolean
    name: v4
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              encPrivKey:
                properties:
                  passwordKey:
                    default: password
                    type: string
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              forceRestart:
                type: boolean
              globalSettings:
                properties:
                  apex.download:
                    default: false
                    type: boolean
                  apex.download.url:
                    default: https://download.oracle.com/otn_software/apex/apex-latest.zip
                    type: string
                  apex.installation.persistence:
                    properties:
                      accessMode:
                        default: ReadWriteOnce
                        enum:
                        - ReadWriteOnce
                        - ReadWriteMany
                        type: string
                      size:
                        default: 1Gi
                        type: string
                      storageClass:
                        type: string
                      volumeName:
                        type: string
                    type: object
                  cache.metadata.enabled:
                    type: boolean
                  cache.metadata.graphql.expireAfterAccess:
                    type: string
                  cache.metadata.graphql.expireAfterWrite:
                    type: string
                  cache.metadata.jwks.enabled:
                    type: boolean
                  cache.metadata.jwks.expireAfterAccess:
                    type: string
                  cache.metadata.jwks.expireAfterWrite:
                    type: string
                  cache.metadata.jwks.initialCapacity:
                    format: int32
                    type: integer
                  cache.metadata.jwks.maximumSize:
                    format: int32
                    type: integer
                  cache.metadata.timeout:
                    type: string
                  certSecret:
                    properties:
                      cert:
                        type: string
                      key:
                        type: string
                      secretName:
                        type: string
                    required:
                    - cert
                    - key
                    - secretName
                    type: object
                  database.api.enabled:
                    type: boolean
                  database.api.management.services.disabled:
                    type: boolean
                  db.invalidPoolTimeout:
                    type: string
                  debug.printDebugToScreen:
                    type: boolean
                  enable.mongo.access.log:
                    default: false
                    type: boolean
                  enable.standalone.access.log:
                    default: false
                    type: boolean
                  error.responseFormat:
                    type: string
                  feature.grahpql.max.nesting.depth:
                    format: int32
                    type: integer
                  icap.port:
                    format: int32
                    type: integer
                  icap.secure.port:
                    format: int32
                    type: integer
                  icap.server:
                    type: string
                  log.procedure:
                    type: boolean
                  mongo.enabled:
                    type: boolean
                  mongo.idle.timeout:
                    type: string
                  mongo.op.timeout:
                    type: string
                  mongo.port:
                    default: 27017
                    format: int32
                    type: integer
                  request.traceHeaderName:
                    type: string
                  security.credentials.attempts:
                    format: int32
                    type: integer
                  security.credentials.lock.time:
                    type: string
                  security.disableDefaultExclusionList:
                    type: boolean
                  security.exclusionList:
                    type: string
                  security.externalSessionTrustedOrigins:
                    type: string
                  security.forceHTTPS:
                    type: boolean
                  security.httpsHeaderCheck:
                    type: string
                  security.inclusionList:
                    type: string
                  security.maxEntries:
                    format: int32
                    type: integer
                  security.verifySSL:
                    type: boolean
                  standalone.context.path:
                    default: /ords
                    type: string
                  standalone.http.port:
                    default: 8080
                    format: int32
                    type: integer
                  standalone.https.host:
                    type: string
                  standalone.https.port:
                    default: 8443
                    format: int32
                    type: integer
                  standalone.stop.timeout:
                    type: string
                type: object
              image:
                type: string
              imagePullPolicy:
                default: IfNotPresent
                enum:
                - IfNotPresent
                - Always
                - Never
                type: string
              imagePullSecrets:
                type: string
              poolSettings:
                items:
                  properties:
                    apex.security.administrator.roles:
                      type: string
                    apex.security.user.roles:
                      type: string
                    autoUpgradeAPEX:
                      default: false
                      type: boolean
                    autoUpgradeORDS:
                      default: false
                      type: boolean
                    db.adminUser:
                      type: string
                    db.adminUser.secret:
                      properties:
                        passwordKey:
                          default: password
                          type: string
                        secretName:
                          type: string
                      required:
                      - secretName
                      type: object
                    db.cdb.adminUser:
                      type: string
                    db.cdb.adminUser.secret:
                      properties:
                        passwordKey:
                          default: password
                          type: string
                        secretName:
                          type: string
                      required:
                      - secretName
                      type: object
                    db.connectionType:
                      enum:
                      - basic
                      - tns
                      - customurl
                      type: string
                    db.credentialsSource:
                      enum:
                      - pool
                      - request
                      type: string
                    db.customURL:
                      type: string
                    db.hostname:
                      type: string
                    db.poolDestroyTimeout:
                      type: string
                    db.port:
                      format: int32
                      type: integer
                    db.secret:
                      properties:
                        passwordKey:
                          default: password
                          type: string
                        secretName:
                          type: string
                      required:
                      - secretName
                      type: object
                    db.servicename:
                      type: string
                    db.sid:
                      type: string
                    db.tnsAliasName:
                      type: string
                    db.username:
                      default: ORDS_PUBLIC_USER
                      type: string
                    db.wallet.zip.service:
                      type: string
                    dbWalletSecret:
                      properties:
                        secretName:
                          type: string
                        walletName:
                          type: string
                      required:
                      - secretName
                      - walletName
                      type: object
                    debug.trackResources:
                      type: boolean
                    feature.openservicebroker.exclude:
                      type: boolean
                    feature.sdw:
                      type: boolean
                    http.cookie.filter:
                      type: string
                    jdbc.DriverType:
                      enum:
                      - thin
                      - oci8
                      type: string
                    jdbc.InactivityTimeout:
                      format: int32
                      type: integer
                    jdbc.InitialLimit:
                      format: int32
                      type: integer
                    jdbc.MaxConnectionReuseCount:
                      format: int32
                      type: integer
                    jdbc.MaxConnectionReuseTime:
                      type: string
                    jdbc.MaxLimit:
                      format: int32
                      type: integer
                    jdbc.MaxStatementsLimit:
                      format: int32
                      type: integer
                    jdbc.MinLimit:
                      format: int32
                      type: integer
                    jdbc.SecondsToTrustIdleConnection:
                      format: int32
                      type: integer
                    jdbc.auth.admin.role:
                      type: string
                    jdbc.auth.enabled:
                      type: boolean
                    jdbc.cleanup.mode:
                      type: string
                    jdbc.statementTimeout:
                      format: int32
                      type: integer
                    misc.defaultPage:
                      type: string
                    misc.pagination.maxRows:
                      format: int32
                      type: integer
                    owa.trace.sql:
                      type: boolean
                    plsql.gateway.mode:
                      enum:
                      - disabled
                      - direct
                      - proxied
                      type: string
                    poolName:
                      type: string
                    procedure.preProcess:
                      type: string
                    procedure.rest.preHook:
                      type: string
                    procedurePostProcess:
                      type: string
                    restEnabledSql.active:
                      type: boolean
                    security.jwks.connection.timeout:
                      type: string
                    security.jwks.read.timeout:
                      type: string
                    security.jwks.refresh.interval:
                      type: string
                    security.jwks.size:
                      format: int32
                      type: integer
                    security.jwt.allowed.age:
                      type: string
                    security.jwt.allowed.skew:
                      type: string
                    security.jwt.profile.enabled:
                      type: boolean
                    security.requestAuthenticationFunction:
                      type: string
                    security.requestValidationFunction:
                      default: ords_util.authorize_plsql_gateway
                      type: string
                    security.validationFunctionType:
                      enum:
                      - plsql
                      - javascript
                      type: string
                    soda.defaultLimit:
                      type: string
                    soda.maxLimit:
                      type: string
                    tnsAdminSecret:
                      properties:
                        secretName:
                          type: string
                      required:
                      - secretName
                      type: object
                  required:
                  - db.secret
                  - poolName
                  type: object
                type: array
              replicas:
                default: 1
                format: int32
                minimum: 1
                type: integer
              serviceAccountName:
                type: string
              workloadType:
                default: Deployment
                enum:
                - Deployment
                - StatefulSet
                - DaemonSet
                type: string
            required:
            - globalSettings
            - image
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              httpPort:
                format: int32
                type: integer
              httpsPort:
                format: int32
                type: integer
              mongoPort:
                format: int32
                type: integer
              ordsInstalled:
                type: boolean
              ordsVersion:
                type: string
              restartRequired:
                type: boolean
              status:
                type: string
              workloadType:
                type: string
            required:
            - restartRequired
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
