apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  creationTimestamp: null
  labels:
    alloydb-omni: "true"
  name: instancebackups.alloydbomni.internal.dbadmin.goog
spec:
  group: alloydbomni.internal.dbadmin.goog
  names:
    kind: InstanceBackup
    listKind: InstanceBackupList
    plural: instancebackups
    shortNames:
    - aooib
    singular: instancebackup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.completeTime
      name: CompleteTime
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: InstanceBackup is the Schema for the InstanceBackup API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: InstanceBackupSpec defines the desired state of an AlloyDB
              Omni InstanceBackup.
            properties:
              backupSourceRole:
                default: primary
                description: Role of Backup Source, allowing to specify backup source
                  role as an enum in {"primary", "standby"} This field is optional
                  Default to primary if not specified
                enum:
                - primary
                - standby
                type: string
              dbclusterRef:
                description: The DBCluster this backup belongs to
                type: string
              instanceBackupPlanRef:
                description: Name of the InstanceBackupPlan from which this backup
                  was created.
                type: string
              manual:
                default: false
                description: Indicate whether this backup is a scheduled or manual
                  backup
                type: boolean
              physicalBackupSpec:
                description: PhysicalBackupSpec contains spec for physical backups.
                properties:
                  backupType:
                    default: full
                    description: BackupType is the type of backup to be created. It's
                      an enum in {"full","diff","incr"}. Default to full if not specified.
                    enum:
                    - full
                    - diff
                    - incr
                    type: string
                type: object
            type: object
          status:
            description: InstanceBackupStatus defines the observed state of an AlloyDB
              Omni InstanceBackup.
            properties:
              completeTime:
                description: Completion time of the Backup
                format: date-time
                type: string
              conditions:
                description: Conditions represents the latest available observations
                  of the Entity's current state.
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    \n type FooStatus struct{ // Represents the observations of a
                    foo's current state. // Known .status.conditions.type are: \"Available\",
                    \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
                    // +listType=map // +listMapKey=type Conditions []metav1.Condition
                    `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
                    protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              createTime:
                description: Create time of the underlying Backup.
                format: date-time
                type: string
              criticalIncidents:
                description: CriticalIncidents is a flat list of all active Critical
                  Incidents.
                items:
                  description: CriticalIncident contains all information about an
                    ongoing critical incident.
                  properties:
                    code:
                      description: Code is the error code of this particular error.
                        Error codes are DBSE+numeric strings, like "DBSE1012".
                      type: string
                    createTime:
                      description: CreateTime is the timestamp when this Incident
                        was created at the origin.
                      format: date-time
                      type: string
                    message:
                      description: Message describes the incident/error that occurred.
                      type: string
                    messageTemplateParams:
                      additionalProperties:
                        type: string
                      description: MessageTemplateParams contains key-value pairs
                        necessary for generating a user-friendly data-driven version
                        of Message in the UI.
                      type: object
                    resource:
                      description: Resource contains information about the Database
                        Service component that reported the incident as well as about
                        the K8s resource.
                      properties:
                        component:
                          description: Component is an internal identifier of the
                            Database Service subsystem that reported the incident.
                          type: string
                        location:
                          description: Location
                          properties:
                            cluster:
                              description: Cluster is the name of the cluster of the
                                affected K8S resource.
                              type: string
                            group:
                              description: Group is the Group name of the k8s resource.
                              type: string
                            kind:
                              description: Kind is the Kind of the k8s resource.
                              type: string
                            name:
                              description: Name is the name of the affected K8S resource.
                              type: string
                            namespace:
                              description: Namespace is the namespace of the affected
                                K8S resource.
                              type: string
                            version:
                              description: Group is the Version of the k8s resource.
                              type: string
                          type: object
                      required:
                      - component
                      type: object
                    stackTrace:
                      description: StackTrace contains an unstructured list of messages
                        from the stack trace.
                      items:
                        description: CriticalIncidentStackTraceMessage contains stack
                          trace information available for the incident.
                        properties:
                          component:
                            description: Component is the name of a Database Service
                              component that logged the message.
                            type: string
                          message:
                            description: Logged message.
                            type: string
                        type: object
                      type: array
                    transientUntil:
                      description: TransientUntil if present indicates that the issue
                        should be considered transient until the specified time.
                      format: date-time
                      type: string
                  required:
                  - code
                  - createTime
                  - resource
                  type: object
                type: array
              observedGeneration:
                description: 'Internal: The generation observed by the controller.'
                format: int64
                type: integer
              phase:
                description: InstanceBackupPhase is the phase of a backup.
                type: string
              physicalBackupStatus:
                description: PhysicalBackupStatus contains status info that are specific
                  for physical backups.
                properties:
                  backupID:
                    description: BackupID is the unique identifier of the physical
                      backup, as tracked by pgBackRest. This ID is used to reference
                      the backup for restore operations.
                    type: string
                  backupType:
                    description: BackupType indicates the type of the backup performed.
                      It can be "full", "diff" (differential), or "incr" (incremental).
                    type: string
                  compressed:
                    description: Compressed specifies whether the backup data is compressed
                      to save space.
                    type: boolean
                  encrypted:
                    description: Encrypted specifies whether the backup data is encrypted.
                    type: boolean
                  endTime:
                    description: EndTime records the exact time when the pgBackRest
                      backup process completed.
                    format: date-time
                    type: string
                  lsn:
                    description: LSN contains the starting and ending Log Sequence
                      Numbers (LSN) for the backup. The LSNs provide a precise point
                      in the database's transaction log, defining the exact scope
                      of the data included in the backup and ensuring accurate recovery.
                    properties:
                      start:
                        description: Start specifies the starting LSN, marking the
                          beginning of the data included in the backup.
                        type: string
                      stop:
                        description: Stop specifies the ending LSN, marking the end
                          of the data included in the backup.
                        type: string
                    type: object
                  priorBackup:
                    description: PriorBackup identifies the preceding backup that
                      this backup relies upon. This is particularly relevant for incremental
                      and differential backups.
                    type: string
                  size:
                    description: Size provides detailed information about the various
                      sizes related to the backup, such as the total size of the database
                      and the size of the backup data itself.
                    properties:
                      backupSetSize:
                        anyOf:
                        - type: integer
                        - type: string
                        description: BackupSetSize is the size of all the files from
                          this backup and any referenced backups in the repository
                          that are required to restore the database from this backup
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      backupSize:
                        anyOf:
                        - type: integer
                        - type: string
                        description: BackupSize is the size of only the files in this
                          backup (which will also be the same for full backups).
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      databaseBackupSize:
                        anyOf:
                        - type: integer
                        - type: string
                        description: DatabaseBackupSize is the amount of data in the
                          database to actually back up (which will be the same for
                          full backups).
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      databaseSize:
                        anyOf:
                        - type: integer
                        - type: string
                        description: DatabaseSize is the full uncompressed size of
                          the database to be backed up.
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                    type: object
                  startTime:
                    description: StartTime records the exact time when the pgBackRest
                      backup process initiated.
                    format: date-time
                    type: string
                  wal:
                    description: WAL contains the names of the starting and ending
                      Write-Ahead Log (WAL) files associated with this backup. The
                      WAL files are essential for ensuring data consistency and enabling
                      point-in-time recovery.
                    properties:
                      start:
                        description: Start specifies the name of the first WAL file
                          required for the backup.
                        type: string
                      stop:
                        description: Stop specifies the name of the last WAL file
                          included in the backup.
                        type: string
                    type: object
                type: object
              reconciled:
                description: 'Internal: Whether the resource was reconciled by the
                  controller.'
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
