apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  name: nexusscripts.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: NexusScript
    listKind: NexusScriptList
    plural: nexusscripts
    singular: nexusscript
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NexusScript is the Schema for the nexusscripts API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NexusScriptSpec defines the desired state of NexusScript.
            properties:
              content:
                description: Content is the content of the script.
                example: security.setAnonymousAccess(Boolean.valueOf(args))
                type: string
              execute:
                default: false
                description: Execute defines if script should be executed after creation.
                type: boolean
              name:
                description: |-
                  Name is the id of the script.
                  Name should be unique across all scripts.
                example: anonymous
                maxLength: 512
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              nexusRef:
                description: NexusRef is a reference to Nexus custom resource.
                properties:
                  kind:
                    default: Nexus
                    description: Kind specifies the kind of the Nexus resource.
                    type: string
                  name:
                    description: Name specifies the name of the Nexus resource.
                    type: string
                required:
                - name
                type: object
              payload:
                description: Payload is the payload of the script.
                example: "true"
                type: string
            required:
            - content
            - name
            - nexusRef
            type: object
          status:
            description: NexusScriptStatus defines the observed state of NexusScript.
            properties:
              error:
                description: Error is an error message if something went wrong.
                type: string
              executed:
                description: Executed defines if script was executed.
                type: boolean
              value:
                description: Value is a status of the script.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
