
name: "Documentation"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      number-of-prs:
        description: 'Number of PRs'     
        required: true
        default: '5000'
env:
  OPP_THIS_REPO: "k8s-operatorhub/community-operators"

jobs:
  documentation:
    runs-on: ubuntu-latest
    container: quay.io/operator_testing/community-operators-mkdocs
    steps:
    - uses: actions/checkout@v2
      with:
        repository: redhat-openshift-ecosystem/community-operators-pipeline
        ref: documentation
    - name: Generate docs
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ci/operator-flow/doc.sh ${{ github.event.inputs.number-of-prs }} ${OPP_THIS_REPO}
        mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
